General:
  OutputFile: "Outputs/projections_outputs/loop/Projections_CC_Enu_3.25to3.50.root"
  #OutputFile: "outputs/testing.root"
  DUNESamples: ["Configs/Samples/SamplePDFDune_NDGAr_FHC_numuselec.yaml"]
  #Nu-FIT
  #OscillationParameters: [0.310, 0.582, 0.224, 7.39E-5, 2.5254E-3, -2.498]
  # T2K-like best-fit
  OscillationParameters: [0.307, 0.528, 0.0218, 7.53e-5, 2.509e-3, -1.601, 1284.9, 2.848]
  OscillatorConfigName: "Configs/OscillatorObj.yaml"
  Systematics:
    XsecCovFile: ["Configs/CovObjs/xsec_covariance_DUNE_systs_NDGAr.yaml"]
    XsecCovName: "xsec_cov"
    XsecStepScale: 0.1
    XsecAtGen: false
    OscCovFile: ["Configs/CovObjs/OscCov_PDG2021_v2.yaml"]
    OscCovName: "osc_cov"
    OscFix: ["baseline"]
  Fitter:
    FitTestLikelihood: false
  MCMC:
    NSteps: 2000
    AutoSave: 10000
  Output:
    FileName: "TestEventRates.root"
    OUTPUTNAME: "TestLLH.root"
  ProcessMCMC: No
  Seed: 0
  Debug: No
GeneralKinematicCuts:
  - Name: "InFDV"
    VarString: "InFDV"
    Range: [1., 2.]
  - Name: "IsCC"
    VarString: "IsCC"
    Range: [1., 2.]
  - Name: "Enu"
    VarString: "TrueNeutrinoEnergy"
    Range: [3.25, 3.50]
"Projections": [{"Name": "TrueQ3_vs_TrueQ0", "VarStrings": ["TrueQ3", "TrueQ0"], "VarBins": [[175, 0., 3.5], [150, 0., 3.]]}, {"Name": "Accepted_TrueQ3_vs_TrueQ0", "VarStrings": ["TrueQ3", "TrueQ0"], "VarBins": [[175, 0., 3.5], [150, 0., 3.]], "KinematicCuts": [{"Range": [1., 2.], "Name": "IsEventAccepted", "VarString": "Event_IsAccepted"}]}]
