---
General:
  OutputFile: "CIFit.root"
  DUNESamples: ["CIValidations/CIInputs/CISampleConfig.yaml"]
  # Nu-FIT
  OscillationParameters: [0.310, 0.582, 0.0224, 7.39E-5, 2.525E-3, -2.498, 1284.9, 2.848] 
  OscillatorConfigName: "Configs/OscillatorObj.yaml"

  Systematics:
    XsecCovFile: ["CIValidations/CIInputs/CIXsecConfig.yaml"]
    XsecCovName: "xsec_cov"
    XsecStepScale: 0.05
    XsecAtGen: false
    OscCovFile: ["Configs/CovObjs/OscCov_PDG2021_v2.yaml"]
    OscCovName: "osc_cov"
    OscFix: ["baseline", "density"]

  Fitter:
    FitTestLikelihood: false
  MCMC:
    NSteps: 2000
    AutoSave: 10000
  Output:
    FileName: "TestEventRates.root"
    OUTPUTNAME: "TestLLH.root"
  ProcessMCMC: No
  Seed: 0
  Debug: No
