---
Systematics:
- Systematic:
    Names:
      FancyName: Norm_Param_0
    Error: 0.11
    FlatPrior: false
    IsFixed: false
    Mode: [ 0 ]
    ParameterBounds: [0, 999.]
    ParameterGroup: Xsec
    ParameterValues:
      Generated: 1.
      PreFitValue: 1.
    DetID: ["ND", "FD", "ATM"]
    StepScale:
      MCMC: 0.2
    Type: Norm