---
# This is the config you plug into MaCh3 applications
# For information on YAML syntax, see https://quickref.me/yaml.html

# We start with the "General" section
# This contains the bulk of the settings
General:
  # The name of the output file. If it already exists, it will be overwritten so remember to change the name before running!!!
  OutputFile: "MaCh3_Output_0.6.root"

  # Here we can list the paths to the DUNE sample CONFIG files.
  DUNESamples: ["PreMadeConfigs/SampleConfig.yaml"]  

  # We can also set the value of the oscillation parameters here
  # For different oscillators we require different sets of parameters. (CUDAProb3 and NuFAST are just 2 pieces of software to calculate oscillation probabilities.)
  OscillationParameters: [0.307, 0.546, 0.0220, 7.53E-5, 2.536E-3, -1.601, 1284.9, 2.848] #CUDAProb3
  #OscillationParameters: [0.310, 0.582, 0.0224, 7.39E-5, 2.525E-3, -2.498, 1284.9, 2.848,  0.5] #NuFAST
  SharedNuOscillatorObject:
    BeamFD: "Configs/NuOsc/CUDAProb3Linear_binned.yaml"


  Seed: 0

  # Now we can look at systematics
  Systematics:
    # For historicaly reasons we call our systematics "xsec" (despite the fact that they're not necessarily cross-section related)
    # First we list our systmatic configuration yamls
    XsecCovFile: ["PreMadeConfigs/SystematicConfig.yaml", "Configs/SystematicConfigs/OscSystematicConfig.yaml"]
    # This is just a label for MaCh3 to use internally
    XsecCovName: "xsec_cov"

    # This is the step scale used in MCMC. For more information about scale factors 
    # please read: https://www2.stat.duke.edu/~pdh10/Teaching/564/Sup/mhalgorithm.pdf
    XsecStepScale: 0.9
    XsecFix: [ "baseline", "density", "Ye", "prod_height" ]

  FittingAlgorithm: "MR2T2"
  Fitter:
    FitTestLikelihood: false

  # For MCMC
  MCMC:
    NSteps: 1000000 # We'll be running a short chain, so only 1000 steps
    AutoSave: 10000 # This 


# For LLH scans we need these settings
LLHScan:
  LLHScanBySample: true
  ScanRanges:
    sin2th_23: [0.35,0.65]
    delm2_23: [-0.0029,0.0029]


# For Sigma Variations
SigmaVar:
  # This will scan at 0, ±1 and ±3 standard deviations from the "nominal" value of each systematic
  SigmaArray: [-3, -1, 0, 1, 3]

PlotSigmaVariation:
  ParamNames: ["DummyNorm"]
  Coulour: [632]


ProcessMCMC:
  #Select which parameter names to remove, for example all flux, look for starting string
  ExcludedNames: []
  #ExcludedNames: ["Norm_"]
  #Select which parameter to remove based on to whcih group they belong, like Xsec, Flux or Osc
  ExcludedGroups: []
  #ExcludedNames: ["Osc"]
  #Select which parameters blocks to reject for example ND and FD detector, look for starting string
  # WARNING this is used only for Legacy pramtaers i.e. one which do not use parameterHandlerGeneric
  ExcludedTypes: []
  # Allow to decrease number of entries if chain is HUUGE
  #MaxEntries = 10000

  #AdditionalCuts
  Posterior1DCut: ""
  #Posterior1DCut: "delm2_23 > 0"

  #Basic settings
  PlotRelativeToPrior: false
  PrintToPDF: true
  #if false it will not plot error band for parameters with flat prior
  PlotErrorForFlatPrior: false
  FancyNames: true
  PlotBinValue: false

  #Correlation related
  Smoothing: true

  #Functionality 1D
  MakeCredibleIntervals: true
  CalcBayesFactor: true
  CalcSavageDickey: true
  CalcBipolarPlot: false
  CalcParameterEvolution: true

  #Functionality 2D
  PlotCorr: true
  MakeSubOptimality: ["false", 100]
  MakeViolin: true
  MakeCredibleRegions: false
  GetTrianglePlot: true
  #Perform some covariance stability test
  DiagnoseCovarianceMatrix: false
  # Assign weight to each mcmc step according to new prior
  ReweightPrior: false
  #Perform Kolmogorov Smirnov test, only works when at least two files are being processed
  PerformKStest: true

  #KS: Credible Intervals/Regions Cosmetic, code has default values so even if you don't pass anything still code will produce fancy plots :)
  CredibleIntervals: [0.99, 0.90, 0.68]
  #In case of sigma, please set CredibleInSigmas to true first
  #CredibleIntervals: [3, 2, 1]
  #kCyan+4, kCyan-2, kCyan-10
  CredibleIntervalsColours: [436, 430, 422]

  #If true Credible intervals should be in percentage
  CredibleInSigmas: false
  CredibleRegions: [0.99, 0.90, 0.68]
  #In case of sigma, please set CredibleInSigmas to true first
  #CredibleRegions: [3, 2, 1]
  # kDashed, kSolid, kDotted
  CredibleRegionStyle: [2, 1, 3]
  #kGreen-3, kGreen-10, kGreen
  CredibleRegionColor: [413, 406, 416]

  #KS: Plot only 2D posteriors with correlations greater than 0.2
  Post2DPlotThreshold: 0.2

  # Used for diagnostic covariance matrix
  NIntervals: 5

  BayesFactor:
    # Goes as follows: ParamName Name[Model 1, Model 2], Model1[lower, upper ], Model2[lower, upper ]
    - ["delm2_23", ["IH", "NH"], [-0.01, 0], [0, 0.01]]
    - ["sin2th_23", ["LO", "UO"], [0, 0.5], [0.5, 1]]

  SavageDickey:
    - ["BinnedSplineParam1", 1.0, [0, 2]]  # Last array doesn't matter as parameter has Gaussian

  BipolarPlot:
    - ["BinnedSplineParam1", [0, 1]]

    #KS: Feel free to pass whatever combination you like
  TrianglePlot:
    - ["Test", ["Norm_Param_0", "Norm_Param_1", "BinnedSplineParam1", "BinnedSplineParam2"]]

  #First is paramter name and second number of intervals
  ParameterEvolution:
    - ["Norm_Param_0", 20]

  Thinning: [false, 100]

  #First param name, then new prior and new prior error
  # apply reactor constraints [vector of param names] [vector of new central value] [vector of new prior errors]
  PriorReweighting: [ ["sin2th_13"], [0.0220], [0.0007] ]
  #Fancy example, not physics motivated but to show functionality
  #PriorReweighting: [ ["MAQE", "Pauli_Blocking_C_nu"], [1.05, 0.1], [ 0.04, 0.5] ]

  # This allows to specify custom bin edges for usual 1D plotting
  CustomBinEdges:
    delta_cp: [-3.141592, 3.141592]

