SampleName: "numuselec"
SampleType: "Atm"
# SelectionCuts:
#   - KinematicStr: "TrueXPos"
#     Bounds: [ -310.0, 310.0 ]
#   - KinematicStr: "TrueYPos"
#     Bounds: [ -550.0, 550.0 ]
#   - KinematicStr: "TrueZPos"
#     Bounds: [ 50.0, 1244.0 ]
Binning:
  XVarStr: "RecoCosineZ"
  XVarBins: [-1, -0.77, -0.26, 0.33, 0.81, 1]
  YVarStr: "RecoNeutrinoEnergy"
  YVarBins: [0, 0.19, 0.25, 0.37, 0.72, 1.31, 2.34, 4.47, 12.01, 1e8]
SampleBools:
  IsELike: no
InputFiles:
  mtupleprefix: "inputs/Atmospherics/CAFs/atm_hd"
  mtuplesuffix: "_numuselec.root"
  splineprefix: ""
  splinesuffix: ""
DetID: 24
NuOsc:
  NuOscConfigFile: "configs/NuOsc/CUDAProb3.yaml"
NSubSamples: 2
SubSamples:
  - name: "nue_x_nue"
    mtuplefile: "nue_x_nue"
    splinefile: "nue_x_nue"
    samplevecno: 0
    nutype: 12
    oscnutype: 12
    signal: false
  - name: "nue_x_numu"
    mtuplefile: "nue_x_numu"
    splinefile: "nue_x_numu"
    samplevecno: 1
    nutype: 12
    oscnutype: 14
    signal: true