---
#Global Sample Handler setting
SampleHandlerName: "PDSP"
POT: 2.1428e+21
MaCh3ModeConfig: "MaCh3Modes.yaml"

LikelihoodOptions:
  #False means you calculate W2 histogram only during first reweight, advisable for Barlow-Beeston
  UpdateW2: true
  TestStatistic: "Poisson"

BinningFile: "PDSP/PDSPBinning.yaml"
InputFiles:
  PrepSplineFile: false

#Settings for a single sample
Samples: ["PDSP"]
Tutorial_Beam:
  SelectionCuts:
    - KinematicStr: "TrueKEInt"
      Bounds: [ 0., 4 ]
  SampleTitle: "PDSP"

  Binning:
    VarStr : [ "RecoKEInt" ]
    VarBins: [[1, 1.5, 2, 2.5]]
    Uniform: true

  InputFiles:
    mtupleprefix: "/home/bhuller/work/analysis_main/analysis_input/root_analysis_input_mc_selected/mc_mc_selected_*"
    mtuplesuffix: ".root"

  SubSamples:
    - Name: "absorption"
      LatexName: "abs"
      mtuplefile: "Tabsorption"
      splinefile: ""
      nutype: 14
      oscnutype: 14
    - Name: "charge_exchange"
      LatexName: "cex"
      mtuplefile: "Tcharge_exchange"
      splinefile: ""
      nutype: 14
      oscnutype: 14
    - Name: "single_pion_production"
      LatexName: "spip"
      mtuplefile: "Tsingle_pion_production"
      splinefile: ""
      nutype: 14
      oscnutype: 14
    - Name: "pion_production"
      LatexName: "pip"
      mtuplefile: "Tpion_production"
      splinefile: ""
      nutype: 14
      oscnutype: 14
