SampleName: "FHC_nue"
SampleType: "BeamND"
POT: 1.3628319e+23 #Actual POT /POT_gen *This POT ### Maybe put to 1
SelectionCuts:
Binning:
  XVarStr: "RecoNeutrinoEnergy" 
  XVarBins: [0.,  0.5,  1.,  1.25, 1.5, 1.75, 2., 2.25, 2.5, 2.75, 3., 3.25, 3.5, 3.75, 4., 5., 6., 10.]
SampleBools:
  IsELike: true
  isrhc: false
  iselike: true
InputFiles:
  mtupleprefix: "inputs/DUNE_ND_CAF_files/MicroProdN3p1_NDLAr_2E18_FHC.caf.nu.0000001.CAF" #name of file
  mtuplesuffix: ".root"
  splineprefix: ""
  splinesuffix: ""
NuOsc:
  NuOscConfigFile: "configs/NuOsc/CUDAProb3Linear.yaml"
DetID: 1 #1 is for ND-LAr
NSubSamples: 1
SubSamples:
  - name: ""
    mtuplefile: ""
    splinefile: ""
    samplevecno: 0
    nutype: 14
    oscnutype: 14
