---
SampleTitle: "ND_FHC_CCnumu"
SampleType: "BeamND"

POT: 3.85e21
MaCh3ModeConfig: "Configs/CovObjs/MaCh3Modes_GENIE.yaml"
SampleName: "ND_LAr_FHC"

BinningFile: "Configs/Samples/BeamParameterBinning.yaml"

Binning:
  XVarStr: "RecoNeutrinoEnergy"
  XVarBins: [0., 0.5, 1., 1.25, 1.5, 1.75, 2., 2.25, 2.5, 2.75, 3., 3.25, 3.5, 3.75, 4., 5., 6., 10.]
  YVarStr: "yRec"
  YVarBins: [0., 0.1, 0.2, 0.3, 0.4, 0.6, 1.1]

DUNESampleBools:
  isFHC: 1
  iselike: no

InputFiles:
  mtupleprefix: "Inputs/DUNE_ND_CAF_files/ND_FHC_ger_"
  mtuplesuffix: "_fv_ccinc_q.root"
  splineprefix: "Inputs/DUNE_ND_spline_files/ND_FHC_ger_"
  splinesuffix: "_splines.root"

NuOsc:
  NuOscConfigFile: "Configs/NuOsc/CUDAProb3Linear.yaml"
  EqualBinningPerOscChannel: false

SubSamples:
  - Name: "FHC_numu_x_numu"
    LatexName: "FHC_numu_x_numu"
    mtuplefile: "numu_x_numu_*"
    splinefile: "numu_x_numu"
    nutype: 14
    oscnutype: 14
  - Name: "FHC_nue_x_nue"
    LatexName: "FHC_nue_x_nue"
    mtuplefile: "nue_x_nue"
    splinefile: "nue_x_nue"
    nutype: 12
    oscnutype: 12
  - Name: "FHC_numubar_x_numubar"
    LatexName: "FHC_numubar_x_numubar"
    mtuplefile: "numubar_x_numubar"
    splinefile: "numubar_x_numubar"
    nutype: -14
    oscnutype: -14
  - Name: "FHC_nuebar_x_nuebar"
    LatexName: "FHC_nuebar_x_nuebar"
    mtuplefile: "nuebar_x_nuebar"
    splinefile: "nuebar_x_nuebar"
    nutype: -12
    oscnutype: -12
