General:
  Minuit2:
    NSteps: 3000
    ToleranceLevel: 5e-6

  OutputFile: "test.root"

  DUNESamples:
    - "/scratch/abipeake/MaCh3DUNE_LukesVersion/MaCh3_DUNE/Configs/BeamOffAxis/Samples/Offaxis_1d.yaml"
    #- "/scratch/abipeake/MaCh3DUNE_LukesVersion/MaCh3_DUNE/Configs/BeamOffAxis/Samples/2Dbinning_offaxis.yaml"
    #- "/scratch/abipeake/MaCh3DUNE_LukesVersion/MaCh3_DUNE/Configs/BeamOffAxis/Samples/2Dbinning_testing.yaml"
    #- "/scratch/abipeake/MaCh3DUNE_LukesVersion/MaCh3_DUNE/Configs/BeamOffAxis/Samples/2Dbinning_testing.yaml"
    #- "/scratch/abipeake/MaCh3DUNE_LukesVersion/MaCh3_DUNE/Configs/BeamOffAxis/Samples/1DEnurec.yaml"
    #- "/scratch/abipeake/MaCh3DUNE_LukesVersion/MaCh3_DUNE/Configs/BeamOffAxis/Samples/Onaxis_1Dsmaller_systematics.yaml"
    #- "/scratch/abipeake/MaCh3DUNE_LukesVersion/MaCh3_DUNE/Configs/BeamOffAxis/Samples/Onaxis_1Dsmaller.yaml"
    #- "/scratch/abipeake/MaCh3DUNE_LukesVersion/MaCh3_DUNE/Configs/BeamOffAxis/Samples/2Dbinning_testing.yaml"
   # - "/scratch/abipeake/MaCh3DUNE_LukesVersion/MaCh3_DUNE/Configs/BeamOffAxis/Samples/Onaxis_1D.yaml"
   #- /scratch/abipeake/MaCh3DUNE_LukesVersion/MaCh3_DUNE/Configs/BeamOffAxis/Samples/CAFv7_onaxisonly.yaml

  OscillationParameters: []

  Systematics:
    XsecCovFile:
     # - "/scratch/abipeake/MaCh3DUNE_LukesVersion/MaCh3_DUNE/Configs/BeamOffAxis/Enu_Enubiasxsec_april2026.yaml"
      #- Configs/BeamOffAxis/NDDetSysts.yml
      #- Configs/BeamOffAxis/FluxSysts.yml
      #- Configs/BeamOffAxis/XSecSysts.yml
      - "/scratch/abipeake/MaCh3DUNE_LukesVersion/MaCh3_DUNE/Configs/BeamOffAxis/FakeDataSysts.yml"
      - "/scratch/abipeake/MaCh3DUNE_LukesVersion/MaCh3_DUNE/Configs/BeamOffAxis/Enu_Enubias_templateparams.yaml"


    XsecCovName: "xsec_cov"

    XsecStepScale: 0.5

    XsecAtGen: false
    xsec_var1: "TrueNeutrinoEnergy"
    xsec_var2: "EnuBias"
    Parameter_fixing_threshold: 1e-50

  Fitter:
    FitTestLikelihood: false


  MCMC:
    NSteps: 8000
    AutoSave: 20000
    BurnInSteps: 0

  ProcessMCMC: No
  Seed: 0
  Debug: Yes

LLHScan:
  ParPoints: 50

AdaptionOptions:
  Settings:
    StartThrow: 5000000
    StartUpdate: 3000000
    UpdateStep: 100000
    EndUpdate: 20000000
    SaveNIterations: 1
    OutputFileName: "/scratch/abipeake/March2026/EasterSunday_coarseobservablebinning_robbinsmonroe/EasterSunday_coarseobservablebinning_robbinsmonroe_adaptive_chain_0_job_0.root"
    UseRobbinsMonro: True # Do we use this along with adaption 
    TargetAcceptance: 0.234 # Target acceptance rate
    TotalRobbinsMonroRestarts: 2 # How many times do we restart the Robbins Monro count
    AcceptanceRateBatchSize: 20000 # How often do we restart the Robbins Monro count


  Covariance:
    xsec_cov:
      DoAdaption: True
      UseExternalMatrix: False
      PrincipalComponentThreshold: 0.995
