#########################################
Title: "DUNE Interaction modes"

GeneratorName: "GENIE"

MaCh3Modes: [
  "QE",
  "SingleKaon",
  ]

QE:
  Name: "QE"
  GeneratorMaping: [1]
  IsNC: false
  PlotColor: 1
  # 1 = QE

SingleKaon:
  Name: "SingleKaon"
  
