# ---
# ThrowMatrixOverride:
#   file: "/scratch/abipeake/MaCh3_DUNE_Nov2025/MaCh3_DUNE/CovMatrix_13thJan2026_alltemplateparameters.root"
#   mat_name: "xsec_cov"
#   check_names: false
Systematics:
  - Systematic:
      SampleNames: ["*"]
      Error: 1.0
      FlatPrior: false
      FixParam: true
      Names:
        FancyName: NuWroFakeDataWeight
        ParameterName: NuWroFakeDataWeight
      ParameterBounds:
      - 0.0
      - 1.0
      ParameterGroup: FakeData
      ParameterValues:
        Generated: 0.0
        PreFitValue: 0.0
      StepScale:
        MCMC: 0.05
      Type: Functional
