---

Systematics:

# V2 initial commit
# WARNING !!!
# osc covariance require particular order of osc parameters, do not change order of dials here
- Systematic:
    Names:
      FancyName: sin2th_12
      ParameterName: sin2th_12


    SampleNames: ["FD_*", "ATM"]
    Error: 0.013
    FlatPrior: false
    ParameterBounds: [0, 1]
    ParameterGroup: Osc
    ParameterValues:
      Generated: 0.310
      PreFitValue: 0.310
    StepScale:
      MCMC: 0.2
    Type: Osc


- Systematic:
    Names:
      FancyName: sin2th_23
      ParameterName: sin2th_23


    SampleNames: ["FD_*", "ATM"]
    Error: 0.021
    FlatPrior: true
    ParameterBounds: [0, 1]
    ParameterGroup: Osc
    ParameterValues:
      Generated: 0.580
      PreFitValue: 0.580
    StepScale:
      MCMC: 0.4
    Type: Osc


- Systematic:
    Names:
      FancyName: sin2th_13
      ParameterName: sin2th_13


    SampleNames: ["FD_*", "ATM"]
    Error: 0.00065
    FlatPrior: true
    ParameterBounds: [0, 1]
    ParameterGroup: Osc
    ParameterValues:
      Generated: 0.0224
      PreFitValue: 0.0224
    StepScale:
      MCMC: 0.5
    Type: Osc


- Systematic:
    Names:
      FancyName: delm2_12
      ParameterName: delm2_12


    SampleNames: ["FD_*", "ATM"]
    Error: 0.0000018
    FlatPrior: false
    ParameterBounds: [-999, 999]
    ParameterGroup: Osc
    ParameterValues:
      Generated: 0.0000739
      PreFitValue: 0.0000739
    StepScale:
      MCMC: 0.2
    Type: Osc


- Systematic:
    Names:
      FancyName: delm2_23
      ParameterName: delm2_23


    SampleNames: ["FD_*", "ATM"]
    Error: 0.000034
    FlatPrior: true
    ParameterBounds: [-999, 999]
    ParameterGroup: Osc
    ParameterValues:
      Generated: 0.002536
      PreFitValue: 0.002536
    StepScale:
      MCMC: 0.1
    Type: Osc


- Systematic:
    Names:
      FancyName: delta_cp
      ParameterName: delta_cp


    SampleNames: ["FD_*", "ATM"]
    Error: 0.35
    FlatPrior: true
    # It has special treatment as it is continuous param
    ParameterBounds: [-999, 999]
    ParameterGroup: Osc
    ParameterValues:
      Generated: -2.498
      PreFitValue: -2.498
    StepScale:
      MCMC: 0.1
    Type: Osc


- Systematic:
    Names:
      FancyName: baseline
      ParameterName: baseline


    SampleNames: ["FD_*", "ATM"]
    Error: 0.01
    FlatPrior: true
    ParameterBounds: [0, 9999]
    ParameterGroup: Osc
    ParameterValues:
      Generated: 1284.9
      PreFitValue: 1284.9
    StepScale:
      MCMC: 1.0
    Type: Osc


- Systematic:
    Names:
      FancyName: density
      ParameterName: density


    SampleNames: ["FD_*", "ATM"]
    Error: 0.01
    FlatPrior: true
    ParameterBounds: [0, 999]
    ParameterGroup: Osc
    ParameterValues:
      Generated: 2.848
      PreFitValue: 2.848
    StepScale:
      MCMC: 1.0
    Type: Osc
