Systematics:

# Original StepScale: 1.0
# scale down by 50% Jun 25 2025

#V2 initial commit
#WARNING !!!
#osc covariance require particular order of osc parameters, do not change order of dials here
- Systematic:
    Names:
      FancyName: sin2th_12
      ParameterName: sin2th_12


    # DetID: 984
    DetID: ["FD", "ATM"]
    Error: 0.0129961532770277840 # how uncertain I believe the parameter is
    FlatPrior: false
    ParameterBounds: [0, 1]
    ParameterGroup: Osc
    ParameterValues:
      Generated: 0.303
      PreFitValue: 0.303
    StepScale:
      MCMC: 0.08 # How far do I want the chain to jump per step in this paramete
    Type: Oscillation # Muyuan changed Osc to Oscillation


- Systematic:
    Names:
      FancyName: sin2th_23
      ParameterName: sin2th_23


    # DetID: 984
    DetID: ["FD", "ATM"]
    Error: 0.021
    FlatPrior: true
    ParameterBounds: [0, 1]
    ParameterGroup: Osc
    ParameterValues:
      Generated: 0.451
      PreFitValue: 0.451
    StepScale:
      MCMC: 0.08
    Type: Oscillation


- Systematic:
    Names:
      FancyName: sin2th_13
      ParameterName: sin2th_13


    # DetID: 984
    DetID: ["FD", "ATM"]
    Error: 0.0007
    FlatPrior: false # using reactor constraint on said Ben
    ParameterBounds: [0, 1]
    ParameterGroup: Osc
    ParameterValues:
      Generated: 0.02225
      PreFitValue: 0.02225
    StepScale:
      MCMC: 0.08
    Type: Oscillation


- Systematic:
    Names:
      FancyName: delm2_12
      ParameterName: delm2_12


    # DetID: 984
    DetID: ["FD", "ATM"]
    Error: 0.0000018
    FlatPrior: false
    ParameterBounds: [-999, 999]
    ParameterGroup: Osc
    ParameterValues:
      Generated: 0.0000741
      PreFitValue: 0.0000741
    StepScale:
      MCMC: 0.08
    Type: Oscillation


- Systematic:
    Names:
      FancyName: delm2_23
      ParameterName: delm2_23


    # DetID: 984
    DetID: ["FD", "ATM"]
    Error: 0.000034
    FlatPrior: true
    ParameterBounds: [-999, 999]
    ParameterGroup: Osc
    ParameterValues:
      Generated: 0.0024599
      PreFitValue: 0.0024599
    StepScale:
      MCMC: 0.08
    Type: Oscillation


- Systematic:
    Names:
      FancyName: delta_cp
      ParameterName: delta_cp


    # DetID: 984
    DetID: ["FD", "ATM"]
    Error: 6.28331122896200340
    FlatPrior: true
    # It has special treatment as it is continuous param
    ParameterBounds: [-999, 999]
    ParameterGroup: Osc
    ParameterValues:
      Generated: -1.601
      PreFitValue: -1.601
    StepScale:
      MCMC: 0.05
    Type: Oscillation

### sterile stuff ###
# - Systematic:
#     Names:
#       FancyName: sin2th_14
#       ParameterName: sin2th_14


#     DetID: 984
#     Error: 0.0001
#     FlatPrior: true
#     # It has special treatment as it is continuous param
#     ParameterBounds: [-999, 999]
#     ParameterGroup: Osc
#     ParameterValues:
#       Generated: 0.01
#       PreFitValue: 0.01
#     StepScale:
#       MCMC: 1.0
#     Type: Osc

# - Systematic:
#     Names:
#       FancyName: sin2th_24
#       ParameterName: sin2th_24


#     DetID: 984
#     Error: 0.0001
#     FlatPrior: true
#     # It has special treatment as it is continuous param
#     ParameterBounds: [-999, 999]
#     ParameterGroup: Osc
#     ParameterValues:
#       Generated: 0.03
#       PreFitValue: 0.03
#     StepScale:
#       MCMC: 1.0
#     Type: Osc

# - Systematic:
#     Names:
#       FancyName: sin2th_34
#       ParameterName: sin2th_34


#     DetID: 984
#     Error: 0.0001
#     FlatPrior: true
#     # It has special treatment as it is continuous param
#     ParameterBounds: [-999, 999]
#     ParameterGroup: Osc
#     ParameterValues:
#       Generated: 0.05
#       PreFitValue: 0.05
#     StepScale:
#       MCMC: 1.0
#     Type: Osc

# - Systematic:
#     Names:
#       FancyName: delm2_14
#       ParameterName: delm2_14


#     DetID: 984
#     Error: 0.0001
#     FlatPrior: true
#     # It has special treatment as it is continuous param
#     ParameterBounds: [-999, 999]
#     ParameterGroup: Osc
#     ParameterValues:
#       Generated: 0.1
#       PreFitValue: 0.1
#     StepScale:
#       MCMC: 1.0
#     Type: Osc

# - Systematic:
#     Names:
#       FancyName: delta_14
#       ParameterName: delta_14


#     DetID: 984
#     Error: 0.0001
#     FlatPrior: true
#     # It has special treatment as it is continuous param
#     ParameterBounds: [-999, 999]
#     ParameterGroup: Osc
#     ParameterValues:
#       Generated: 0.
#       PreFitValue: 0.
#     StepScale:
#       MCMC: 1.0
#     Type: Osc

# - Systematic:
#     Names:
#       FancyName: delta_24
#       ParameterName: delta_24


#     DetID: 984
#     Error: 0.0001
#     FlatPrior: true
#     # It has special treatment as it is continuous param
#     ParameterBounds: [-999, 999]
#     ParameterGroup: Osc
#     ParameterValues:
#       Generated: 0.
#       PreFitValue: 0.
#     StepScale:
#       MCMC: 1.0
#     Type: Osc

### NSI stuff ###
- Systematic:
   Names:
     FancyName: Eps_ee
     ParameterName: Eps_ee


  #  DetID: 984
   DetID: ["FD", "ATM"]
   # Error: 0.001
   Error: 0.1
   FlatPrior: true
   # It has special treatment as it is continuous param
   # ParameterBounds: [-999, 999]
   ParameterBounds: [-0.5, 0.5] # trying this out
   ParameterGroup: Osc
   ParameterValues:
     Generated: 0.02 # set to close to asimov point
     PreFitValue: 0.02
   StepScale:
     #MCMC: 1.0
     #  MCMC: 0.5 # StepScale ≈ (stddev / 2) / Error 3% acceptance rate
     MCMC: 0.5
   Type: Oscillation

- Systematic:
   Names:
     FancyName: Eps_emu
     ParameterName: Eps_emu


  #  DetID: 984
   DetID: ["FD", "ATM"]
   # Error: 0.001
   Error: 0.02
   FlatPrior: true
   # It has special treatment as it is continuous param
   # ParameterBounds: [-999, 999]
   ParameterBounds: [-0.5, 0.5] # trying this out
   ParameterGroup: Osc
   ParameterValues:
     Generated: 0.02
     PreFitValue: 0.02
   StepScale:
     #MCMC: 1.0
     # MCMC: 0.1
     MCMC: 0.5
   Type: Oscillation

- Systematic:
   Names:
     FancyName: Eps_etau
     ParameterName: Eps_etau


  #  DetID: 984
   DetID: ["FD", "ATM"]
   #  Error: 0.001
   Error: 0.02
   FlatPrior: true
   # It has special treatment as it is continuous param
   #  ParameterBounds: [-999, 999]
   ParameterBounds: [-0.5, 0.5] # trying this out
   ParameterGroup: Osc
   ParameterValues:
     Generated: 0.1
     PreFitValue: 0.1
   StepScale:
     #MCMC: 1.0
     # MCMC: 0.1
     MCMC: 0.5
   Type: Oscillation

- Systematic:
   Names:
     FancyName: Eps_mumu
     ParameterName: Eps_mumu


  #  DetID: 984
   DetID: ["FD", "ATM"]
   #  Error: 0.001
   Error: 0.02
   FlatPrior: true
   # It has special treatment as it is continuous param
   #  ParameterBounds: [-999, 999]
   ParameterBounds: [-0.5, 0.5] # trying this out
   ParameterGroup: Osc
   ParameterValues:
     Generated: 0.03
     PreFitValue: 0.03
   StepScale:
     #MCMC: 1.0
     #MCMC: 0.1
    MCMC: 0.5
   Type: Oscillation

- Systematic:
   Names:
     FancyName: Eps_mutau
     ParameterName: Eps_mutau


  #  DetID: 984
   DetID: ["FD", "ATM"]
   Error: 0.1 # global best fit
   #  Error: 0.1
   FlatPrior: true
   # It has special treatment as it is continuous param
   #  ParameterBounds: [-999, 999]
   # ParameterBounds: [-0.5, 0.5] # trying this out
   ParameterBounds: [-0.05, 0.05] # global best fit
   ParameterGroup: Osc
   ParameterValues:
     Generated: 0.05
     #PreFitValue: 0.15
     PreFitValue: 0.0 # global best fit
   StepScale:
     #MCMC: 1.0
     #MCMC: 0.1
     MCMC: 0.5
   Type: Oscillation

- Systematic:
   Names:
     FancyName: Eps_tautau
     ParameterName: Eps_tautau


  #  DetID: 984
   DetID: ["FD", "ATM"]
   #  Error: 0.001
   Error: 0.02
   FlatPrior: true
   # It has special treatment as it is continuous param
   # ParameterBounds: [-999, 999]
   ParameterBounds: [-0.5, 0.5] # trying this out
   ParameterGroup: Osc
   ParameterValues:
     Generated: 0.02
     PreFitValue: 0.02
   StepScale:
     #MCMC: 1.0
     #MCMC: 0.1
     MCMC: 0.5
   Type: Oscillation

- Systematic:
   Names:
     FancyName: Delta_emu
     ParameterName: Delta_emu


  #  DetID: 984
   DetID: ["FD", "ATM"]
   Error: 1.0 
   #Error: 0.0 # fixing this parameter
   FlatPrior: true
   # It has special treatment as it is continuous param
   # ParameterBounds: [-999, 999]
   #  ParameterBounds: [-0.5, 0.5] # trying this out
   ParameterBounds: [-3.1416, 3.1416]
   ParameterGroup: Osc
   ParameterValues:
     Generated: 0.02
     PreFitValue: 0.02
   StepScale:
     # MCMC: 1.0
     #MCMC: 1.61 # muyuan trying this out, this one is AccProb: 0.1%
     #MCMC: 0.25
     # MCMC: 0.8
     MCMC: 0.5
   Type: Oscillation

- Systematic:
   Names:
     FancyName: Delta_etau
     ParameterName: Delta_etau


  #  DetID: 984
   DetID: ["FD", "ATM"]
   Error: 1.0
   #Error: 0.0 # fixing this parameter
   FlatPrior: true
   # It has special treatment as it is continuous param
   # ParameterBounds: [-999, 999]
   ParameterBounds: [-3.1415926, 3.1415926]
   ParameterGroup: Osc
   ParameterValues:
     Generated: 0.02
     PreFitValue: 0.02
   StepScale:
     # MCMC: 1.0
     # MCMC: 0.25 # muyuan trying this out
     # MCMC: 0.8
     MCMC: 0.5
   Type: Oscillation

- Systematic:
   Names:
     FancyName: Delta_mutau
     ParameterName: Delta_mutau # [-0.0041, 0.0031] based on https://arxiv.org/pdf/2201.03566


  #  DetID: 984
   DetID: ["FD", "ATM"]
   Error: 1.0
   #Error: 0.0 # fixing this parameter
   # Error: 6.28331122896200340
   FlatPrior: true
   # It has special treatment as it is continuous param
   # ParameterBounds: [-999, 999]
   ParameterBounds: [-3.1415926, 3.1415926]
   ParameterGroup: Osc
   ParameterValues:
     Generated: 0.
     PreFitValue: 0.
   StepScale:
     # MCMC: 1.0
     #MCMC: 0.25 # muyuan trying this out
     # MCMC: 0.8
     MCMC: 0.5  
   Type: Oscillation

- Systematic:
   Names:
     FancyName: ElecCoup
     ParameterName: ElecCoup


  #  DetID: 984
   DetID: ["FD", "ATM"]
   Error: 0.02 # fixing this parameter
   FlatPrior: true
   # It has special treatment as it is continuous param
   # ParameterBounds: [-999, 999]
   ParameterBounds: [-1, 1] 
   ParameterGroup: Osc
   ParameterValues:
     Generated: 0.02
     PreFitValue: 0.02
   StepScale:
     #MCMC: 1.0
     #MCMC: 0.5
     MCMC: 0.03
   Type: Oscillation

- Systematic:
   Names:
     FancyName: UpCoup
     ParameterName: UpCoup


  #  DetID: 984
   DetID: ["FD", "ATM"]
   Error: 0.02 # fixing this parameter
   FlatPrior: true
   # It has special treatment as it is continuous param
   ParameterBounds: [-1, 1]
   ParameterGroup: Osc
   ParameterValues:
     Generated: 0.02
     PreFitValue: 0.02
   StepScale:
     MCMC: 0.03
   Type: Oscillation

- Systematic:
   Names:
     FancyName: DownCoup
     ParameterName: DownCoup


  #  DetID: 984
   DetID: ["FD", "ATM"]
   Error: 0.02
   FlatPrior: true
   # It has special treatment as it is continuous param
   ParameterBounds: [-1, 1]
   ParameterGroup: Osc
   ParameterValues:
     Generated: 0.02
     PreFitValue: 0.02
   StepScale:
     MCMC: 0.03
   Type: Oscillation

- Systematic:
    Names:
      FancyName: ProdH
      ParameterName: ProdH


    DetID: ["FD", "ATM"]
    Error: 1.0
    FlatPrior: true
    ParameterBounds: [0, 999]
    ParameterGroup: Osc
    ParameterValues:
      Generated: 25
      PreFitValue: 25
    StepScale:
      MCMC: 1.0
    Type: Oscillation
