Systematics:

- Systematic:
    Names:
      FancyName: Abs_TrueEBin_Under
      ParameterName: Abs_TrueEBin_Under
    
    SampleNames: ["absorption"]
    Error: 0.1 # Need to figure out how to set poisson errors on the normalisation parameters (do we need manual input or can these be calculated by the fitter engine?)
    FlatPrior: true
    ParameterBounds: [0, 999]
    ParameterGroup: Fit
    KinematicCuts:
      - TrueEInt: [0., 1.5]
      - RecoEndZ: [0, 220]
    ParameterValues:
      Generator: 1.
      PreFitValue: 1.
    Type: Norm
    StepScale:
      MCMC: 1.

- Systematic:
    Names:
      FancyName: Abs_TrueEBin_0
      ParameterName: Abs_TrueEBin_0
    
    SampleNames: ["absorption"]
    Error: 0.1
    FlatPrior: true
    ParameterBounds: [0, 999]
    ParameterGroup: Fit
    KinematicCuts:
      - TrueEInt: [1.5, 1.7]
      - RecoEndZ: [0, 220]
    ParameterValues:
      Generator: 1.
      PreFitValue: 1.
    Type: Norm
    StepScale:
      MCMC: 1.

- Systematic:
    Names:
      FancyName: Abs_TrueEBin_1
      ParameterName: Abs_TrueEBin_1
    
    SampleNames: ["absorption"]
    Error: 0.1
    FlatPrior: true
    ParameterBounds: [0, 999]
    ParameterGroup: Fit
    KinematicCuts:
      - TrueEInt: [1.7, 1.9]
      - RecoEndZ: [0, 220]
    ParameterValues:
      Generator: 1.
      PreFitValue: 1.
    Type: Norm
    StepScale:
      MCMC: 1.

- Systematic:
    Names:
      FancyName: Abs_TrueEBin_2
      ParameterName: Abs_TrueEBin_2
    
    SampleNames: ["absorption"]
    Error: 0.1
    FlatPrior: true
    ParameterBounds: [0, 999]
    ParameterGroup: Fit
    KinematicCuts:
      - TrueEInt: [1.9, 2.1]
      - RecoEndZ: [0, 220]
    ParameterValues:
      Generator: 1.
      PreFitValue: 1.
    Type: Norm
    StepScale:
      MCMC: 1.

- Systematic:
    Names:
      FancyName: Abs_TrueEBin_Over
      ParameterName: Abs_TrueEBin_Over
    
    SampleNames: ["absorption"]
    Error: 0.1
    FlatPrior: true
    ParameterBounds: [0, 999]
    ParameterGroup: Fit
    KinematicCuts:
      - TrueEInt: [2.1, 999.]
      - RecoEndZ: [0, 220]
    ParameterValues:
      Generator: 1.
      PreFitValue: 1.
    Type: Norm
    StepScale:
      MCMC: 1.

- Systematic:
    Names:
      FancyName: Abs_Escaping
      ParameterName: Abs_Escaping
    
    SampleNames: ["absorption"]
    Error: 0.1
    FlatPrior: true
    ParameterBounds: [0, 999]
    ParameterGroup: Fit
    KinematicCuts:
      - RecoEndZ: [220, 999]
    ParameterValues:
      Generator: 1.
      PreFitValue: 1.
    Type: Norm
    StepScale:
      MCMC: 1.

- Systematic:
    Names:
      FancyName: CEx_TrueEBin_Under
      ParameterName: CEx_TrueEBin_Under
    
    SampleNames: ["charge_exchange"]
    Error: 0.1
    FlatPrior: true
    ParameterBounds: [0, 999]
    ParameterGroup: Fit
    KinematicCuts:
      - TrueEInt: [0., 1.5]
      - RecoEndZ: [0, 220]
    ParameterValues:
      Generator: 1.
      PreFitValue: 1.
    Type: Norm
    StepScale:
      MCMC: 1.

- Systematic:
    Names:
      FancyName: CEx_TrueEBin_0
      ParameterName: CEx_TrueEBin_0
    
    SampleNames: ["charge_exchange"]
    Error: 0.1
    FlatPrior: true
    ParameterBounds: [0, 999]
    ParameterGroup: Fit
    KinematicCuts:
      - TrueEInt: [1.5, 1.7]
      - RecoEndZ: [0, 220]
    ParameterValues:
      Generator: 1.
      PreFitValue: 1.
    Type: Norm
    StepScale:
      MCMC: 1.

- Systematic:
    Names:
      FancyName: CEx_TrueEBin_1
      ParameterName: CEx_TrueEBin_1
    
    SampleNames: ["charge_exchange"]
    Error: 0.1
    FlatPrior: true
    ParameterBounds: [0, 999]
    ParameterGroup: Fit
    KinematicCuts:
      - TrueEInt: [1.7, 1.9]
      - RecoEndZ: [0, 220]
    ParameterValues:
      Generator: 1.
      PreFitValue: 1.
    Type: Norm
    StepScale:
      MCMC: 1.

- Systematic:
    Names:
      FancyName: CEx_TrueEBin_2
      ParameterName: CEx_TrueEBin_2
    
    SampleNames: ["charge_exchange"]
    Error: 0.1
    FlatPrior: true
    ParameterBounds: [0, 999]
    ParameterGroup: Fit
    KinematicCuts:
      - TrueEInt: [1.9, 2.1]
      - RecoEndZ: [0, 220]
    ParameterValues:
      Generator: 1.
      PreFitValue: 1.
    Type: Norm
    StepScale:
      MCMC: 1.

- Systematic:
    Names:
      FancyName: CEx_TrueEBin_Over
      ParameterName: CEx_TrueEBin_Over
    
    SampleNames: ["charge_exchange"]
    Error: 0.1
    FlatPrior: true
    ParameterBounds: [0, 999]
    ParameterGroup: Fit
    KinematicCuts:
      - TrueEInt: [2.1, 999.]
      - RecoEndZ: [0, 220]
    ParameterValues:
      Generator: 1.
      PreFitValue: 1.
    Type: Norm
    StepScale:
      MCMC: 1.

- Systematic:
    Names:
      FancyName: CEx_Escaping
      ParameterName: CEx_Escaping
    
    SampleNames: ["charge_exchange"]
    Error: 0.1
    FlatPrior: true
    ParameterBounds: [0, 999]
    ParameterGroup: Fit
    KinematicCuts:
      - RecoEndZ: [220, 999]
    ParameterValues:
      Generator: 1.
      PreFitValue: 1.
    Type: Norm
    StepScale:
      MCMC: 1.

- Systematic:
    Names:
      FancyName: Pion_TrueEBin_Under
      ParameterName: Pion_TrueEBin_Under
    
    SampleNames: ["pion_production", "single_pion_production"]
    Error: 0.1
    FlatPrior: true
    ParameterBounds: [0, 999]
    ParameterGroup: Fit
    KinematicCuts:
      - TrueEInt: [0., 1.5]
      - RecoEndZ: [0, 220]
    ParameterValues:
      Generator: 1.
      PreFitValue: 1.
    Type: Norm
    StepScale:
      MCMC: 1.

- Systematic:
    Names:
      FancyName: Pion_TrueEBin_0
      ParameterName: Pion_TrueEBin_0
    
    SampleNames: ["pion_production", "single_pion_production"]
    Error: 0.1
    FlatPrior: true
    ParameterBounds: [0, 999]
    ParameterGroup: Fit
    KinematicCuts:
      - TrueEInt: [1.5, 1.7]
      - RecoEndZ: [0, 220]
    ParameterValues:
      Generator: 1.
      PreFitValue: 1.
    Type: Norm
    StepScale:
      MCMC: 1.

- Systematic:
    Names:
      FancyName: Pion_TrueEBin_1
      ParameterName: Pion_TrueEBin_1
    
    SampleNames: ["pion_production", "single_pion_production"]
    Error: 0.1
    FlatPrior: true
    ParameterBounds: [0, 999]
    ParameterGroup: Fit
    KinematicCuts:
      - TrueEInt: [1.7, 1.9]
      - RecoEndZ: [0, 220]
    ParameterValues:
      Generator: 1.
      PreFitValue: 1.
    Type: Norm
    StepScale:
      MCMC: 1.

- Systematic:
    Names:
      FancyName: Pion_TrueEBin_2
      ParameterName: Pion_TrueEBin_2
    
    SampleNames: ["pion_production", "single_pion_production"]
    Error: 0.1
    FlatPrior: true
    ParameterBounds: [0, 999]
    ParameterGroup: Fit
    KinematicCuts:
      - TrueEInt: [1.9, 2.1]
      - RecoEndZ: [0, 220]
    ParameterValues:
      Generator: 1.
      PreFitValue: 1.
    Type: Norm
    StepScale:
      MCMC: 1.

- Systematic:
    Names:
      FancyName: Pion_TrueEBin_Over
      ParameterName: Pion_TrueEBin_Over
    
    SampleNames: ["pion_production", "single_pion_production"]
    Error: 0.1
    FlatPrior: true
    ParameterBounds: [0, 999]
    ParameterGroup: Fit
    KinematicCuts:
      - TrueEInt: [2.1, 999.]
      - RecoEndZ: [0, 220]
    ParameterValues:
      Generator: 1.
      PreFitValue: 1.
    Type: Norm
    StepScale:
      MCMC: 1.

- Systematic:
    Names:
      FancyName: Pion_Escaping
      ParameterName: Pion_Escaping
    
    SampleNames: ["pion_production", "single_pion_production"]
    Error: 0.1
    FlatPrior: true
    ParameterBounds: [0, 999]
    ParameterGroup: Fit
    KinematicCuts:
      - RecoEndZ: [220, 999]
    ParameterValues:
      Generator: 1.
      PreFitValue: 1.
    Type: Norm
    StepScale:
      MCMC: 1.

- Systematic:
    Names:
      FancyName: Impure_TrueEBin_Under
      ParameterName: Impure_TrueEBin_Under
    
    SampleNames: ["IMPURITY"]
    Error: 0.1
    FlatPrior: true
    ParameterBounds: [0, 999]
    ParameterGroup: Fit
    KinematicCuts:
      - TrueEInt: [0., 1.5]
      - RecoEndZ: [0, 220]
    ParameterValues:
      Generator: 1.
      PreFitValue: 1.
    Type: Norm
    StepScale:
      MCMC: 1.

- Systematic:
    Names:
      FancyName: Impure_TrueEBin_0
      ParameterName: Impure_TrueEBin_0
    
    SampleNames: ["IMPURITY"]
    Error: 0.1
    FlatPrior: true
    ParameterBounds: [0, 999]
    ParameterGroup: Fit
    KinematicCuts:
      - TrueEInt: [1.5, 1.7]
      - RecoEndZ: [0, 220]
    ParameterValues:
      Generator: 1.
      PreFitValue: 1.
    Type: Norm
    StepScale:
      MCMC: 1.

- Systematic:
    Names:
      FancyName: Impure_TrueEBin_1
      ParameterName: Impure_TrueEBin_1
    
    SampleNames: ["IMPURITY"]
    Error: 0.1
    FlatPrior: true
    ParameterBounds: [0, 999]
    ParameterGroup: Fit
    KinematicCuts:
      - TrueEInt: [1.7, 1.9]
      - RecoEndZ: [0, 220]
    ParameterValues:
      Generator: 1.
      PreFitValue: 1.
    Type: Norm
    StepScale:
      MCMC: 1.

- Systematic:
    Names:
      FancyName: Impure_TrueEBin_2
      ParameterName: Impure_TrueEBin_2
    
    SampleNames: ["IMPURITY"]
    Error: 0.1
    FlatPrior: true
    ParameterBounds: [0, 999]
    ParameterGroup: Fit
    KinematicCuts:
      - TrueEInt: [1.9, 2.1]
      - RecoEndZ: [0, 220]
    ParameterValues:
      Generator: 1.
      PreFitValue: 1.
    Type: Norm
    StepScale:
      MCMC: 1.

- Systematic:
    Names:
      FancyName: Impure_TrueEBin_Over
      ParameterName: Impure_TrueEBin_Over
    
    SampleNames: ["IMPURITY"]
    Error: 0.1
    FlatPrior: true
    ParameterBounds: [0, 999]
    ParameterGroup: Fit
    KinematicCuts:
      - TrueEInt: [2.1, 999.]
      - RecoEndZ: [0, 220]
    ParameterValues:
      Generator: 1.
      PreFitValue: 1.
    Type: Norm
    StepScale:
      MCMC: 1.

- Systematic:
    Names:
      FancyName: Impure_Escaping
      ParameterName: Impure_Escaping
    
    SampleNames: ["IMPURITY"]
    Error: 0.1
    FlatPrior: true
    ParameterBounds: [0, 999]
    ParameterGroup: Fit
    KinematicCuts:
      - RecoEndZ: [220, 999]
    ParameterValues:
      Generator: 1.
      PreFitValue: 1.
    Type: Norm
    StepScale:
      MCMC: 1.
