Systematics:

- Systematic:
    Names:
      FancyName: Abs_TrueEBin_Under
      ParameterName: Abs_TrueEBin_Under

    SampleNames: ["PDSP"]
    Mode: [0]
    Error: 0.1
    FlatPrior: true
    ParameterBounds: [0, 2]
    ParameterGroup: Fit
    KinematicCuts:
      - TrueKEInt: [0., 1500]
      - RecoEndZ: [0, 220]
    ParameterValues:
      Generator: 1.
      PreFitValue: 1.
    Type: Norm
    StepScale:
      MCMC: 0.01

- Systematic:
    Names:
      FancyName: Abs_TrueEBin_0
      ParameterName: Abs_TrueEBin_0

    SampleNames: ["PDSP"]
    Mode: [0]
    Error: 0.1
    FlatPrior: true
    ParameterBounds: [0, 2]
    ParameterGroup: Fit
    KinematicCuts:
      - TrueKEInt: [1500, 1700]
      - RecoEndZ: [0, 220]
    ParameterValues:
      Generator: 1.
      PreFitValue: 1.
    Type: Norm
    StepScale:
      MCMC: 0.01

- Systematic:
    Names:
      FancyName: Abs_TrueEBin_1
      ParameterName: Abs_TrueEBin_1

    SampleNames: ["PDSP"]
    Mode: [0]
    Error: 0.1
    FlatPrior: true
    ParameterBounds: [0, 2]
    ParameterGroup: Fit
    KinematicCuts:
      - TrueKEInt: [1700, 1900]
      - RecoEndZ: [0, 220]
    ParameterValues:
      Generator: 1.
      PreFitValue: 1.
    Type: Norm
    StepScale:
      MCMC: 0.01

- Systematic:
    Names:
      FancyName: Abs_TrueEBin_2
      ParameterName: Abs_TrueEBin_2

    SampleNames: ["PDSP"]
    Mode: [0]
    Error: 0.1
    FlatPrior: true
    ParameterBounds: [0, 2]
    ParameterGroup: Fit
    KinematicCuts:
      - TrueKEInt: [1900, 2100]
      - RecoEndZ: [0, 220]
    ParameterValues:
      Generator: 1.
      PreFitValue: 1.
    Type: Norm
    StepScale:
      MCMC: 0.01

- Systematic:
    Names:
      FancyName: Abs_TrueEBin_Over
      ParameterName: Abs_TrueEBin_Over

    SampleNames: ["PDSP"]
    Mode: [0]
    Error: 0.1
    FlatPrior: true
    ParameterBounds: [0, 2]
    ParameterGroup: Fit
    KinematicCuts:
      - TrueKEInt: [2100, 999999]
      - RecoEndZ: [0, 220]
    ParameterValues:
      Generator: 1.
      PreFitValue: 1.
    Type: Norm
    StepScale:
      MCMC: 0.01

- Systematic:
    Names:
      FancyName: Abs_Escaping
      ParameterName: Abs_Escaping

    SampleNames: ["PDSP"]
    Mode: [0]
    Error: 0.1
    FlatPrior: true
    ParameterBounds: [0, 2]
    ParameterGroup: Fit
    KinematicCuts:
      - RecoEndZ: [220, 999]
    ParameterValues:
      Generator: 1.
      PreFitValue: 1.
    Type: Norm
    StepScale:
      MCMC: 0.01

- Systematic:
    Names:
      FancyName: CEx_TrueEBin_Under
      ParameterName: CEx_TrueEBin_Under

    SampleNames: ["PDSP"]
    Mode: [1]
    Error: 0.1
    FlatPrior: true
    ParameterBounds: [0, 2]
    ParameterGroup: Fit
    KinematicCuts:
      - TrueKEInt: [0., 1500]
      - RecoEndZ: [0, 220]
    ParameterValues:
      Generator: 1.
      PreFitValue: 1.
    Type: Norm
    StepScale:
      MCMC: 0.01

- Systematic:
    Names:
      FancyName: CEx_TrueEBin_0
      ParameterName: CEx_TrueEBin_0

    SampleNames: ["PDSP"]
    Mode: [1]
    Error: 0.1
    FlatPrior: true
    ParameterBounds: [0, 2]
    ParameterGroup: Fit
    KinematicCuts:
      - TrueKEInt: [1500, 1700]
      - RecoEndZ: [0, 220]
    ParameterValues:
      Generator: 1.
      PreFitValue: 1.
    Type: Norm
    StepScale:
      MCMC: 0.01

- Systematic:
    Names:
      FancyName: CEx_TrueEBin_1
      ParameterName: CEx_TrueEBin_1

    SampleNames: ["PDSP"]
    Mode: [1]
    Error: 0.1
    FlatPrior: true
    ParameterBounds: [0, 2]
    ParameterGroup: Fit
    KinematicCuts:
      - TrueKEInt: [1700, 1900]
      - RecoEndZ: [0, 220]
    ParameterValues:
      Generator: 1.
      PreFitValue: 1.
    Type: Norm
    StepScale:
      MCMC: 0.01

- Systematic:
    Names:
      FancyName: CEx_TrueEBin_2
      ParameterName: CEx_TrueEBin_2

    SampleNames: ["PDSP"]
    Mode: [1]
    Error: 0.1
    FlatPrior: true
    ParameterBounds: [0, 2]
    ParameterGroup: Fit
    KinematicCuts:
      - TrueKEInt: [1900, 2100]
      - RecoEndZ: [0, 220]
    ParameterValues:
      Generator: 1.
      PreFitValue: 1.
    Type: Norm
    StepScale:
      MCMC: 0.01

- Systematic:
    Names:
      FancyName: CEx_TrueEBin_Over
      ParameterName: CEx_TrueEBin_Over

    SampleNames: ["PDSP"]
    Mode: [1]
    Error: 0.1
    FlatPrior: true
    ParameterBounds: [0, 2]
    ParameterGroup: Fit
    KinematicCuts:
      - TrueKEInt: [2100, 999999]
      - RecoEndZ: [0, 220]
    ParameterValues:
      Generator: 1.
      PreFitValue: 1.
    Type: Norm
    StepScale:
      MCMC: 0.01

- Systematic:
    Names:
      FancyName: CEx_Escaping
      ParameterName: CEx_Escaping

    SampleNames: ["PDSP"]
    Mode: [1]
    Error: 0.1
    FlatPrior: true
    ParameterBounds: [0, 2]
    ParameterGroup: Fit
    KinematicCuts:
      - RecoEndZ: [220, 999]
    ParameterValues:
      Generator: 1.
      PreFitValue: 1.
    Type: Norm
    StepScale:
      MCMC: 0.01

- Systematic:
    Names:
      FancyName: Pion_TrueEBin_Under
      ParameterName: Pion_TrueEBin_Under

    SampleNames: ["PDSP"]
    Mode: [2]
    Error: 0.1
    FlatPrior: true
    ParameterBounds: [0, 2]
    ParameterGroup: Fit
    KinematicCuts:
      - TrueKEInt: [0., 1500]
      - RecoEndZ: [0, 220]
    ParameterValues:
      Generator: 1.
      PreFitValue: 1.
    Type: Norm
    StepScale:
      MCMC: 0.01

- Systematic:
    Names:
      FancyName: Pion_TrueEBin_0
      ParameterName: Pion_TrueEBin_0

    SampleNames: ["PDSP"]
    Mode: [2]
    Error: 0.1
    FlatPrior: true
    ParameterBounds: [0, 2]
    ParameterGroup: Fit
    KinematicCuts:
      - TrueKEInt: [1500, 1700]
      - RecoEndZ: [0, 220]
    ParameterValues:
      Generator: 1.
      PreFitValue: 1.
    Type: Norm
    StepScale:
      MCMC: 0.01

- Systematic:
    Names:
      FancyName: Pion_TrueEBin_1
      ParameterName: Pion_TrueEBin_1

    SampleNames: ["PDSP"]
    Mode: [2]
    Error: 0.1
    FlatPrior: true
    ParameterBounds: [0, 2]
    ParameterGroup: Fit
    KinematicCuts:
      - TrueKEInt: [1700, 1900]
      - RecoEndZ: [0, 220]
    ParameterValues:
      Generator: 1.
      PreFitValue: 1.
    Type: Norm
    StepScale:
      MCMC: 0.01

- Systematic:
    Names:
      FancyName: Pion_TrueEBin_2
      ParameterName: Pion_TrueEBin_2

    SampleNames: ["PDSP"]
    Mode: [2]
    Error: 0.1
    FlatPrior: true
    ParameterBounds: [0, 2]
    ParameterGroup: Fit
    KinematicCuts:
      - TrueKEInt: [1900, 2100]
      - RecoEndZ: [0, 220]
    ParameterValues:
      Generator: 1.
      PreFitValue: 1.
    Type: Norm
    StepScale:
      MCMC: 0.01

- Systematic:
    Names:
      FancyName: Pion_TrueEBin_Over
      ParameterName: Pion_TrueEBin_Over

    SampleNames: ["PDSP"]
    Mode: [2]
    Error: 0.1
    FlatPrior: true
    ParameterBounds: [0, 2]
    ParameterGroup: Fit
    KinematicCuts:
      - TrueKEInt: [2100, 999999]
      - RecoEndZ: [0, 220]
    ParameterValues:
      Generator: 1.
      PreFitValue: 1.
    Type: Norm
    StepScale:
      MCMC: 0.01

- Systematic:
    Names:
      FancyName: Pion_Escaping
      ParameterName: Pion_Escaping

    SampleNames: ["PDSP"]
    Mode: [2]
    Error: 0.1
    FlatPrior: true
    ParameterBounds: [0, 2]
    ParameterGroup: Fit
    KinematicCuts:
      - RecoEndZ: [220, 999]
    ParameterValues:
      Generator: 1.
      PreFitValue: 1.
    Type: Norm
    StepScale:
      MCMC: 0.01

- Systematic:
    Names:
      FancyName: Impure_TrueEBin_Under
      ParameterName: Impure_TrueEBin_Under

    SampleNames: ["IMPURITY"]
    Error: 0.1
    FlatPrior: true
    ParameterBounds: [0, 2]
    ParameterGroup: Fit
    KinematicCuts:
      - TrueKEInt: [0., 1500]
      - RecoEndZ: [0, 220]
    ParameterValues:
      Generator: 1.
      PreFitValue: 1.
    Type: Norm
    StepScale:
      MCMC: 0.01

- Systematic:
    Names:
      FancyName: Impure_TrueEBin_0
      ParameterName: Impure_TrueEBin_0

    SampleNames: ["IMPURITY"]
    Error: 0.1
    FlatPrior: true
    ParameterBounds: [0, 2]
    ParameterGroup: Fit
    KinematicCuts:
      - TrueKEInt: [1500, 1700]
      - RecoEndZ: [0, 220]
    ParameterValues:
      Generator: 1.
      PreFitValue: 1.
    Type: Norm
    StepScale:
      MCMC: 0.01

- Systematic:
    Names:
      FancyName: Impure_TrueEBin_1
      ParameterName: Impure_TrueEBin_1

    SampleNames: ["IMPURITY"]
    Error: 0.1
    FlatPrior: true
    ParameterBounds: [0, 2]
    ParameterGroup: Fit
    KinematicCuts:
      - TrueKEInt: [1700, 1900]
      - RecoEndZ: [0, 220]
    ParameterValues:
      Generator: 1.
      PreFitValue: 1.
    Type: Norm
    StepScale:
      MCMC: 0.01

- Systematic:
    Names:
      FancyName: Impure_TrueEBin_2
      ParameterName: Impure_TrueEBin_2

    SampleNames: ["IMPURITY"]
    Error: 0.1
    FlatPrior: true
    ParameterBounds: [0, 2]
    ParameterGroup: Fit
    KinematicCuts:
      - TrueKEInt: [1900, 2100]
      - RecoEndZ: [0, 220]
    ParameterValues:
      Generator: 1.
      PreFitValue: 1.
    Type: Norm
    StepScale:
      MCMC: 0.01

- Systematic:
    Names:
      FancyName: Impure_TrueEBin_Over
      ParameterName: Impure_TrueEBin_Over

    SampleNames: ["IMPURITY"]
    Error: 0.1
    FlatPrior: true
    ParameterBounds: [0, 2]
    ParameterGroup: Fit
    KinematicCuts:
      - TrueKEInt: [2100, 999999]
      - RecoEndZ: [0, 220]
    ParameterValues:
      Generator: 1.
      PreFitValue: 1.
    Type: Norm
    StepScale:
      MCMC: 0.01

- Systematic:
    Names:
      FancyName: Impure_Escaping
      ParameterName: Impure_Escaping

    SampleNames: ["IMPURITY"]
    Error: 0.1
    FlatPrior: true
    ParameterBounds: [0, 2]
    ParameterGroup: Fit
    KinematicCuts:
      - RecoEndZ: [220, 999]
    ParameterValues:
      Generator: 1.
      PreFitValue: 1.
    Type: Norm
    StepScale:
      MCMC: 0.01
