---
Systematics:
- Systematic:
    SampleNames: ["ATM"] # lists all the samples this systematic applies to
    Error: 1.0 # absolute error on the parameter, 1sigma error band
    FlatPrior: false # penalty term, for atmospheric, always true
    # KinematicCuts:
    # - TrueNeutrinoEnergy:
    #   - 0.0
    #   - 0.5 # energy range for this systematic, 0 to 0.5 GeV
    Names:
      FancyName: atmflux_0 # latex style name for plots atmflux_0 
      ParameterName: atmflux_0 # atmflux_0
    ParameterBounds: [-9999.0, 9999.0] # like a normalization term, scale the events. addative scale  # 1.0 + parameter dial value * functional response(TSpline function)
    ParameterGroup: AtmFlux
    ParameterValues: 
      Generated: 0.0
      PreFitValue: 0.0
    StepScale:
      MCMC: 0.3 # irrevant for atm flux
    Type: Functional
