# for each list specify:
# isrhc = "true for rhc or false for fhc"; #default to false
# mtupleprefix = "common part at beginning of path to mtuple files"
# mtuplesuffix = "common part at end of path to mtuple files"
# splineprefix = "common part at beginning of path to spline files"
# splinesuffix = "common part at endof path to spline files"
# up_bnd = "upper boundary on erec" #deault to 30.
# isfitqun = true for fitqun variable samples false otherwise #default to true
#Add samples to the sample list as shown below
SampleTitle: "ND_FHC_CCnumu"
SampleType: "BeamFD"
SampleName: "ND"
MaCh3ModeConfig: "configs/CovObjs/MaCh3Modes_GENIE.yaml"
POT: 3.0e+21 #9.99328e+21 #9.99328e+6 #7.24e+21
DUNESampleBools:
  isFHC: 1
  iselike: no
SelectionCuts:
  - KinematicStr: "isCC"
    Bounds: [ 0.8, 1.4 ]
  - KinematicStr: "ELepRec"
    Bounds: [ 0.000001, 10000000]
Binning:
   Axes:
    - VarStr: RecoNeutrinoEnergy
      VarBins: [0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 0.45, 0.5, 0.55, 0.6, 0.65, 0.7, 0.75, 0.8, 0.85, 0.9, 0.95, 1, 1.05, 1.1, 1.15, 1.2, 1.25, 1.3, 1.35, 1.4, 1.45, 1.5, 1.55, 1.6, 1.65, 1.7, 1.75, 1.8, 1.85, 1.9, 1.95, 2, 2.05, 2.1, 2.15, 2.2, 2.25, 2.3, 2.35, 2.4, 2.45, 2.5, 2.55, 2.6, 2.65, 2.7, 2.75, 2.8, 2.85, 2.9, 2.95, 3, 3.05, 3.1, 3.15, 3.2, 3.25, 3.3, 3.35, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9, 4, 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5, 5.5, 6]
      Title: E_{#nu}^{Rec} [GeV]
    - VarStr: ELepRec
      VarBins: [0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 0.45, 0.5, 0.55, 0.6, 0.65, 0.7, 0.75, 0.8, 0.85, 0.9, 0.95, 1, 1.05, 1.1, 1.15, 1.2, 1.25, 1.3, 1.35, 1.4, 1.45, 1.5, 1.55, 1.6, 1.65, 1.7, 1.75, 1.8, 1.85, 1.9, 1.95, 2, 2.05, 2.1, 2.15, 2.2, 2.25, 2.3, 2.35, 2.4, 2.45, 2.5, 2.55, 2.6, 2.65, 2.7, 2.75, 2.8, 2.85, 2.9, 2.95, 3, 3.05, 3.1, 3.15, 3.2, 3.25, 3.3, 3.35, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9, 4, 4.1, 4.2, 4.3, 4.4,  5, 5.5]
      Title: E_{Lep}^{Rec} [GeV]
ForceGeneric: True
DUNESampleBools:
  iselike: no
NuOsc:
  NuOscConfigFile: "configs/NuOsc/NuFASTLinear.yaml"
  EqualBinningPerOscChannel: false
InputFiles:
  mtupleprefix: "/project/rpp-nilic/abipeake/"
  mtuplesuffix: ".root"
  splineprefix: "" 
  splinesuffix: ""
SampleCuts:
  up_bnd: 100.
NSubSamples: 3
Sample_Name: ["ND"]
SubSamples:
  - Name: "CAFv7_0m_130_FHC"
    LatexName: "CAFv7_0m_130_FHC"
    mtuplefile: "CAFv7_0m_130_FHC"
    splinefile: ""
    samplevecno: 0
    nutype: 14
    oscnutype: 14
    signal: false
  - Name: "CAFv7_0m_131_FHC"
    LatexName: "CAFv7_0m_131_FHC"
    mtuplefile: "CAFv7_0m_131_FHC"
    splinefile: ""
    samplevecno: 1
    nutype: 14
    oscnutype: 14
    signal: false
  - Name: "CAFv7_0m_132_FHC"
    LatexName: "CAFv7_0m_132_FHC"
    mtuplefile: "CAFv7_0m_132_FHC"
    splinefile: ""
    samplevecno: 2
    nutype: 14
    oscnutype: 14
    signal: false