General:
  OutputFile: "/scratch/abipeake/FinalChains/Enubiasratio_Enu_erecyrecnew/Enubiasratio_Enu_erecyrecnew_chain_0_job_1.root"
  DUNESamples:
    #- "/scratch/abipeake/MaCh3_DUNE_merged/MaCh3_DUNE/configs/Samples/OA_samples_subsamples/Binningfor_Enubias_Enu/testfor_erecequals_ehadpluselep.yaml"
    #- "/scratch/abipeake/MaCh3_DUNE_merged/MaCh3_DUNE/configs/Samples/OA_samples_subsamples/Binningfor_Enubias_Enu/testfor_Ehadav1D.yaml"
    - "/scratch/abipeake/MaCh3_DUNE_merged/MaCh3_DUNE/configs/Samples/OA_samples_subsamples/Binningfor_Enubias_Enu/testforelep_1D.yaml"
    #- "/scratch/abipeake/MaCh3_DUNE_merged/MaCh3_DUNE/configs/Samples/OA_samples_subsamples/Binningfor_Enubias_Enu/CERN_Erec_Elep_binning_august.yaml"
   # - "/scratch/abipeake/MaCh3_DUNE_merged/MaCh3_DUNE/configs/Samples/OA_samples_subsamples/Binningfor_Enubias_Enu/CERN_ERecmodified_Elep.yaml"
   #- "/scratch/abipeake/MaCh3_DUNE_merged/MaCh3_DUNE/configs/Samples/OA_samples_subsamples/Binningfor_Enubias_Enu/CERN_Erec_Elep_binning_august.yaml"
  OscillationParameters: [0.0, 0.0, 0.0, 7.53e-5, 2.509e-3, -1.601, 1284.9, 2.848, 0.5] 
  OscillatorConfigName: "/scratch/abipeake/MaCh3_DUNE_merged/MaCh3_DUNE/configs/OscillatorObj.yaml"

  Systematics:
    XsecCovFile:  ["/scratch/abipeake/MaCh3_DUNE_merged/MaCh3_DUNE/configs/CovObjs/q0q3_onebin.yaml"] #["/scratch/abipeake/MaCh3_DUNE_merged/MaCh3_DUNE/configs/CovObjs/TrueNeutrinoEnergy_Enubias_relative_20thaugbinning.yaml"]
    XsecCovName: "xsec_cov"
    XsecStepScale: 1.0
    XsecAtGen: false 
    OscCovFile: ["/scratch/abipeake/MaCh3_DUNE_merged/MaCh3_DUNE/configs/CovObjs/OscCov_ND.yaml"]
    OscCovName: "osc_cov"
    xsec_var1: "TrueNeutrinoEnergy"
    xsec_var2: "isRelativeEnubias"
    Parameter_fixing_threshold: 0.00000000000000000000000000000000000000000000000000000001 

  Fitter:
    FitTestLikelihood: false
  MCMC:
    NSteps: 1500000 #50000
    AutoSave: 10000
    BurnInSteps: 100000
  Output:
    FileName: "TestEventRates_fit_10000.root"
    OUTPUTNAME: "TestLLH__fit_10000.root"

  ProcessMCMC: Yes
  Seed: 0
  Debug: Yes
  ThrowMatrixFile: "Covariance_matrices/New/adapted_elep_ercec_forenubiasenu.root"
  ThrowMatrixName: "1000_xsec_cov_throw_matrix"
AdaptionOptions:
  Settings:
    StartThrow: 0         # start throwing from chain 
    StartUpdate: 0        
    EndUpdate: 1500000
    UpdateStep: 1000
    SaveNIterations: 10000
    OutputFileName: "Covariance_matrices/New/adapted2_elep_ercec_forenubiasenu.root"
  Covariance:
    xsec_cov:
      DoAdaption: True     
      UseExternalMatrix: false
      ExternalMatrixFileName: ""
      ExternalMatrixName: ""
      ExternalMeansName: ""
