SampleHandlerName: "OffAxisND"

SampleType: "OffAxisND"

MaCh3ModeConfig: "Configs/CovObjs/MaCh3Modes_GENIE.yaml"

BinningFile: "Configs/TutorialConfigs/TutorialBinning.yaml"


InputFiles:
  #CovarianceMatrix: ["/scratch/abipeake/MaCh3DUNE_LukesVersion/MaCh3_DUNE/covmat_0m_1D/combined_cov.root", "NDCovMatrix"]

Samples: ["OffAxis0m_numuCC_numode"] #,"OffAxis1.75m_numuCC_numode"ls ,"OffAxis2m_numuCC_numode","OffAxis4m_numuCC_numode","OffAxis5.75m_numuCC_numode","OffAxis8m_numuCC_numode","OffAxis9.75m_numuCC_numode","OffAxis12m_numuCC_numode","OffAxis13.75m_numuCC_numode","OffAxis16m_numuCC_numode","OffAxis17.75m_numuCC_numode","OffAxis20m_numuCC_numode","OffAxis21.75m_numuCC_numode","OffAxis24m_numuCC_numode","OffAxis25.75m_numuCC_numode","OffAxis26.25m_numuCC_numode","OffAxis28.25m_numuCC_numode","OffAxis28.5m_numuCC_numode"]

OffAxis0m_numuCC_numode:
  SampleTitle: "OffAxis0m_numuCC_numode"

  POT: 1.1e+21
  is_numode: True

  SelectionCuts:
    - KinematicStr: "IsCC"
      Bounds: [0.5,1.5]

  Binning:
    VarStr : [ "RecoNeutrinoEnergy"]
    VarBins: [[0, 0.5, 0.6556, 0.8111, 0.9667, 1.1222, 1.2778, 1.4333, 1.5889, 1.7444, 1.9, 2.0556, 2.2111, 2.3667, 2.5222, 2.6778, 2.8333, 2.9889, 3.2, 3.4, 3.6, 3.8, 4.0, 4.5, 5.0, 6.0, 7, 8, 9, 10]]
    Uniform: True

  InputFiles:
    mtupleprefix: ""
    mtuplesuffix: ""
    splineprefix: ""
    splinesuffix: ""

  SubSamples:
  - Name: "OnAxis_numuCC_numode1"
    LatexName: "On Axis Numu CC Neutrino Mode"
    mtuplefile: "/project/rpp-nilic/abipeake/PRISM_CAFs/FHC/CAFv7_0m_13*_FHC.root"
    splinefile: "" # "/scratch/abipeake/MaCh3DUNE_LukesVersion/MaCh3_DUNE/Splines_foranalysis/OffAxis1D/OffAxis0m_numuCC_numode_splines.root"
    nutype: 14
    oscnutype: 14


