# for each list specify:
# isrhc = "true for rhc or false for fhc"; #default to false
# mtupleprefix = "common part at beginning of path to mtuple files"
# mtuplesuffix = "common part at end of path to mtuple files"
# splineprefix = "common part at beginning of path to spline files"
# splinesuffix = "common part at endof path to spline files"
# up_bnd = "upper boundary on erec" #deault to 30.
# isfitqun = true for fitqun variable samples false otherwise #default to true
#Add samples to the sample list as shown below
SampleTitle: "ND_FHC_CCnumu"
#SampleType: "Beam"
SampleName: "ND"
MaCh3ModeConfig: "Configs/CovObjs/MaCh3Modes_GENIE.yaml"
SelectionCuts:
POT: 9.99328e+16 #9.99328e+18 #9.99328e+21 #9.99328e+6 #7.24e+21
DUNESampleBools:
  isFHC: 1
  iselike: no
BinningFile: "/scratch/abipeake/MaCh3_DUNE_Nov2025/MaCh3_DUNE/Configs/TutorialConfigs/TutorialBinning.yaml"
SelectionCuts:
  - KinematicStr: "TrueXPos"
    Bounds: [ -310.0, 310.0 ]
  - KinematicStr: "TrueYPos"
    Bounds: [ -550.0, 550.0 ]
  - KinematicStr: "TrueZPos"
    Bounds: [ 50.0, 1244.0 ]
  - KinematicStr: "CVNNumu"
    Bounds: [ 0.5, 999 ]
  - KinematicStr: "isCC"
    Bounds: [ 0.8, 1.4 ]
  - KinematicStr: "RecoNeutrinoEnergy"
    Bounds: [ 0.1, 9999 ]
Binning:
   #XVarStr: RecoNeutrinoEnergy
   #XVarBins: [60, 0.0, 6.0]
   XVarStr: "TrueNeutrinoEnergy"
   XVarBins: [0., 0.25, 0.5, 0.75, 1., 1.25, 1.5, 1.75, 2., 2.25, 2.5, 2.75, 3., 3.25, 3.5, 3.75, 4., 4.25, 4.5, 4.75, 5., 5.25, 5.5, 5.75, 6., 6.25, 6.5, 6.75, 7., 7.25, 7.5, 7.75, 8., 8.25, 8.5, 8.75, 9., 9.25, 9.5, 9.75, 10., 1000.]

ForceGeneric: True
DUNESampleBools:
  iselike: no
NuOsc:
  NuOscConfigFile: "Configs/NuOsc/NuFASTLinear.yaml"
  EqualBinningPerOscChannel: false
InputFiles:
  mtupleprefix: "inputs/"
  mtuplesuffix: ".root"
  splineprefix: "" 
  splinesuffix: ""
SampleCuts:
  up_bnd: 100.
NSubSamples: 1
Sample_Name: ["ND"]
SubSamples:
  - Name: "CAFv7_0m_130_FHC"
    LatexName: "CAFv7_0m_130_FHC"
    mtuplefile: "CAFv7_0m_130_FHC"
    splinefile: ""
    samplevecno: 0
    nutype: 14
    oscnutype: 14
    signal: false