# for each list specify:
# isrhc = "true for rhc or false for fhc"; #default to false
# mtupleprefix = "common part at beginning of path to mtuple files"
# mtuplesuffix = "common part at end of path to mtuple files"
# splineprefix = "common part at beginning of path to spline files"
# splinesuffix = "common part at endof path to spline files"
# up_bnd = "upper boundary on erec" #deault to 30.
# isfitqun = true for fitqun variable samples false otherwise #default to true
#Add samples to the sample list as shown below
SampleTitle: "ND_FHC_CCnumu"
SampleType: "BeamFD"
SampleName: "ND"
MaCh3ModeConfig: "configs/CovObjs/MaCh3Modes_GENIE.yaml"
SelectionCuts:
POT: 3.0e21 #9.99328e+21 #9.99328e+6 #7.24e+21
DUNESampleBools:
  isFHC: 1
  iselike: no
SelectionCuts:
Binning:
  Axes:
     - VarStr: "q3"
       Uniform: [100, 0.0, 5.0]
       Title: "q_{3} [GeV/c]"
     - VarStr: "q0"
       Uniform: [100, 0.0, 5.0]
       Title: "q_{0} [GeV/c]"
     #- VarStr: "TrueNeutrinoEnergy"
      # VarBins: [0.0, 1.0, 2.0,  3.0, 4.0, 8.0, 20.0]
       #Title: "E_{#nu} [GeV/c]"
  ForceGeneric: True
DUNESampleBools:
  iselike: no
NuOsc:
  NuOscConfigFile: "configs/NuOsc/NuFASTLinear.yaml"
  EqualBinningPerOscChannel: false
InputFiles:
  mtupleprefix: "/project/rpp-nilic/abipeake/"
  mtuplesuffix: ".root"
  splineprefix: "" 
  splinesuffix: ""
SampleCuts:
  up_bnd: 100.
NSubSamples: 4
Sample_Name: ["ND"]
SubSamples:
  - Name: "CAFv7_0m_130_FHC"
    LatexName: "CAFv7_0m_130_FHC"
    mtuplefile: "CAFv7_0m_130_FHC"
    splinefile: ""
    samplevecno: 0
    nutype: 14
    oscnutype: 14
    signal: false
  - Name: "CAFv7_0m_131_FHC"
    LatexName: "CAFv7_0m_131_FHC"
    mtuplefile: "CAFv7_0m_131_FHC"
    splinefile: ""
    samplevecno: 1
    nutype: 14
    oscnutype: 14
    signal: false
  - Name: "CAFv7_0m_132_FHC"
    LatexName: "CAFv7_0m_132_FHC"
    mtuplefile: "CAFv7_0m_132_FHC"
    splinefile: ""
    samplevecno: 2
    nutype: 14
    oscnutype: 14
    signal: false
  - Name: "CAFv7_0m_133_FHC"
    LatexName: "CAFv7_0m_133_FHC"
    mtuplefile: "CAFv7_0m_133_FHC"
    splinefile: ""
    samplevecno: 3
    nutype: 14
    oscnutype: 14
    signal: false