# for each list specify:
# isrhc = "true for rhc or false for fhc"; #default to false
# mtupleprefix = "common part at beginning of path to mtuple files"
# mtuplesuffix = "common part at end of path to mtuple files"
# splineprefix = "common part at beginning of path to spline files"
# splinesuffix = "common part at endof path to spline files"
# up_bnd = "upper boundary on erec" #deault to 30.
# isfitqun = true for fitqun variable samples false otherwise #default to true
#Add samples to the sample list as shown below
SampleTitle: "ND_FHC_CCnumu"
SampleType: "BeamFD"
SampleName: "ND"
MaCh3ModeConfig: "configs/CovObjs/MaCh3Modes_GENIE.yaml"
SelectionCuts:
POT: 3.0e+21 #9.99328e+18 #9.99328e+21 #9.99328e+6 #7.24e+21
DUNESampleBools:
  isFHC: 1
  iselike: no
SelectionCuts:
Binning:
   Axes:
    - VarStr: pT
      VarBins: [0, 0.0333333, 0.0666667, 0.1, 0.1333333, 0.1666667, 0.2,0.225, 0.25, 0.275, 0.3, 0.325, 0.35, 0.375, 0.4,0.45, 0.5, 0.55, 0.6, 0.65, 0.7,0.875, 1.05, 1.225, 1.4, 1.575, 1.75, 1.925, 2.1, 2.275, 2.45] #[0, 0.1,0.25,0.3,0.4, 0.5,0.6,0.7,0.8,0.9,1.0, 1.2, 1.4, 1.6,1.8,2.0,4.0,10.0]
      Title: p_{T} [GeV]
    - VarStr: pz
      VarBins: [0.0, 0.1111111, 0.2222222, 0.3333333, 0.4444444, 0.5555555, 0.6666666, 0.7777777, 0.8888888, 1.0, 1.1111111, 1.2222222, 1.3333333, 1.4444444, 1.5555555, 1.6666666, 1.7777777, 1.8888888, 2.0]
#[0, 0.1666667, 0.3333334, 0.5, 0.6666667, 0.8333334, 1.0, 1.166667, 1.333333, 1.5,1.6, 1.7, 2.0]
      Title: p_{z} [GeV]
    - VarStr: RecoNeutrinoEnergy
      VarBins: [0., 0.5, 1., 1.25, 1.5, 1.75, 2., 2.25, 2.5, 2.75, 3., 3.25, 3.5, 3.75, 4., 5., 6., 10.]
      Title: E^{Reco.}_{#nu} [GeV]
ForceGeneric: True
DUNESampleBools:
  iselike: no
NuOsc:
  NuOscConfigFile: "configs/NuOsc/NuFASTLinear.yaml"
  EqualBinningPerOscChannel: false
InputFiles:
  mtupleprefix: "/project/rpp-nilic/abipeake/"
  mtuplesuffix: ".root"
  splineprefix: "" 
  splinesuffix: ""
SampleCuts:
  up_bnd: 100.
NSubSamples: 4
Sample_Name: ["ND"]
SubSamples:
  - Name: "CAFv7_0m_130_FHC"
    LatexName: "CAFv7_0m_130_FHC"
    mtuplefile: "CAFv7_0m_130_FHC"
    splinefile: ""
    samplevecno: 0
    nutype: 14
    oscnutype: 14
    signal: false
  - Name: "CAFv7_0m_131_FHC"
    LatexName: "CAFv7_0m_131_FHC"
    mtuplefile: "CAFv7_0m_131_FHC"
    splinefile: ""
    samplevecno: 1
    nutype: 14
    oscnutype: 14
    signal: false
  - Name: "CAFv7_0m_132_FHC"
    LatexName: "CAFv7_0m_132_FHC"
    mtuplefile: "CAFv7_0m_132_FHC"
    splinefile: ""
    samplevecno: 2
    nutype: 14
    oscnutype: 14
    signal: false
  - Name: "CAFv7_0m_133_FHC"
    LatexName: "CAFv7_0m_133_FHC"
    mtuplefile: "CAFv7_0m_133_FHC"
    splinefile: ""
    samplevecno: 3
    nutype: 14
    oscnutype: 14
    signal: false