General:
  OscillatorConfigName: "configs/OscillatorObj.yaml"
  POT: 1.3628319e+23
  Systematics:
    # XsecCovFile: "inputs/xsec_covariance_DUNE_systs_2022a_FD_v3.root"
    # XsecCovFile: "inputs/xsec_atm_new_tune.root"
    XsecCovFile: "configs/xsec_systs.yaml"
    XsecCovName: "xsec_cov"
    XsecStepScale: 0.1
    XsecAtGen: false 
    OscCovFile: "inputs/osc_covariance_DUNE_PDG2021_v1.root"
    OscCovName: "osc_cov"
  Output:
    FileName: "AtmChain_2.root"
  MCMC:
    AutoSave: 500
    NSteps: 50
    StartFromPos: false
    PosFileName: /dune/app/users/pgranger/MaCh3_ana/MaCh3_DUNE/AtmChain_1.root
    StatOnly: false
    ProcessMCMC: No
  Debug: Yes
  Seed: 0

  
