# for each list specify:
# isrhc = "true for rhc or false for fhc"; #default to false
# mtupleprefix = "common part at beginning of path to mtuple files"
# mtuplesuffix = "common part at end of path to mtuple files"
# splineprefix = "common part at beginning of path to spline files"
# splinesuffix = "common part at endof path to spline files"
# up_bnd = "upper boundary on erec" #deault to 30.
# isfitqun = true for fitqun variable samples false otherwise #default to true
#Add samples to the sample list as shown below
# {
# 	name = "descriptive name for sample";
# 	mtuplefile = "path to mtuple file";
# 	splinefile  = "path to splinefile"; #!!NB MUST BE COMPATIBLE WITH BINNING OPTION SPECIFIED IN EXECUTABLE
# 	samplevecno = which number in the skmcsamples array should this go in;
# 	nutype = "nutype before oscillation";
# 	oscnutype = "nutype after oscillation";
# 	signal = true for signal samples;,
# },
SampleName: "numuselec"
# SelectionCuts:
#   - KinematicStr: "TrueXPos"
#     Bounds: [ -310.0, 310.0 ]
#   - KinematicStr: "TrueYPos"
#     Bounds: [ -550.0, 550.0 ]
#   - KinematicStr: "TrueZPos"
#     Bounds: [ 50.0, 1244.0 ]
Binning:
  BinningOpt: 2
  XVarBins: [0., 0.25, 0.5, 0.75, 1.,  1.25, 1.5, 1.75, 2., 2.25, 2.5, 2.75, 3., 3.25, 3.5, 3.75, 4., 4.25, 4.5, 4.75, 5, 5.5, 6, 6.5, 7, 7.5, 8, 8.5, 9, 9.5, 10]
  YVarBins: [-1, -0.9, -0.8, -0.7, -0.6, -0.5, -0.4, -0.3, -0.2, -0.1, 0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1]

SampleBools:
  isrhc: no
  iselike: no
InputFiles:
  mtupleprefix: "inputs/ATM_CAF_files/hd_AV_"
  mtuplesuffix: "_numuselec.root"
  # splineprefix: "inputs/ATM_spline_files/FD_FHC_ger_"
  splineprefix: "inputs/ATM_spline_files_test/hd_AV_"
  # splineprefix: "inputs/DUNE_spline_files/FD_FHC_ger_"
  splinesuffix: "_numuselec_splines2.root"
SampleCuts:
  up_bnd: 30.
# DetID: 72
DetID: 24
NSubSamples: 1
SubSamples:
  - name: "numu_x_numu"
    mtuplefile: "numu_x_numu"
    splinefile: "numu_x_numu"
    samplevecno: 0
    nutype: 14
    oscnutype: 14
    signal: true

  # - name: "numubar_x_numubar"
  #   mtuplefile: "numubar_x_numubar"
  #   splinefile: "numubar_x_numubar"
  #   samplevecno: 1
  #   nutype: -14
  #   oscnutype: -14
  #   signal: true

  # - name: "nuebar_x_numubar"
  #   mtuplefile: "nuebar_x_numubar"
  #   splinefile: "nuebar_x_numubar"
  #   samplevecno: 2
  #   nutype: -12
  #   oscnutype: -14
  #   signal: true

  # # - name: "numu_x_nue"
  # #   mtuplefile: "numu_x_nue"
  # #   splinefile: "numu_x_nue"
  # #   samplevecno: 1
  # #   nutype: 14
  # #   oscnutype: 12
  # #   signal: false

  # # - name: "numu_x_nutau"
  # #   mtuplefile: "numu_x_nutau"
  # #   splinefile: "numu_x_nutau"
  # #   samplevecno: 2
  # #   nutype: 14
  # #   oscnutype: 16
  # #   signal: false

  # - name: "nue_x_numu"
  #   mtuplefile: "nue_x_numu"
  #   splinefile: "nue_x_numu"
  #   samplevecno: 3
  #   nutype: 12
  #   oscnutype: 14
  #   signal: true

  # - name: "nue_x_nue"
  #   mtuplefile: "nue_x_nue"
  #   splinefile: "nue_x_nue"
  #   samplevecno: 4
  #   nutype: 12
  #   oscnutype: 12
  #   signal: false

  # - name: "nue_x_nutau"
  #   mtuplefile: "nue_x_nutau"
  #   splinefile: "nue_x_nutau"
  #   samplevecno: 5
  #   nutype: 12
  #   oscnutype: 16
  #   signal: false
