General:
  OutputFile: "Outputs/projections_outputs/Projections_CC_BField0_5_FidRad_160_FidLen_209_InstRad_249_45_InstLen_259_WithECal_mustcontainallsecondaries_5percthershold.root"
  #OutputFile: "Outputs/projections_outputs/Projections_CC_BField0_5_FidRad_160_FidLen_209_InstRad_249_45_InstLen_259_WithECal.root"
  #OutputFile: "outputs/testing.root"
  DUNESamples: ["Configs/Samples/SamplePDFDune_NDGAr_FHC_numuselec.yaml"]	
  #Nu-FIT
  #OscillationParameters: [0.310, 0.582, 0.224, 7.39E-5, 2.5254E-3, -2.498]
  # T2K-like best-fit
  OscillationParameters: [0.307, 0.528, 0.0218, 7.53e-5, 2.509e-3, -1.601, 1284.9, 2.848]
  OscillatorConfigName: "Configs/OscillatorObj.yaml"
  Systematics:
    XsecCovFile: ["Configs/CovObjs/xsec_covariance_DUNE_systs_NDGAr.yaml"]
    XsecCovName: "xsec_cov"
    XsecStepScale: 0.1
    XsecAtGen: false 
    OscCovFile: ["Configs/CovObjs/OscCov_PDG2021_v2.yaml"]
    OscCovName: "osc_cov"
    OscFix: ["baseline"]

  Fitter:
    FitTestLikelihood: false
  MCMC:
    NSteps: 2000
    AutoSave: 10000
  Output:
    FileName: "TestEventRates.root"
    OUTPUTNAME: "TestLLH.root"
  ProcessMCMC: No
  Seed: 0
  Debug: No

GeneralKinematicCuts:
- Name: "InFDV"
  VarString: "InFDV"
  Range: [1.,2.]
- Name: "IsCC"
  VarString: "IsCC"
  Range: [1.,2.]
#- Name: "Enu"
#  VarString: "TrueNeutrinoEnergy"
#  Range: [1.,5.]
#- Name: "StoppedInTPC"
#  VarString: "Particle_IsStoppedInTPC"
#  Range: [1.,2.]
#- Name: "StoppedInECal"
#  VarString: "Particle_IsStoppedInECal"
#  Range: [1.,2.]
#- Name: "StoppedInGap"
#  VarString: "Particle_IsStoppedInGap"
#  Range: [1.,2.]
#- Name: "StoppedInEndGap"
#  VarString: "Particle_IsStoppedInEndGap"
#  Range: [1.,2.]
#- Name: "StoppedInBarrelGap"
#  VarString: "Particle_IsStoppedInBarrelGap"
#  Range: [1.,2.]
#- Name: "Escaped"
#  VarString: "Particle_IsEscaped"
#  Range: [1.,2.]

"Projections": [
  {
    "Name": "TrueNeutrinoEnergy",
    "VarStrings": ["TrueNeutrinoEnergy"],
    "VarBins": [[0.,  0.5,  1.,  1.25, 1.5, 1.75, 2., 2.25, 2.5, 2.75, 3., 3.25, 3.5, 3.75, 4., 5., 6., 10.]],
  }, 
  {
    "Name": "TrueQ3_vs_TrueQ0",
    "VarStrings": ["TrueQ3","TrueQ0"],
    "VarBins": [[175,0.,3.5],[150,0.,3.]],
  },
  {
    "Name": "Accepted_TrueQ3_vs_TrueQ0",
    "VarStrings": ["TrueQ3","TrueQ0"],
    "VarBins": [[175,0.,3.5],[150,0.,3.]],
    "KinematicCuts": [
      {
        "Range": [1.,2.],
        "Name": "IsEventAccepted",
        "VarString": "Event_IsAccepted"
      }
    ]
  },
  {
    "Name": "Lepton_Angular_Distribution",
    "VarStrings": ["LepPhi", "LepTheta"],
    "VarBins": [[90,-180.,180.],[90,0.,180.]]
  },
  {
    "Name": "Accepted_Lepton_Angular_Distribution",
    "VarStrings": ["LepPhi", "LepTheta"],
    "VarBins": [[90,-180.,180.],[90,0.,180.]],
    "KinematicCuts": [
      {
        "Range": [1.,2.],
        "Name": "IsEventAccepted",
        "VarString": "Event_IsAccepted"
      }
    ]
  },
  {
    "Name": "Particle_BAngle_Momentum",
    "VarStrings": ["Particle_BAngle","Particle_Momentum"],
    "VarBins": [[90,0.,180.],[200,0.,6.]],
  },
  {
    "Name": "Accepted_Particle_BAngle_Momentum",
    "VarStrings": ["Particle_BAngle","Particle_Momentum"],
    "VarBins": [[90,0.,180.],[200,0.,6.]],
    "KinematicCuts": [
      {
        "Range": [1.,2.],
        "Name": "IsParticleAccepted",
        "VarString": "Particle_IsAccepted"
      }
    ]
  },
  {
    "Name": "Particle_BAngle_Momentum_Protons",
    "VarStrings": ["Particle_BAngle","Particle_Momentum"],
    "VarBins": [[90,0.,180.],[200,0.,6.]],
    "KinematicCuts": [
      {
        "Range": [2211.5,2212.5],
        "Name": "PDG",
        "VarString": "Particle_PDG"
      }
    ]
  },
  {
    "Name": "Accepted_Particle_BAngle_Momentum_Protons",
    "VarStrings": ["Particle_BAngle","Particle_Momentum"],
    "VarBins": [[90,0.,180.],[200,0.,6.]],
    "KinematicCuts": [
      {
        "Range": [2211.5,2212.5],
        "Name": "PDG",
        "VarString": "Particle_PDG"
      },
      {
        "Range": [1.,2.],
        "Name": "IsParticleAccepted",
        "VarString": "Particle_IsAccepted"
      }
    ]
  },
  {
    "Name": "Particle_BAngle_Momentum_Pi+",
    "VarStrings": ["Particle_BAngle","Particle_Momentum"],
    "VarBins": [[90,0.,180.],[200,0.,6.]],
    "KinematicCuts": [
      {
        "Range": [210.5,211.5],
        "Name": "PDG",
        "VarString": "Particle_PDG"
      }
    ]
  },
  {
    "Name": "Accepted_Particle_BAngle_Momentum_Pi+",
    "VarStrings": ["Particle_BAngle","Particle_Momentum"],
    "VarBins": [[90,0.,180.],[200,0.,6.]],
    "KinematicCuts": [
      {
        "Range": [210.5,211.5],
        "Name": "PDG",
        "VarString": "Particle_PDG"
      },
      {
        "Range": [1.,2.],
        "Name": "IsParticleAccepted",
        "VarString": "Particle_IsAccepted"
      }
    ]
  },
  {
    "Name": "Particle_BAngle_Momentum_Pi-",
    "VarStrings": ["Particle_BAngle","Particle_Momentum"],
    "VarBins": [[90,0.,180.],[200,0.,6.]],
    "KinematicCuts": [
      {
        "Range": [-211.5,-210.5],
        "Name": "PDG",
        "VarString": "Particle_PDG"
      }
    ]
  },
  {
    "Name": "Accepted_Particle_BAngle_Momentum_Pi-",
    "VarStrings": ["Particle_BAngle","Particle_Momentum"],
    "VarBins": [[90,0.,180.],[200,0.,6.]],
    "KinematicCuts": [
      { 
        "Range": [-211.5,-210.5],
        "Name": "PDG",
        "VarString": "Particle_PDG"
      },
      {
        "Range": [1.,2.],
        "Name": "IsParticleAccepted",
        "VarString": "Particle_IsAccepted"
      }
    ]
  },
  {
    "Name": "Particle_BAngle_Momentum_Mu-",
    "VarStrings": ["Particle_BAngle","Particle_Momentum"],
    "VarBins": [[90,0.,180.],[200,0.,6.]],
    "KinematicCuts": [
      {
        "Range": [12.5,13.5],
        "Name": "PDG",
        "VarString": "Particle_PDG"
      }
    ]
  },
  {
    "Name": "Accepted_Particle_BAngle_Momentum_Mu-",
    "VarStrings": ["Particle_BAngle","Particle_Momentum"],
    "VarBins": [[90,0.,180.],[200,0.,6.]],
    "KinematicCuts": [
      {
        "Range": [12.5,13.5],
        "Name": "PDG",
        "VarString": "Particle_PDG"
      },
      {
        "Range": [1.,2.],
        "Name": "IsParticleAccepted",
        "VarString": "Particle_IsAccepted"
      }
    ]
  },
  {
    "Name": "Lepton_BAngle_Momentum",
    "VarStrings": ["LepBAngle","LepP"],
    "VarBins": [[90,0.,180.],[200,0.,6.]],
  },
  {
    "Name": "Accepted_Lepton_BAngle_Momentum",
    "VarStrings": ["LepBAngle","LepP"],
    "VarBins": [[90,0.,180.],[200,0.,6.]],
    "KinematicCuts": [
      {
        "Range": [1.,2.],
        "Name": "IsEventAccepted",
        "VarString": "Event_IsAccepted"
      }
    ]
  },
  {
    "Name": "Particle_TrackLengthYZ_Momentum",
    "VarStrings": ["Particle_TrackLengthYZ","Particle_Momentum"],
    "VarBins": [[100,0,500],[100,0,6]],
    "KinematicCuts": [
      {
        "Range": [1,200],
        "Name": "Momentum",
        "VarString": "Particle_Momentum",
      },
      {
        "Range": [60,120],
        "Name": "BAngle",
        "VarString": "Particle_BAngle",
      },
    ]     
  },
  {
    "Name": "Accepted_Particle_TrackLengthYZ_Momentum",
    "VarStrings": ["Particle_TrackLengthYZ","Particle_Momentum"],
    "VarBins": [[100,0,500],[100,0,6]],
    "KinematicCuts": [
      {
        "Range": [1,200],
        "Name": "Momentum",
        "VarString": "Particle_Momentum",
      },
      {
        "Range": [60,120],
        "Name": "BAngle",
        "VarString": "Particle_BAngle",
      },
      {
        "Name": "IsParticleAccepted",
        "Range": [1.,2.],
        "VarString": "Particle_IsAccepted"
      }
    ]
  },
  {
    "Name": "Particle_End_Radii",
    "VarStrings": ["Particle_EndR"],
    "VarBins": [[50,240,290]]
  },
  {
    "Name": "Accepted_Particle_End_Radii",
    "VarStrings": ["Particle_EndR"],
    "VarBins": [[50,240,290]],
    "KinematicCuts": [
      {
        "Name": "IsParticleAccepted",
        "Range": [1.,2.],
        "VarString": "Particle_IsAccepted"
      }
    ]
  },
  {
    "Name": "Particle_Momentum",
    "VarStrings": ["Particle_Momentum"],
    "VarBins": [[100,0.,6]],
  },
  {
    "Name": "Pi0_BeamAngle_Mom",
    "VarStrings": ["Particle_BeamAngle","Particle_Momentum"],
    "VarBins": [[90,0.,180.],[100,0.,5]],
    "KinematicCuts": [
      {
        "Name": "PDG",
        "VarString": "Particle_PDG",
        "Range": [110.5,111.5]
      },
    ]
  },
  {
    "Name": "Pi0_BeamAngle",
    "VarStrings": ["Particle_BeamAngle"],
    "VarBins": [[90,0.,180.]],
    "KinematicCuts": [
      {
        "Name": "PDG",
        "VarString": "Particle_PDG",
        "Range": [110.5,111.5]
      },
    ]
  },
  {
    "Name": "Pi0_Mom",
    "VarStrings": ["Particle_Momentum"],
    "VarBins": [[100,0.,5]],
    "KinematicCuts": [
      {
        "Name": "PDG",
        "VarString": "Particle_PDG",
        "Range": [110.5,111.5]
      },
    ]
  },
  {
    "Name": "eta_BeamAngle_Mom",
    "VarStrings": ["Particle_BeamAngle","Particle_Momentum"],
    "VarBins": [[90,0.,180.],[100,0.,5]],
    "KinematicCuts": [
      {
        "Name": "PDG",
        "VarString": "Particle_PDG",
        "Range": [220.5,221.5]
      },
    ]
  },
  {
    "Name": "eta_BeamAngle",
    "VarStrings": ["Particle_BeamAngle"],
    "VarBins": [[90,0.,180.]],
    "KinematicCuts": [
      {
        "Name": "PDG",
        "VarString": "Particle_PDG",
        "Range": [220.5,221.5]
      },
    ]
  },
  {
    "Name": "eta_Mom",
    "VarStrings": ["Particle_Momentum"],
    "VarBins": [[100,0.,5]],
    "KinematicCuts": [
      {
        "Name": "PDG",
        "VarString": "Particle_PDG",
        "Range": [220.5,221.5]
      },
    ]
  },
  {
    "Name": "N_Escaped_Secondary_Nuclei",
    "VarStrings": ["Particle_NEscSecNuc"],
    "VarBins": [[10,0.,10.]]
  },
  {
    "Name": "N_Escaped_Secondaries",
    "VarStrings": ["Particle_NEscSec"],
    "VarBins": [[15,0.,15.]]
  },
  {
    "Name": "TPC_Escaped_Sec_Energy",
    "VarStrings": ["Particle_EscSecEnergy"],
    "VarBins": [[100,0.001,0.2]],
    "KinematicCuts": [
      {
        "VarString": "Particle_IsStoppedInTPC",
        "Name": "TPC",
        "Range": [1.,2.]
      }
    ]
  },
  {
    "Name": "ECal_Escaped_Sec_Energy",
    "VarStrings": ["Particle_EscSecEnergy"],
    "VarBins": [[100,0.001,0.2]],
    "KinematicCuts": [
      {
        "VarString": "Particle_IsStoppedInECal",
        "Name": "ECal",
        "Range": [1.,2.]
      }
    ]
  },
  {
    "Name": "pi+_TPC_decaymom",
    "VarStrings": ["Particle_EndMomentum"],
    "VarBins":[[100,0.,2.]],
    "KinematicCuts": [
      {
        "VarString": "Particle_PDG",
        "Name": "PDG",
        "Range": [210.5,211.5]
      },
      {
        "VarString": "Particle_IsStoppedInTPC",
        "Name": "TPC",
        "Range": [1.,2.]
      },
      {
        "VarString": "Particle_IsDecayed",
        "Name": "Decayed",
        "Range": [1.,2.]
      }
    ]
  },
  {
    "Name": "pi-_TPC_decaymom",
    "VarStrings": ["Particle_EndMomentum"],
    "VarBins":[[100,0.,2.]],
    "KinematicCuts": [
      {
        "VarString": "Particle_PDG",
        "Name": "PDG",
        "Range": [-211.5,-210.5]
      },
      {
        "VarString": "Particle_IsStoppedInTPC",
        "Name": "TPC",
        "Range": [1.,2.]
      },
      {
        "VarString": "Particle_IsDecayed",
        "Name": "Decayed",
        "Range": [1.,2.]
      }
    ]
  },
  {
    "Name": "pi+_ECal_decaymom",
    "VarStrings": ["Particle_EndMomentum"],
    "VarBins":[[100,0.,2.]],
    "KinematicCuts": [
      {
        "VarString": "Particle_PDG",
        "Name": "PDG",
        "Range": [210.5,211.5]
      },
      {
        "VarString": "Particle_IsStoppedInECal",
        "Name": "ECal",
        "Range": [1.,2.]
      },
      {
        "VarString": "Particle_IsDecayed",
        "Name": "Decayed",
        "Range": [1.,2.]
      }
    ]
  },
  {
    "Name": "pi-_ECal_decaymom",
    "VarStrings": ["Particle_EndMomentum"],
    "VarBins":[[100,0.,2.]],
    "KinematicCuts": [
      {
        "VarString": "Particle_PDG",
        "Name": "PDG",
        "Range": [-211.5,-210.5]
      },
      {
        "VarString": "Particle_IsStoppedInECal",
        "Name": "ECal",
        "Range": [1.,2.]
      },
      {
        "VarString": "Particle_IsDecayed",
        "Name": "Decayed",
        "Range": [1.,2.]
      }
    ]
  },
]
