General:
  OutputFile: "outputs/NDGAr_EventRates_CC_BField0_5_FidRad_160_FidLen_209_InstrRad_249_45_InstrLen_259_WithECal_Enu_1to5.root"
  #OutputFile: "outputs/_TEST_i_anatree.root"
  DUNESamples: ["configs/Samples/SamplePDFDune_NDGAr_FHC_numuselec.yaml"]	
  #Nu-FIT
  #OscillationParameters: [0.310, 0.582, 0.224, 7.39E-5, 2.5254E-3, -2.498]
  # T2K-like best-fit
  OscillationParameters: [0.307, 0.528, 0.0218, 7.53e-5, 2.509e-3, -1.601, 1284.9, 2.848]
  OscillatorConfigName: "configs/OscillatorObj.yaml"
  Systematics:
    XsecCovFile: ["configs/CovObjs/xsec_covariance_DUNE_systs_2022a_FD_v3_new.yaml"]
    XsecCovName: "xsec_cov"
    XsecStepScale: 0.1
    XsecAtGen: false 
    OscCovFile: ["configs/CovObjs/OscCov_PDG2021_v2.yaml"]
    OscCovName: "osc_cov"
    OscFix: ["baseline"]

  Fitter:
    FitTestLikelihood: false
  MCMC:
    NSteps: 2000
    AutoSave: 10000
  Output:
    FileName: "TestEventRates.root"
    OUTPUTNAME: "TestLLH.root"
  ProcessMCMC: No
  Seed: 0
  Debug: No

GeneralKinematicCuts:
- Name: "InFDV"
  VarString: "InFDV"
  Range: [1.,2.]
- Name: "IsCC"
  VarString: "IsCC"
  Range: [1.,2.]
- Name: "Enu"
  VarString: "TrueNeutrinoEnergy"
  Range: [1.,5.]
#- Name: "StoppedInTPC"
#  VarString: "Particle_IsStoppedInTPC"
#  Range: [1.,2.]
#- Name: "StoppedInECal"
#  VarString: "Particle_IsStoppedInECal"
#  Range: [1.,2.]
#- Name: "StoppedInGap"
#  VarString: "Particle_IsStoppedInGap"
#  Range: [1.,2.]

"Projections": [
  {
    "Name": "TrueQ3_vs_TrueQ0",
    "VarStrings": ["TrueQ3","TrueQ0"],
    "VarBins": [[100,0.,3.],[100,0.,3.]],
  },
  {
    "Name": "TrueQ3_vs_TrueQ0_Accepted",
    "VarStrings": ["TrueQ3","TrueQ0"],
    "VarBins": [[100,0.,3.],[100,0.,3.]],
    "KinematicCuts": [
      {
        "Range": [1.,2.],
        "Name": "Accepted",
        "VarString": "Event_IsAccepted"
      }
    ]
  },
  {
    "Name": "Particle_BAngle_MomResMS",
    "VarStrings": ["Particle_BAngle","Particle_MomResMS"],
    "VarBins":[[90,0.,180.],[100,0.,0.2]]
  },
  {
    "Name": "Particle_BAngle_MomResMS_Accepted",
    "VarStrings": ["Particle_BAngle","Particle_MomResMS"],
    "VarBins":[[90,0.,180.],[100,0.,0.2]],
    "KinematicCuts": [
      {
        "Range": [1.,2.],
        "Name": "Accepted",
        "VarString": "Particle_IsAccepted"
      }
    ]
  },
  {
    "Name": "Particle_BAngle_MomResTrans",
    "VarStrings": ["Particle_BAngle","Particle_MomResTrans"],
    "VarBins":[[90,0.,180.],[100,0.,1.]]
  },
  {
    "Name": "Particle_BAngle_MomResTrans_Accepted",
    "VarStrings": ["Particle_BAngle","Particle_MomResTrans"],
    "VarBins":[[90,0.,180.],[100,0.,1.]],
    "KinematicCuts": [
      {
        "Range": [1.,2.],
        "Name": "Accepted",
        "VarString": "Particle_IsAccepted"
      }
    ]
  },
{
    "Name": "Particle_BAngle_Momentum",
    "VarStrings": ["Particle_BAngle","Particle_Momentum"],
    "VarBins": [[90,0.,180.],[200,0.,6.]],
  },
  {
    "Name": "Particle_BAngle_Momentum_Accepted",
    "VarStrings": ["Particle_BAngle","Particle_Momentum"],
    "VarBins": [[90,0.,180.],[200,0.,6.]],
    "KinematicCuts": [
      {
        "Range": [1.,2.],
        "Name": "Accepted",
        "VarString": "Particle_IsAccepted"
      }
    ]
  },
  {
    "Name": "Particle_BAngle_Momentum_Protons",
    "VarStrings": ["Particle_BAngle","Particle_Momentum"],
    "VarBins": [[90,0.,180.],[200,0.,6.]],
    "KinematicCuts": [
      {
        "Range": [2211.5,2212.5],
        "Name": "Protons",
        "VarString": "Particle_PDG"
      }
    ]
  },
  {
    "Name": "Particle_BAngle_Momentum_Protons_Accepted",
    "VarStrings": ["Particle_BAngle","Particle_Momentum"],
    "VarBins": [[90,0.,180.],[200,0.,6.]],
    "KinematicCuts": [
      {
        "Range": [2211.5,2212.5],
        "Name": "Protons",
        "VarString": "Particle_PDG"
      },
      {
        "Range": [1.,2.],
        "Name": "Accepted",
        "VarString": "Particle_IsAccepted"
      }
    ]
  },
  {
    "Name": "Particle_BAngle_Momentum_Pi+",
    "VarStrings": ["Particle_BAngle","Particle_Momentum"],
    "VarBins": [[90,0.,180.],[200,0.,6.]],
    "KinematicCuts": [
      {
        "Range": [210.5,211.5],
        "Name": "Pi+",
        "VarString": "Particle_PDG"
      }
    ]
  },
  {
    "Name": "Particle_BAngle_Momentum_Pi+_Accepted",
    "VarStrings": ["Particle_BAngle","Particle_Momentum"],
    "VarBins": [[90,0.,180.],[200,0.,6.]],
    "KinematicCuts": [
      {
        "Range": [210.5,211.5],
        "Name": "Pi+",
        "VarString": "Particle_PDG"
      },
      {
        "Range": [1.,2.],
        "Name": "Accepted",
        "VarString": "Particle_IsAccepted"
      }
    ]
  },
  {
    "Name": "Particle_BAngle_Momentum_Pi-",
    "VarStrings": ["Particle_BAngle","Particle_Momentum"],
    "VarBins": [[90,0.,180.],[200,0.,6.]],
    "KinematicCuts": [
      {
        "Range": [-211.5,-210.5],
        "Name": "Pi-",
        "VarString": "Particle_PDG"
      }
    ]
  },
  {
    "Name": "Particle_BAngle_Momentum_Pi-_Accepted",
    "VarStrings": ["Particle_BAngle","Particle_Momentum"],
    "VarBins": [[90,0.,180.],[200,0.,6.]],
    "KinematicCuts": [
      { 
        "Range": [-211.5,-210.5],
        "Name": "Pi-",
        "VarString": "Particle_PDG"
      },
      {
        "Range": [1.,2.],
        "Name": "Accepted",
        "VarString": "Particle_IsAccepted"
      }
    ]
  },
  {
    "Name": "Particle_BAngle_Momentum_Mu-",
    "VarStrings": ["Particle_BAngle","Particle_Momentum"],
    "VarBins": [[90,0.,180.],[200,0.,6.]],
    "KinematicCuts": [
      {
        "Range": [12.5,13.5],
        "Name": "Mu-",
        "VarString": "Particle_PDG"
      }
    ]
  },
  {
    "Name": "Particle_BAngle_Momentum_Mu-_Accepted",
    "VarStrings": ["Particle_BAngle","Particle_Momentum"],
    "VarBins": [[90,0.,180.],[200,0.,6.]],
    "KinematicCuts": [
      {
        "Range": [12.5,13.5],
        "Name": "Mu-",
        "VarString": "Particle_PDG"
      },
      {
        "Range": [1.,2.],
        "Name": "Accepted",
        "VarString": "Particle_IsAccepted"
      }
    ]
  },
  {
    "Name": "Particle_PDG",
    "VarStrings": ["Particle_PDG"],
    "VarBins": [[6444,-3222.5,3222.5]],
  },
  {
    "Name": "Particle_PDG_Accepted",
    "VarStrings": ["Particle_PDG"],
    "VarBins": [[6444,-3222.5,3222.5]],
    "KinematicCuts": [
      {
        "Range": [1.,2.],
        "Name": "Accepted",
        "VarString": "Particle_IsAccepted"
      }
    ]
  },
]
