General:
  OutputFile: "/scratch/abipeake/MaCh3_DUNE_merged/MaCh3_DUNE/Chain_testing/adaptive_fit_nonefixed_27thmau.root"
  DUNESamples:
     - "/scratch/abipeake/MaCh3_DUNE_merged/MaCh3_DUNE/configs/Samples/OA_samples_subsamples/0m_CC_q0q3.yaml"
   

  OscillationParameters: [0.0, 0.0, 0.0, 7.53e-5, 2.509e-3, -1.601, 1284.9, 2.848, 0.5] #[0.307, 0.528, 0.0218, 7.53e-5, 2.509e-3, -1.601, 1284.9, 2.848]#[0.307, 0.528, 0.0218, 7.53e-5, 2.509e-3, -1.601, 1284.9, 2.848] #[0.0, 0.0, 0.0, 7.53e-5, 2.509e-3, -1.601, 1284.9, 2.848] #[0.307, 0.528, 0.0218, 7.53e-5, 2.509e-3, -1.601, 1284.9, 2.848]
  OscillatorConfigName: "configs/OscillatorObj.yaml"

  Systematics:
    XsecCovFile: ["/scratch/abipeake/MaCh3_DUNE_merged/MaCh3_DUNE/configs/CovObjs/q0q3_triangle_1275params.yaml"] #["configs/CovObjs/q0q3_0.0_5.0GeV_triangle_morebins.yaml"] ["configs/CovObjs/xsec_energy_abi_moreparameters.yaml"]  #["configs/CovObjs/xsec_abi_manyparameters_nd.yaml"] #["configs/CovObjs/xsec_energy_abi_moreparameters.yaml"]  #["configs/CovObjs/xsec_abi_manyparameters_nd.yaml"]
    XsecCovName: "xsec_cov"
    XsecStepScale: 0.002
    XsecAtGen: false 
    OscCovFile: ["/scratch/abipeake/MaCh3_DUNE_merged/MaCh3_DUNE/configs/CovObjs/OscCov_ND.yaml"]
    OscCovName: "osc_cov"

  Fitter:
    FitTestLikelihood: false
  MCMC:
    NSteps: 2000000 #50000
    AutoSave: 10000
    BurnInSteps: 0
  Output:
    FileName: "TestEventRates_fit_10000.root"
    OUTPUTNAME: "TestLLH__fit_10000.root"

  ProcessMCMC: No
  Seed: 0
  Debug: No
LLHScan:
  ParPoints: 1000
AdaptionOptions:
  Settings:
    StartThrow:  200000
    StartUpdate: 1000
    EndUpdate:   2000000
    UpdateStep:  1000
    SaveNIterations: 10000
    OutputFileName: mcmc_covariance.root

  Covariance:
    xsec_cov:
      DoAdaption: True
      MatrixBlocks: []
      UseExternalMatrix: False
  
Predictive:
  PosteriorFiles: "Chain_testing/Enurec_Elep_test_largerxsecscale4.root"
  Ntoy: 1000
  ThrowDetCov: true
  FixXSec: false
  FixFlux: false
  VarNames: ["RecoNeutrinoEnergy", "q0", "q3", "ELepRec"  ]
  
NDOptions:
  PlotByMode: false

