General:
  OutputFile: "DuneEventRates.root"

  DUNESamples: ["configs/Samples/AtmSample_numuselec.yaml","configs/Samples/AtmSample_nueselec.yaml"]

  #Nu-FIT
  #OscillationParameters: [0.310, 0.582, 0.224, 7.39E-5, 2.5254E-3, -2.498, 25]

  #Nu-FIT 5.2 w. SK atm
  OscillationParameters: [0.303, 0.452, 0.0223, 7.41E-5, 2.51E-3, -2.233, 25]

  #T2K-like best-fit
  #OscillationParameters: [0.307, 0.528, 0.0218, 7.53e-5, 2.509e-3, -1.601, 25]

  #Unoscillated
  #OscillationParameters: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2.5]
  
  Systematics:
    XsecCovFile: ["configs/CovObjs/xsec_covariance_DUNE_systs_2022a_FD_v3.yaml"]
    XsecCovName: "xsec_cov"
    XsecStepScale: 0.1
    XsecAtGen: false 
    OscCovFile: ["configs/CovObjs/OscCov_PDG2021_v2_Atmospherics.yaml"]
    OscCovName: "osc_cov"

  Fitter:
    FitTestLikelihood: false

  MCMC:
    NSteps: 2000
    AutoSave: 10000

  Output:
    FileName: "TestEventRates.root"
    OUTPUTNAME: "TestLLH.root"

  ProcessMCMC: No
  Seed: 0
  Debug: No
