General:
  OutputFile: "outputs/Projections_CC_BField0_5_FidRad_160_FidLen_209_InstRad_249_45_InstLen_259_WithECal_Enu_1to5GeV_fixednhits.root"
  #OutputFile: "outputs/FinalComparison_endgap.root"
  DUNESamples: ["configs/Samples/SamplePDFDune_NDGAr_FHC_numuselec.yaml"]	
  #Nu-FIT
  #OscillationParameters: [0.310, 0.582, 0.224, 7.39E-5, 2.5254E-3, -2.498]
  # T2K-like best-fit
  OscillationParameters: [0.307, 0.528, 0.0218, 7.53e-5, 2.509e-3, -1.601, 1284.9, 2.848]
  OscillatorConfigName: "configs/OscillatorObj.yaml"
  Systematics:
    XsecCovFile: ["configs/CovObjs/xsec_covariance_DUNE_systs_NDGAr.yaml"]
    XsecCovName: "xsec_cov"
    XsecStepScale: 0.1
    XsecAtGen: false 
    OscCovFile: ["configs/CovObjs/OscCov_PDG2021_v2.yaml"]
    OscCovName: "osc_cov"
    OscFix: ["baseline"]

  Fitter:
    FitTestLikelihood: false
  MCMC:
    NSteps: 2000
    AutoSave: 10000
  Output:
    FileName: "TestEventRates.root"
    OUTPUTNAME: "TestLLH.root"
  ProcessMCMC: No
  Seed: 0
  Debug: No

GeneralKinematicCuts:
- Name: "InFDV"
  VarString: "InFDV"
  Range: [1.,2.]
- Name: "IsCC"
  VarString: "IsCC"
  Range: [1.,2.]
- Name: "Enu"
  VarString: "TrueNeutrinoEnergy"
  Range: [1.,5.]
#- Name: "StoppedInTPC"
#  VarString: "Particle_IsStoppedInTPC"
#  Range: [0.,1.]
#- Name: "StoppedInECal"
#  VarString: "Particle_IsStoppedInECal"
#  Range: [0.,1.]
#- Name: "StoppedInGap"
#  VarString: "Particle_IsStoppedInGap"
#  Range: [0.,1.]
#- Name: "StoppedInEndGap"
#  VarString: "Particle_IsStoppedInEndGap"
#  Range: [1.,2.]
#- Name: "StoppedInBarrelGap"
#  VarString: "Particle_IsStoppedInBarrelGap"
#  Range: [1.,2.]

"Projections": [
  {
    "Name": "TrueNeutrinoEnergy",
    "VarStrings": ["TrueNeutrinoEnergy"],
    "VarBins": [[0.,  0.5,  1.,  1.25, 1.5, 1.75, 2., 2.25, 2.5, 2.75, 3., 3.25, 3.5, 3.75, 4., 5., 6., 10.]],
  }, 
  {
    "Name": "TrueQ3_vs_TrueQ0",
    "VarStrings": ["TrueQ3","TrueQ0"],
    "VarBins": [[100,0.,3.],[100,0.,3.]],
  },
  {
    "Name": "TrueQ3_vs_TrueQ0_Accepted",
    "VarStrings": ["TrueQ3","TrueQ0"],
    "VarBins": [[100,0.,3.],[100,0.,3.]],
    "KinematicCuts": [
      {
        "Range": [1.,2.],
        "Name": "Accepted",
        "VarString": "Event_IsAccepted"
      }
    ]
  },
  {
    "Name": "Particle_BAngle_MomResMS",
    "VarStrings": ["Particle_BAngle","Particle_MomResMS"],
    "VarBins":[[90,0.,180.],[100,0.,0.2]]
  },
  {
    "Name": "Particle_BAngle_MomResMS_Accepted",
    "VarStrings": ["Particle_BAngle","Particle_MomResMS"],
    "VarBins":[[90,0.,180.],[100,0.,0.2]],
    "KinematicCuts": [
      {
        "Range": [1.,2.],
        "Name": "Accepted",
        "VarString": "Particle_IsAccepted"
      }
    ]
  },
  {
    "Name": "Particle_BAngle_MomResTrans",
    "VarStrings": ["Particle_BAngle","Particle_MomResTrans"],
    "VarBins":[[90,0.,180.],[100,0.,1.]]
  },
  {
    "Name": "Particle_BAngle_MomResTrans_Accepted",
    "VarStrings": ["Particle_BAngle","Particle_MomResTrans"],
    "VarBins":[[90,0.,180.],[100,0.,1.]],
    "KinematicCuts": [
      {
        "Range": [1.,2.],
        "Name": "Accepted",
        "VarString": "Particle_IsAccepted"
      }
    ]
  },
  {
    "Name": "Particle_BAngle_Momentum",
    "VarStrings": ["Particle_BAngle","Particle_Momentum"],
    "VarBins": [[90,0.,180.],[200,0.,6.]],
  },
  {
    "Name": "Particle_BAngle_Momentum_Accepted",
    "VarStrings": ["Particle_BAngle","Particle_Momentum"],
    "VarBins": [[90,0.,180.],[200,0.,6.]],
    "KinematicCuts": [
      {
        "Range": [1.,2.],
        "Name": "Accepted",
        "VarString": "Particle_IsAccepted"
      }
    ]
  },
  {
    "Name": "Particle_BAngle_Momentum_Protons",
    "VarStrings": ["Particle_BAngle","Particle_Momentum"],
    "VarBins": [[90,0.,180.],[200,0.,6.]],
    "KinematicCuts": [
      {
        "Range": [2211.5,2212.5],
        "Name": "Protons",
        "VarString": "Particle_PDG"
      }
    ]
  },
  {
    "Name": "Particle_BAngle_Momentum_Protons_Accepted",
    "VarStrings": ["Particle_BAngle","Particle_Momentum"],
    "VarBins": [[90,0.,180.],[200,0.,6.]],
    "KinematicCuts": [
      {
        "Range": [2211.5,2212.5],
        "Name": "Protons",
        "VarString": "Particle_PDG"
      },
      {
        "Range": [1.,2.],
        "Name": "Accepted",
        "VarString": "Particle_IsAccepted"
      }
    ]
  },
  {
    "Name": "Particle_BAngle_Momentum_Pi+",
    "VarStrings": ["Particle_BAngle","Particle_Momentum"],
    "VarBins": [[90,0.,180.],[200,0.,6.]],
    "KinematicCuts": [
      {
        "Range": [210.5,211.5],
        "Name": "Pi+",
        "VarString": "Particle_PDG"
      }
    ]
  },
  {
    "Name": "Particle_BAngle_Momentum_Pi+_Accepted",
    "VarStrings": ["Particle_BAngle","Particle_Momentum"],
    "VarBins": [[90,0.,180.],[200,0.,6.]],
    "KinematicCuts": [
      {
        "Range": [210.5,211.5],
        "Name": "Pi+",
        "VarString": "Particle_PDG"
      },
      {
        "Range": [1.,2.],
        "Name": "Accepted",
        "VarString": "Particle_IsAccepted"
      }
    ]
  },
  {
    "Name": "Particle_BAngle_Momentum_Pi-",
    "VarStrings": ["Particle_BAngle","Particle_Momentum"],
    "VarBins": [[90,0.,180.],[200,0.,6.]],
    "KinematicCuts": [
      {
        "Range": [-211.5,-210.5],
        "Name": "Pi-",
        "VarString": "Particle_PDG"
      }
    ]
  },
  {
    "Name": "Particle_BAngle_Momentum_Pi-_Accepted",
    "VarStrings": ["Particle_BAngle","Particle_Momentum"],
    "VarBins": [[90,0.,180.],[200,0.,6.]],
    "KinematicCuts": [
      { 
        "Range": [-211.5,-210.5],
        "Name": "Pi-",
        "VarString": "Particle_PDG"
      },
      {
        "Range": [1.,2.],
        "Name": "Accepted",
        "VarString": "Particle_IsAccepted"
      }
    ]
  },
  {
    "Name": "Particle_BAngle_Momentum_Mu-",
    "VarStrings": ["Particle_BAngle","Particle_Momentum"],
    "VarBins": [[90,0.,180.],[200,0.,6.]],
    "KinematicCuts": [
      {
        "Range": [12.5,13.5],
        "Name": "Mu-",
        "VarString": "Particle_PDG"
      }
    ]
  },
  {
    "Name": "Particle_BAngle_Momentum_Mu-_Accepted",
    "VarStrings": ["Particle_BAngle","Particle_Momentum"],
    "VarBins": [[90,0.,180.],[200,0.,6.]],
    "KinematicCuts": [
      {
        "Range": [12.5,13.5],
        "Name": "Mu-",
        "VarString": "Particle_PDG"
      },
      {
        "Range": [1.,2.],
        "Name": "Accepted",
        "VarString": "Particle_IsAccepted"
      }
    ]
  },
  {
    "Name": "Particle_PDG",
    "VarStrings": ["Particle_PDG"],
    "VarBins": [[6444,-3222.5,3222.5]],
  },
  {
    "Name": "Particle_PDG_Accepted",
    "VarStrings": ["Particle_PDG"],
    "VarBins": [[6444,-3222.5,3222.5]],
    "KinematicCuts": [
      {
        "Range": [1.,2.],
        "Name": "Accepted",
        "VarString": "Particle_IsAccepted"
      }
    ]
  },
  {
    "Name": "Particle_Momentum",
    "VarStrings": ["Particle_Momentum"],
    "VarBins": [[100,0.,6]],
  },
  {
    "Name": "Particle_Transverse_Momentum",
    "VarStrings": ["Particle_TransverseMomentum"],
    "VarBins": [[100,0.,6.]],
  },
  {
    "Name": "Particle_N_Hits_in_TPC",
    "VarStrings": ["Particle_NHits"],
    "VarBins": [[20,0,500]],
  },
  {
    "Name": "Particle_N_Helix_Turns",
    "VarStrings": ["Particle_NTurns"],
    "VarBins": [[100,0.,6.]],
  },
  {
    "Name": "Particle_N_Helix_Turns_p+",
    "VarStrings": ["Particle_NTurns"],
    "VarBins": [[100,0.,6.]],
    "KinematicCuts": [
      {
        "Range": [2211.5,2212.5],
        "Name": "p+",
        "VarString": "Particle_PDG"
      }
    ]
  },
  {
    "Name": "Particle_N_Helix_Turns_mu-",
    "VarStrings": ["Particle_NTurns"],
    "VarBins": [[100,0.,6.]],
    "KinematicCuts": [
      {
        "Range": [12.5,13.5],
        "Name": "mu-",
        "VarString": "Particle_PDG"
      }
    ]
  },
  {
    "Name": "Particle_N_Helix_Turns_pi+",
    "VarStrings": ["Particle_NTurns"],
    "VarBins": [[100,0.,6.]],
    "KinematicCuts": [
      {
        "Range": [210.5,211.5],
        "Name": "pi+",
        "VarString": "Particle_PDG"
      }
    ]
  },
  {
    "Name": "Particle_N_Helix_Turns_pi-",
    "VarStrings": ["Particle_NTurns"],
    "VarBins": [[100,0.,6.]],
    "KinematicCuts": [
      {
        "Range": [-211.5,-210.5],
        "Name": "pi-",
        "VarString": "Particle_PDG"
      }
    ]
  },
  {
    "Name": "Interaction Mode",
    "VarStrings": ["Mode"],
    "VarBins": [[20,-0.5,19.5]],
  },
  {
    "Name": "Interaction Mode (bad caf events)",
    "VarStrings": ["Mode"],
    "VarBins": [[20,-0.5,19.5]],
    "KinematicCuts": [
      { 
        "Range": [0.,0.5],
        "Name": "Bad CAF Event",
        "VarString": "IsGoodCAFEvent"
      }
    ]
  },
]
