General:
  OutputFile: "Chain_testing/1Dtest_flatprior.root"
  DUNESamples:
     - "configs/Samples/OA_samples_subsamples/0m_CC_1D.yaml"
     #- "configs/Samples/OA_samples_subsamples/0m_CC_newconfig.yaml"
     #- "configs/Samples/OA_samples_subsamples/0m_CC_Enurec_Elep.yaml"

  OscillationParameters: [0.0, 0.0, 0.0, 7.53e-5, 2.509e-3, -1.601, 1284.9, 2.848, 0.5] #[0.307, 0.528, 0.0218, 7.53e-5, 2.509e-3, -1.601, 1284.9, 2.848]#[0.307, 0.528, 0.0218, 7.53e-5, 2.509e-3, -1.601, 1284.9, 2.848] #[0.0, 0.0, 0.0, 7.53e-5, 2.509e-3, -1.601, 1284.9, 2.848] #[0.307, 0.528, 0.0218, 7.53e-5, 2.509e-3, -1.601, 1284.9, 2.848]
  OscillatorConfigName: "configs/OscillatorObj.yaml"
  Systematics:
    XsecCovFile: ["configs/CovObjs/1D_Reconeutrinoenergy.yaml"]
    XsecCovName: "xsec_cov"
    XsecStepScale: 0.001
    XsecAtGen: false 
    OscCovFile: ["configs/CovObjs/OscCov_ND.yaml"]
    OscCovName: "osc_cov"
  Fitter:
    FitTestLikelihood: false
  MCMC:
    NSteps: 10000 #50000
    AutoSave: 1000
    BurnInSteps: 1
  Output:
    FileName: "TestEventRates_fit_10000.root"
    OUTPUTNAME: "TestLLH__fit_10000.root"
  ProcessMCMC: No
  Seed: 0
  Debug: No
LLHScan:
  ParPoints: 1000
AdaptionOptions:
  Settings:
    StartThrow:  2000
    StartUpdate: 2000
    EndUpdate:   8500
    UpdateStep:  1000
    SaveNIterations: 1000
    OutputFileName: mcmc_covariance.root

  Covariance:
    xsec_cov:
      DoAdaption: True
      MatrixBlocks: []
      UseExternalMatrix: False
      PrincipalComponentThreshold: 0.99 

Predictive:
  PosteriorFiles: "Chain_testing/1D.root"
  Ntoy: 1000
  ThrowDetCov: true
  FixXSec: false
  FixFlux: false

NDOptions:
  PlotByMode: false

