---
General:
  OutputFile: "DuneEventRates.root"

  DUNESamples:
    - "Configs/Samples/AtmSample_numuselec.yaml"
    - "Configs/Samples/AtmSample_nueselec.yaml"    

  # Nu-FIT
  # OscillationParameters: [0.310, 0.582, 0.224, 7.39E-5, 2.5254E-3, -2.498, 25]

  # Nu-FIT 5.2 w. SK atm
  OscillationParameters: [0.303, 0.452, 0.0223, 7.41E-5, 2.51E-3, -2.233, 25,  1221.5, 3480., 5701., 6371., 1., 1., 1., 1., 0.468, 0.468, 0.496, 0.496]
  #OscillationParameters: [0.303, 0.452, 0.0223, 7.41E-5, 2.51E-3, -2.233, 25]

  # T2K-like best-fit
  # OscillationParameters: [0.307, 0.528, 0.0218, 7.53e-5, 2.509e-3, -1.601, 25]

  # Unoscillated
  # OscillationParameters: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2.5]

  Systematics:
    XsecCovFile: ["Configs/CovObjs/xsec_covariance_DUNE_systs_2022a_FD_v3.yaml", "Configs/CovObjs/OscCov_PDG2021_v2_Atmospherics.yaml"]
    XsecCovName: "xsec_cov"
    XsecStepScale: 0.1
    XsecAtGen: false
    XsecFix: []

  SharedNuOscillatorObject:
    ATM: "Configs/NuOsc/CUDAProb3_SubSampling_ProdHAvg_EarthSysts.yaml"

  Fitter:
    FitTestLikelihood: false

  MCMC:
    NSteps: 20000
    AutoSave: 5000

  Output:
    FileName: "TestEventRates.root"
    OUTPUTNAME: "TestLLH.root"

  Seed: 0
  Debug: No
  StartFromPos: false
  PosFileName: "chain_0.root"

ProcessMCMC:
  BurnInSteps: 80000
  Thinning: [false, 100]

  PrintToPDF: true
  PlotCorr: true
  ExcludedTypes: []
  ExcludedNames: []

  Posterior1DCut: "Weight"
  PlotRelativeToPrior: false
  PlotErrorForFlatPrior: false
  FancyNames: true
  PlotBinValue: false
  Post2DPlotThreshold: 0.0

  Smoothing: false
  MakeViolin: true
  MakeSubOptimality: ["false", 100]

  DiagnoseCovarianceMatrix: false

  #=============================================================================

  MakeCredibleIntervals: true
  CredibleRegions: [0.99, 0.90, 0.68]
  CredibleIntervalsColours: [436, 430, 422]
  CredibleInSigmas: false

  MakeCredibleRegions: true
  CredibleRegions: [0.99, 0.90, 0.68]
  CredibleRegionStyle: [2, 1, 3]
  CredibleRegionColor: [413, 406, 416]
  CredibleInSigmas: false
  Draw2DPosterior: false
  DrawBestFit: true

  CalcSavageDickey: true
  SavageDickey:
    - ["delta_cp", 0.0, [-3.14, 3.14]]

  CalcBayesFactor: true
  BayesFactor:
    - ["delm2_23", ["IH", "NH"], [-0.01, 0], [0, 0.01]]
    - ["sin2th_23", ["LO", "UO"], [0, 0.5], [0.5, 1]]

  GetTrianglePlot: true
  TrianglePlot:
    - ["OscPars", ["delm2_23", "sin2th_23", "sin2th_13", "delta_cp"]]

  ReweightPrior: true
  PriorReweighting: [ ["sin2th_13"], [0.0220], [0.0007] ]

  JarlskogAnalysis: true

  CalcBipolarPlot: false
  CalcParameterEvolution: false

  #=============================================================================

"Projections": [
  {
    "Name": "RecoNuEnergy",
    "VarString": "RecoNeutrinoEnergy",
    "VarBins": [0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0, 1.2, 1.4],
    "KinematicCuts": [
      {
        "Range": [0.1, 0.8],
        "Name": "TrueNuEnergy",
        "VarString": "TrueNeutrinoEnergy"
      },
      {
        "Range": [0.4, 1.0],
        "Name": "TrueCosZ",
        "VarString": "TrueCosineZ"
      }
    ],
    "CategoryCuts": [
      {
        "Name": "OscillationChannel_Single",
        "VarString": "OscChannel",
        "Breakdown": [[0.0], [1.0], [2.0], [3.0], [4.0], [5.0], [6.0], [7.0], [8.0], [9.0], [10.0], [11.0]],
        "Names": ["nue_x_nue", "nue_x_numu", "nue_x_nutau", "numu_x_nue",
                  "numu_x_numu", "numu_x_nutau", "nuebar_x_nuebar",
                  "nuebar_x_numubar", "nuebar_x_nutaubar", "numubar_x_nuebar",
                  "numubar_x_numubar", "numubar_x_nutaubar"],
      },
      {
        "Name": "OscillationChannel_Group",
        "VarString": "OscChannel",
        "Breakdown": [[0.0, 1.0, 2.0, 3.0, 4.0, 5.0], [6.0, 7.0, 8.0, 9.0, 10.0, 11.0]],
        "Names": ["Nu", "Nubar"],
      },
      {
        "Name": "Mode_Single",
        "VarString": "Mode",
        "Breakdown": [[0.0], [1.0], [2.0], [3.0], [4.0], [5.0], [6.0], [7.0], [8.0],
                      [9.0], [10.0], [11.0], [12.0], [13.0], [14.0], [15.0], [16.0],
                      [17.0], [18.0], [19.0], [20.0], [21.0], [22.0], [23.0],
                      [24.0], [25.0], [26.0]],
      },
      {
        "Name": "Mode_Group",
        "VarString": "Mode",
        "Breakdown": [[0.0], [2.0], [3.0], [9.0], [15.0], [16.0], [1.0, 4.0, 5.0, 6.0, 7.0, 8.0, 10.0, 11.0, 12.0, 13.0], [14.0, 17.0, 18.0, 19.0, 20.0, 21.0, 22.0, 23.0, 24.0, 25.0, 26.0]],
        "Names": ["CCQE", "CCDIS", "CCRES", "CCMEC", "NCDIS", "NCRES", "CCOth", "NCOth"],
      }
    ],
  },

  {
    "Name": "TrueNuEnergy",
    "VarString": "TrueNeutrinoEnergy",
    "VarBins": [0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0, 1.2, 1.4, 1.6, 1.8, 2.0,
                2.2, 2.4, 2.6, 2.8, 3.0, 3.5, 4.0, 4.5, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0],
  }
]
