General:
  OutputFile: "outputs/liban_stepsize/DuneEventRates_debug.root"
  # DUNESamples: ["configs/Samples/SamplePDFDuneND_FHC_numuselec_everything.yaml"] 
  # DUNESamples: ["configs/Samples/SamplePDFDuneND_RHC_numuselec_everything.yaml"] 
  # DUNESamples: ["configs/Samples/SamplePDFDuneND_FHC_numuselec_everything.yaml", "configs/Samples/SamplePDFDuneND_RHC_numuselec_everything.yaml"] 
  DUNESamples: ["configs/Samples/SamplePDFDuneND_FHC_numuselec.yaml"]
  #Nu-FIT
  #OscillationParameters: [0.310, 0.582, 0.224, 7.39E-5, 2.5254E-3, -2.498]
  # T2K-like best-fit
  # OscillationParameters: [0.307, 0.528, 0.0218, 7.53e-5, 2.509e-3, -1.601, 1284.9, 2.848]
  OscillationParameters: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

  OscillatorConfigName: "configs/OscillatorObj.yaml"
  Systematics:
    XsecCovFile: ["configs/CovObjs/xsec_covariance_DUNE_systs_2022a_FD_v3_flux.yaml"]
    XsecCovName: "xsec_cov"
    XsecStepScale: 0.2
    # Start with a large step scale for adaptive
    # XsecStepScale: 1
    XsecAtGen: false 
    OscCovFile: ["configs/CovObjs/OscCov_PDG2021_v2_unoscillated.yaml"]
    OscCovName: "osc_cov"

  Fitter:
    FitTestLikelihood: false
  MCMC:
    NSteps: 1000
    AutoSave: 10000
  Output:
    FileName: "TestEventRates.root"
    OUTPUTNAME: "TestLLH.root"
  ProcessMCMC: No
  Seed: 0
  Debug: Yes

# AdaptionOptions:
#   Settings:
#     # When do we start throwing from our adaptive matrix?
#     AdaptionStartThrow : 2000
#     # When do we start putting steps into our adaptive covariance?
#     AdaptionStartUpdate : 0
#     # When do we end updating our covariance?
#     AdaptionEndUpdate : 50000
#     # How often do we change our matrix throws?
#     AdaptionUpdateStep : 1000
#   Covariance:
#     # So now we list individual matrices, let's just do xsec
#     xsec_cov:
#       # Do we want to adapt this matrix?
#       DoAdaption: true
#       # So we can separate out flux and xsec
#       MatrixBlocks: [ ]
#       # External Settings
#       UseExternalMatrix: false
#       ExternalMatrixFileName: ""
#       ExternalMatrixName: ""
#       ExternalMeansName: ""
#     osc_cov:
#       DoAdaption: false
#       # So we can separate out flux and xsec
#       MatrixBlocks: [  ]
#       # External Settings
#       UseExternalMatrix: false
#       ExternalMatrixFileName: ""
#       ExternalMatrixName: ""
#       ExternalMeansName: ""
