---
General:
  OutputFile: "DuneEventRates.root"
  DUNESamples:
   - "Configs/Samples/SamplePDFDune_FHC_numuselec.yaml"
   - "Configs/Samples/SamplePDFDune_FHC_nueselec.yaml"
   - "Configs/Samples/SamplePDFDune_RHC_numuselec.yaml"
   - "Configs/Samples/SamplePDFDune_RHC_nueselec.yaml"
   
  OscillationParameters: [0.307, 0.528, 0.0218, 7.53e-5, 2.509e-3, -1.601, 1284.9, 2.848, 0.5, 9.48e-18, 2.0, 1.] # 9.48e-18

  # Nu-FIT
  #OscillationParameters: [0.310, 0.582, 0.0224, 7.39E-5, 2.525E-3, -2.498, 1284.9, 2.848] #CUDAProb3
  #OscillationParameters: [0.310, 0.582, 0.0224, 7.39E-5, 2.525E-3, -2.498, 1284.9, 2.848,  0.5] #NuFAST

  # T2K-like best-fit
  #OscillationParameters: [0.307, 0.528, 0.0218, 7.53e-5, 2.509e-3, -1.601, 1284.9, 2.848] #CUDAProb3
  #OscillationParameters: [0.307, 0.528, 0.0218, 7.53e-5, 2.509e-3, -1.601, 1284.9, 2.848, 0.5] #NuFAST

  OscillatorConfigName: "Configs/OscillatorObj.yaml"

  Systematics:
    XsecCovFile:
      - "Configs/CovObjs/tdr_covs/Xsec_ND+FD.yaml"
      - "Configs/CovObjs/tdr_covs/Flux_ND+FD.yaml"
      - "Configs/CovObjs/tdr_covs/DetSysts_FD.yaml"
    XsecCovName: "xsec_cov"
    XsecStepScale: 0.05
    XsecAtGen: false
    NDCovFile: "Configs/CovObjs/tdr_covs/det_sys_cov.root"
    OscCovFile: ["Configs/CovObjs/OscCov_PDG2021_v2.yaml"]
    OscCovName: "osc_cov"
    OscFix: ["baseline", "density"]

  Fitter:
    FitTestLikelihood: false
  MCMC:
    NSteps: 2000
    AutoSave: 10000
  Output:
    FileName: "TestEventRates.root"
    OUTPUTNAME: "TestLLH.root"
  ProcessMCMC: No
  Seed: 0
  Debug: No

# LLH Scan settings
LLHScan:
  # don't make LLH for certain systematic groups
  #LLHScanSkipVector: []
  # Save individual sample contributions to the LLH
  LLHScanBySample: false
  # Number of points we run LLH scans for each systematic
  #LLHScanPoints: 50
  # Number of points for 2D scan in each direction
  #2DLLHScanPoints: 20
  # Add physical ranges for special params whose priors/errors may not be well well-defined
  ScanRanges:
    #delta_cp: [-3.14,3.14]

# Tests
Tests:
  SkipChecks: False
  TestResultsFile: tests/test_results/EventRatesV2TDR.txt
