General:
  OutputFile: "/scratch/abipeake/MaCh3_DUNE_merged/MaCh3_DUNE/Chain_testing/help.root"
  DUNESamples:
    # - "/scratch/abipeake/MaCh3_DUNE_merged/MaCh3_DUNE/configs/Samples/OA_samples_subsamples/CERN_0m_pzptEnu.yaml"
     - "configs/Samples/OA_samples_subsamples/0m_CC_Enurec_Elep.yaml"
     #- "configs/Samples/OA_samples_subsamples/0m_CC_newconfig.yaml"
     #- "configs/Samples/OA_samples_subsamples/0m_CC_Enurec_Elep.yaml"

  OscillationParameters: [0.0, 0.0, 0.0, 7.53e-5, 2.509e-3, -1.601, 1284.9, 2.848, 0.5] #[0.307, 0.528, 0.0218, 7.53e-5, 2.509e-3, -1.601, 1284.9, 2.848]#[0.307, 0.528, 0.0218, 7.53e-5, 2.509e-3, -1.601, 1284.9, 2.848] #[0.0, 0.0, 0.0, 7.53e-5, 2.509e-3, -1.601, 1284.9, 2.848] #[0.307, 0.528, 0.0218, 7.53e-5, 2.509e-3, -1.601, 1284.9, 2.848]
  OscillatorConfigName: "/scratch/abipeake/MaCh3_DUNE_merged/MaCh3_DUNE/configs/OscillatorObj.yaml"

  Systematics:
    XsecCovFile: ["/scratch/abipeake/MaCh3_DUNE_merged/MaCh3_DUNE/configs/CovObjs/TrueNeutrinoEnergy_ERecProxy_minus_Enu_0.0_10.0GeV_fullgrid_wider.yaml"]
    XsecCovName: "xsec_cov"
    XsecStepScale: 0.001
    XsecAtGen: false 
    OscCovFile: ["/scratch/abipeake/MaCh3_DUNE_merged/MaCh3_DUNE/configs/CovObjs/OscCov_ND.yaml"]
    OscCovName: "osc_cov"
    xsec_var1: "TrueNeutrinoEnergy"
    xsec_var2: "ERecProxy_minus_Enu"


  Fitter:
    FitTestLikelihood: false
  MCMC:
    NSteps: 1000000 #50000
    AutoSave: 1000
    BurnInSteps: 1
  Output:
    FileName: "TestEventRates_fit_10000.root"
    OUTPUTNAME: "TestLLH__fit_10000.root"

  ProcessMCMC: No
  Seed: 0
  Debug: No
LLHScan:
  ParPoints: 1000
AdaptionOptions:
  Settings:
    StartThrow:  5000
    StartUpdate: 0
    EndUpdate:   1000000
    UpdateStep:  1000
    SaveNIterations: 10000
    OutputFileName: mcmc_covariance.root

  Covariance:
    xsec_cov:
      DoAdaption: True
      MatrixBlocks: []
      UseExternalMatrix: False
      PrincipalComponentThreshold: 0.99 

Predictive:
  PosteriorFiles: "Chain_testing/Enurec_Elep_test_largerxsecscale4.root"
  Ntoy: 1000
  ThrowDetCov: true
  FixXSec: false
  FixFlux: false
  VarNames: ["RecoNeutrinoEnergy", "q0", "q3", "ELepRec"  ]

NDOptions:
  PlotByMode: false
