General:
  POT: 1.3628319e+23 
  Systematics:
    XsecCovFile: "inputs/xsec_covariance_DUNE_systs_060921_v3.root"
    XsecCovName: "xsec_cov"
    XsecAtGen: false
    OscCovFile: "inputs/osc_covariance_DUNE_PDG2021_v1.root"
    OscCovName: "osc_cov"
  Output:
    FileName: "test_outputfile.root"
  ProcessMCMC: No
  Seed: 0
  Debug: No
