General:
  IncludeFD: true
  IncludeND: true
  FDPOT: 1.3628319e+23
  NDPOT: 1.1e+21
  #### Asimov A ####
  #OscParams: [0.307, 0.528, 0.0218, 7.53e-5, 2.509e-3, -1.601]
  # NuFit 4.0 NH ####
  OscParams: [0.310, 0.580, 0.02241, 7.39e-5, 2.4511e-3, -2.531]
  # NuFit 4.0 NH OLD#
  OscParams: [0.310, 0.582, 0.0224, 7.39e-5, 2.525e-3, -2.498]
  Systematics:
    XsecCovFile: "inputs/xsec_covariance_DUNE_systs_2023_nddet_NuPhys.root"
    XsecCovName: "xsec_cov"
    XsecStepScale: 0.05
    XsecAtGen: false 
    OscCovFile: "inputs/osc_covariance_DUNE_PDG2021_v1.root"
    OscCovName: "osc_cov"
    NDCovFile: "inputs/det_sys_cov.root"
    OscStepScale: 0.045
  Output:
    FileName: "MaCh3_FD+ND_test.root"
MCMC:
  NSTEPS: 2000000
  StartFromPos: false
  PosFileName: 
  StatOnly: false
  ProcessMCMC: No
  Seed: 0
  AutoSave: 500
  Debug: Yes
