General:
  Systematics:
    XsecCovFile: "inputs/xsec_covariance_DUNE_systs_2022a_v1.root"
    XsecCovName: "xsec_cov"
    OscCovFile: "inputs/oscillation_covariance_6par_nondouble_PDG2019.root"
    OscCovName: "osc_cov"
  Output:
    OUTPUTNAME: "MaCh3_output.root"
  ProcessMCMC: No
  Seed: 0
  Debug: No
