OscillatorObj:
  OscillatorEarthDensityFile: /home/pgranger/atmospherics/debug/MaCh3_DUNE/build/_deps/cudaprob3-src/models/PREM_4layer.dat
  #Uses single fine bin contrubtion to coarse bin if OscillatorArrayConfig==0, otherwise it uses many fine bin contributions
  OscillatorArrayConfig: 0

  #Is the binning of the oscillator specified in logarithmic or linear binning
  OscillatorIsLinear: false

  #Are we specifying the fine binning in terms of the number of fine bins per coarse bin
  OscillatorUseFineBinsPerCoarseBin: true

  #Binning uses Templates (OscillatorPrimaryBinningTemplateName,OscillatorSecondaryBinningTemplateName) from OscillatorInputFileName if OscillatorUseBinningTemplates==true, otherwise it uses the values specified below
  OscillatorUseBinningTemplates: false
  OscillatorInputFileName: "inputs/OscillationInputs/OscillogramTemplate.root"
  OscillatorPrimaryBinningTemplateName: "OscillogramTemplate_Coarse"
  OscillatorSecondaryBinningTemplateName: "OscillogramTemplate_Fine"

  #If using Binning templates, these values aren't requiredg
  OscillatornCoarseCosz: 100
  OscillatorlCoarseCosz: -1.0
  OscillatorhCoarseCosz: 1.0

  OscillatornCoarseEnergy: 100
  OscillatorlCoarseEnergy: 0.01
  OscillatorhCoarseEnergy: 1000.0

  OscillatornFineCosz: 1
  OscillatornFineEnergy: 1

  #Binning uses OscillatornFineCosz if OscillatorfineCoarseRatioCosz==-1, otherwise it uses OscillatorfineCoarseRatioCosz
  #Binning uses OscillatornFineEnergy if OscillatorfineCoarseRatioEnergy==-1, otherwise it uses OscillatorfineCoarseRatioEnergy
  OscillatorfineCoarseRatioCosz: -1.0
  OscillatorfineCoarseRatioEnergy: -1.0

  #Use Production height bin, otherwise use fixed value
  OscillatorUseProductionHeightAveraging: false
  OscillatorProductionHeightFileName: "inputs/skatm/ProdHeightDist.root"
  OscillatornProductionHeightAveragingBins: 20
  OscillatorlProductionHeightRange: 0.  #Specified in km
  OscillatorhProductionHeightRange: 50. #Specified in km

  #Use PREM model (0.497/0.468) if true, use 0.5 otherwise
  OscillatorUseChemicalComposition: true

  #Allows binning to be dynamically rebinned, this does not work with production height averaging
  OscillatorRebinMode: false

  #Do you need graphical information outputing from Oscillator
  OscillatorFillHistograms: true