---
# This is the config you plug into MaCh3 applications
# For information on YAML syntax, see https://quickref.me/yaml.html

# We start with the "General" section
# This contains the bulk of the settings
General:
  # The name of the output file. If it already exists, it will be overwritten.
  OutputFile: "MaCh3_Output.root"

  # Here we can list the paths to the DUNE sample CONFIG files.
  DuneSamples: []  

  # We can also set the value of the oscillation parameters here
  # For different oscillators we require different sets of parameters. (CUDAProb3 and NuFAST are just 2 pieces of software to calculate oscillation probabilities.)
  OscillationParameters: [0.310, 0.582, 0.0224, 7.39E-5, 2.525E-3, -2.498, 1284.9, 2.848] #CUDAProb3
  #OscillationParameters: [0.310, 0.582, 0.0224, 7.39E-5, 2.525E-3, -2.498, 1284.9, 2.848,  0.5] #NuFAST

  # Now we can look at systematics
  Systematics:
    # For historicaly reasons we call our systematics "xsec" (despite the fact that they're not necessarily cross-section related)
    # First we list our systmatic configuration yamls
    XsecCovFile: []
    # This is just a label for MaCh3 to use internally
    XsecCovName: "xsec_cov"

    # This is the step scale used in MCMC. For more information about scale factors 
    # please read: https://www2.stat.duke.edu/~pdh10/Teaching/564/Sup/mhalgorithm.pdf
    XsecStepScale: 2.38
    
# For LLH scans we need these settings
LLHScan:
  LLHScanBySample: true


# For Sigma Variations
SigmaVar:
  # This will scan at 0, ±1 and ±3 standard deviations from the "nominal" value of each systematic
  SigmaArray: [-3, -1, 0, 1, 3]
