---
General:
  OutputFile: "OutputFileName.root"
  DUNESamples: 
    - "configs/Samples/SamplePDFDune_FHC_numuselec.yaml"
    - "configs/Samples/SamplePDFDune_FHC_nueselec.yaml"
    - "configs/Samples/SamplePDFDune_RHC_numuselec.yaml"
    - "configs/Samples/SamplePDFDune_RHC_nueselec.yaml"
    - "Configs/Samples/SamplePDFDuneND_FHC_CCnumuselec.yaml"
    - "Configs/Samples/SamplePDFDuneND_RHC_CCnumuselec.yaml"

  # Nu-FIT
  OscillationParameters: [0.310, 0.582, 0.0224, 7.39E-5, 2.525E-3, -2.498, 1284.9, 2.848] #CUDAProb3
  #OscillationParameters: [0.310, 0.582, 0.0224, 7.39E-5, 2.525E-3, -2.498, 1284.9, 2.848,  0.5] #NuFAST

  # T2K-like best-fit
  #OscillationParameters: [0.307, 0.528, 0.0218, 7.53e-5, 2.509e-3, -1.601, 1284.9, 2.848] #CUDAProb3
  #OscillationParameters: [0.307, 0.528, 0.0218, 7.53e-5, 2.509e-3, -1.601, 1284.9, 2.848, 0.5] #NuFAST

  OscillatorConfigName: "Configs/OscillatorObj.yaml"

  StartFromPos: false
  PosFileName: 

  Systematics:
    # XsecCovFile: ["configs/CovObjs/xsec_covariance_DUNE_systs_2022a_FD_v3_flux.yaml"]
    XsecCovFile: 
      - "Configs/CovObjs/tdr_covs/Flux_ND+FD.yaml"
      # - "Configs/CovObjs/tdr_covs/Flux_ND+FD_uniform.yaml"
      # - "Configs/CovObjs/tdr_covs/Flux_ND_uniform.yaml"
      
      - "Configs/CovObjs/tdr_covs/Xsec_ND+FD.yaml"
      # - "Configs/CovObjs/tdr_covs/Xsec_ND+FD_uniform.yaml"
      
      - "Configs/CovObjs/tdr_covs/DetSysts_FD.yaml"
    XsecCovName: "xsec_cov"
    # Liban's step size
    # XsecStepScale: 0.05

    # Very small
    # XsecStepScale: 0.00005
    
    # Slightly less small
    # XsecStepScale: 0.0005

    # Even larger
    # XsecStepScale: 0.005

    # Even even larger
    # XsecStepScale: 0.05

    # Even even even larger
    # XsecStepScale: 0.1

    # Start with a large step scale for adaptive
    # XsecStepScale: 0.2

    # Set global step scale to be 1 when using an external adapted proposal matrix
    XsecStepScale: 1
    XsecAtGen: false 
    NDCovFile: "Configs/CovObjs/tdr_covs/det_sys_cov.root"
    OscCovFile: ["Configs/CovObjs/OscCov_PDG2021_v2.yaml"]
    OscCovName: "osc_cov"
    OscFix: ["baseline", "density"]

  Fitter:
    FitTestLikelihood: false
  MCMC:
    NSteps: 5000000
    AutoSave: 10000
  Output:
    FileName: "TestEventRates.root"
    OUTPUTNAME: "TestLLH.root"
  ProcessMCMC: No
  Seed: 0
  Debug: Yes

  # Custom throw matrix
  ThrowMatrixFile: "Configs/CovObjs/tdr_covs/NDOnlyFitProposalMatrix.root"
  # Entry in the throw matrix
  ThrowMatrixName: "xsec_cov_posfit_matrix"

# LLH Scan settings
LLHScan:
  # don't make LLH for certain systematic groups
  #LLHScanSkipVector: []
  # Save individual sample contributions to the LLH
  LLHScanBySample: false
  # Number of points we run LLH scans for each systematic
  LLHScanPoints: 100
  # Number of points for 2D scan in each direction
  #2DLLHScanPoints: 20
  # Add physical ranges for special params whose priors/errors may not be well well-defined
  ScanRanges:
    #delta_cp: [-3.14,3.14]

AdaptionOptions:
  Settings:
    # When do we start throwing from our adaptive matrix?
    StartThrow: 100000
    # When do we start putting steps into our adaptive covariance?
    StartUpdate: 0
    # When do we end updating our covariance?
    EndUpdate: 5000000
    # How often do we change our matrix throws?
    UpdateStep: 100000
    SaveNIterations: 1
    OutputFileName: ""
  Covariance:
    # So now we list individual matrices, let's just do xsec
    xsec_cov:
      # Do we want to adapt this matrix?
      DoAdaption: false
      # So we can separate out flux and xsec
      MatrixBlocks: [ ]
      # Detector systematics: all diagonal except for terms that correlate
      # MatrixBlocks: [[0,2],[2,4],[4,6], [6,7],[7,8],[8,9], [9,10],[10,11],[11,12], [12,13],[13,14],[14,15], [15,17],[17,19],[19,21], [21,22],[22,23],[23,24],[24,26]]
      # External Settings
      UseExternalMatrix: false
      ExternalMatrixFileName: ""
      ExternalMatrixName: ""
      ExternalMeansName: ""
    osc_cov:
      DoAdaption: false
      # So we can separate out flux and xsec
      MatrixBlocks: [  ]
      # External Settings
      UseExternalMatrix: false
      ExternalMatrixFileName: ""
      ExternalMatrixName: ""
      ExternalMeansName: ""


# Tests
Tests:
  SkipChecks: False
  TestResultsFile: tests/test_results/EventRatesV2TDR.txt
