# for each list specify:
# isrhc = "true for rhc or false for fhc"; #default to false
# mtupleprefix = "common part at beginning of path to mtuple files"
# mtuplesuffix = "common part at end of path to mtuple files"
# splineprefix = "common part at beginning of path to spline files"
# splinesuffix = "common part at endof path to spline files"
# up_bnd = "upper boundary on erec" #deault to 30.
# isfitqun = true for fitqun variable samples false otherwise #default to true
#Add samples to the sample list as shown below
# {
# 	name = "descriptive name for sample";
# 	mtuplefile = "path to mtuple file";
# 	splinefile  = "path to splinefile"; #!!NB MUST BE COMPATIBLE WITH BINNING OPTION SPECIFIED IN EXECUTABLE
# 	samplevecno = which number in the skmcsamples array should this go in;
# 	nutype = "nutype before oscillation";
# 	oscnutype = "nutype after oscillation";
# 	signal = true for signal samples;,
# },
SampleName: "FHC_numu"
SelectionCuts:
  - KinematicStr: "TrueXPos"
    Bounds: [ -310.0, 310.0 ]
  - KinematicStr: "TrueYPos"
    Bounds: [ -550.0, 550.0 ]
  - KinematicStr: "TrueZPos"
    Bounds: [ 50.0, 1244.0 ]
  - KinematicStr: "CVNNumu"
    Bounds: [ 0.5, 999 ]
Binning:
  BinningOpt: 1
  XVarBins: [0.,  0.5,  1.,  1.25, 1.5, 1.75, 2., 2.25, 2.5, 2.75, 3., 3.25, 3.5, 3.75, 4., 5., 6., 10.]
  YVarBins: [0.,  0.5,  1.,  1.25, 1.5, 1.75, 2., 2.25, 2.5, 2.75, 3., 3.25, 3.5, 3.75, 4., 5., 6., 10.]
SampleBools:
  isrhc: no
  iselike: no
InputFiles:
  mtupleprefix: "inputs/DUNE_CAF_files/FD_FHC_ger_"
  mtuplesuffix: "_numuselec.root"
  splineprefix: "inputs/DUNE_spline_files/FD_FHC_ger_"
  splinesuffix: "_numuselec_splines.root"
SampleCuts:
  up_bnd: 30.
DetID: 24
NSubSamples: 12
SubSamples:
  - name: "FHC_numu_x_numu"
    mtuplefile: "numu_x_numu"
    splinefile: "numu_x_numu"
    samplevecno: 0
    nutype: 14
    oscnutype: 14
    signal: false
  - name: "FHC_nue_x_nue"
    mtuplefile: "nue_x_nue"
    splinefile: "nue_x_nue"
    samplevecno: 1
    nutype: 12
    oscnutype: 12
    signal: false
  - name: "FHC_numubar_x_numubar"
    mtuplefile: "numubar_x_numubar"
    splinefile: "numubar_x_numubar"
    samplevecno: 2
    nutype: -14
    oscnutype: -14
    signal: false
  - name: "FHC_nuebar_x_nuebar"
    mtuplefile: "nuebar_x_nuebar"
    splinefile: "nuebar_x_nuebar"
    samplevecno: 3
    nutype: -12
    oscnutype: -12
    signal: false
  - name: "FHC_numu_x_nue"
    mtuplefile: "numu_x_nue"
    splinefile: "numu_x_nue"
    samplevecno: 4
    nutype: 14
    oscnutype: 12
    signal: true
  - name: "FHC_numubar_x_nuebar"
    mtuplefile: "numubar_x_nuebar"
    splinefile: "numubar_x_nuebar"
    samplevecno: 5
    nutype: -14
    oscnutype: -12 
    signal: true
  - name: "FHC_nue_x_numu"
    mtuplefile: "nue_x_numu"
    splinefile: "nue_x_numu"
    samplevecno: 6
    nutype: 12
    oscnutype: 14
    signal: true
  - name: "FHC_nuebar_x_numubar"
    mtuplefile: "nuebar_x_numubar"
    splinefile: "nuebar_x_numubar"
    samplevecno: 7
    nutype: -12
    oscnutype: -14
    signal: true
  - name: "FHC_numu_x_nutau"
    mtuplefile: "numu_x_nutau"
    splinefile: "numu_x_nutau"
    samplevecno: 8
    nutype: 14
    oscnutype: 16
    signal: true
  - name: "FHC_nue_x_nutau"
    mtuplefile: "nue_x_nutau"
    splinefile: "nue_x_nutau"
    samplevecno: 9
    nutype: 12
    oscnutype: 16
    signal: true
  - name: "FHC_numubar_x_nutaubar"
    mtuplefile: "numubar_x_nutaubar"
    splinefile: "numubar_x_nutaubar"
    samplevecno: 10
    nutype: -14
    oscnutype: -16
    signal: true
  - name: "FHC_nuebar_x_nutaubar"
    mtuplefile: "nuebar_x_nutaubar"
    splinefile: "nuebar_x_nutaubar"
    samplevecno: 11
    nutype: -12
    oscnutype: -16
    signal: true
