# for each list specify:
# isrhc = "true for rhc or false for fhc"; #default to false
# mtupleprefix = "common part at beginning of path to mtuple files"
# mtuplesuffix = "common part at end of path to mtuple files"
# splineprefix = "common part at beginning of path to spline files"
# splinesuffix = "common part at endof path to spline files"
# up_bnd = "upper boundary on erec" #deault to 30.
# isfitqun = true for fitqun variable samples false otherwise #default to true
#Add samples to the sample list as shown below
# {
# 	name = "descriptive name for sample";
# 	mtuplefile = "path to mtuple file";
# 	splinefile  = "path to splinefile"; #!!NB MUST BE COMPATIBLE WITH BINNING OPTION SPECIFIED IN EXECUTABLE
# 	samplevecno = which number in the skmcsamples array should this go in;
# 	nutype = "nutype before oscillation";
# 	oscnutype = "nutype after oscillation";
# 	signal = true for signal samples;,
# },
#SampleName: "NDGAr_FHC_CCnumu"
SampleName: "NDGAr_FHC"
SelectionCuts:
    - KinematicStr: "InFDV"
      Bounds: [1.0, 2.0]
    - KinematicStr: "IsAccepted"
      Bounds: [1.0, 2.0]
    - KinematicStr: "IsCC"
      Bounds: [1.0, 2.0]
#    - KinematicStr: "NTruePrimMuons"
#      Bounds: [1.0, 2.0]
#    - KinematicStr: "RecoRad"
#      Bounds: [0.0, 227.0]
#    - KinematicStr: "NRecoMuons"
#      Bounds: [1.0, 2.0]
#    - KinematicStr: "RecoXPos"
#      Bounds: [-209.0, 209.0]
#    - KinematicStr: "NRecoParticles"
#      Bounds: [2.0, 100.0]
#    - KinematicStr: "NRecoMuons"
#      Bounds: [1.0, 2.0]
#    - KinematicStr: "NChargedPions"
#      Bounds: [3,4]
#    - KinematicStr: "DeltaRecoEnergyThreshold"
#      Bounds: [0.09,2.0]

#    - KinematicStr: "NRecoPions"
#      Bounds: [1.0, 2.0]
#    - KinematicStr: "PiTrueEnergy"
#      Bounds: [0.0, 1.0]
#    - KinematicStr: "PiRecoEnergy"
#      Bounds: [0.0, 1.0]

Binning:
  BinningOpt: 2
#  XVarBins: [0.,  0.5,  1.,  1.25, 1.5, 1.75, 2., 2.25, 2.5, 2.75, 3., 3.25, 3.5, 3.75, 4., 5., 6., 10.]
#  YVarBins: [0., 0.1, 0.2, 0.3, 0.4, 0.6, 1.1]
  XVarBins: [0., 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2.0, 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3.0, 3.25, 3.5, 3.75, 4.0, 4.5, 5.0, 6.0, 7.0, 8.0, 9.0, 10.]
  XVarBins: [0., 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.]
  YVarBins: [0., 0.1, 0.2, 0.4, 0.7, 1.1]
SampleBools:
  isrhc: no
  isnd: yes
  iselike: no
  iscalo_reco: yes
InputFiles:
  mtupleprefix: "inputs/DUNE_NDGAr_CAF_files/NDGAr_FHC_ger_"
  mtuplesuffix: "_numuselec.root"
  splineprefix: "inputs/DUNE_NDGAr_spline_files/NDGAr_FHC_ger_"
  splinesuffix: "_numuselec_2dsplinesnewreco.root"
SampleCuts:
  up_bnd: 100000.
  muonscore_threshold: 0.5
  protondEdxscore_threshold: 0.3
  protontofscore_threshold: 0.6
  recovertexradius_threshold: 100.0
  pionenergy_threshold: 0
  B_field: 0.5
  momentum_resolution_threshold: 0.05 
  pixel_spacing: 6.0
  adc_sampling_frequency: 20.0
  drift_velocity: 3.011
NSubSamples: 4
DetID: 1
SubSamples:
  - name: "FHC_numu_x_numu"
    mtuplefile: "numu_x_numu"
    splinefile: "numu_x_numu"
    samplevecno: 0
    nutype: 14
    oscnutype: 14
    signal: false
  - name: "FHC_nue_x_nue"
    mtuplefile: "nue_x_nue"
    splinefile: "nue_x_nue"
    samplevecno: 1
    nutype: 12
    oscnutype: 12
    signal: false
  - name: "FHC_numubar_x_numubar"
    mtuplefile: "numubar_x_numubar"
    splinefile: "numubar_x_numubar"
    samplevecno: 2
    nutype: -14
    oscnutype: -14
    signal: false
  - name: "FHC_nuebar_x_nuebar"
    mtuplefile: "nuebar_x_nuebar"
    splinefile: "nuebar_x_nuebar"
    samplevecno: 3
    nutype: -12
    oscnutype: -12
    signal: false
#  - name: "FHC_numu_x_nue"
#    mtuplefile: "numu_x_nue"
#    splinefile: "numu_x_nue"
#    samplevecno: 4
#    nutype: 14
#    oscnutype: 12
#    signal: true
#  - name: "FHC_numubar_x_nuebar"
#    mtuplefile: "numubar_x_nuebar"
#    splinefile: "numubar_x_nuebar"
#    samplevecno: 5
#    nutype: -14
#    oscnutype: -12
#    signal: true
#  - name: "FHC_nue_x_numu"
#    mtuplefile: "nue_x_numu"
#    splinefile: "nue_x_numu"
#    samplevecno: 6
#    nutype: 12
#    oscnutype: 14
#    signal: true
#  - name: "FHC_nuebar_x_numubar"
#    mtuplefile: "nuebar_x_numubar"
#    splinefile: "nuebar_x_numubar"
#    samplevecno: 7
#    nutype: -12
#    oscnutype: -14
#    signal: true
#  - name: "FHC_numu_x_nutau"
#    mtuplefile: "numu_x_nutau"
#    splinefile: "numu_x_nutau"
#    samplevecno: 8
#    nutype: 14
#    oscnutype: 16
#    signal: true
#  - name: "FHC_nue_x_nutau"
#    mtuplefile: "nue_x_nutau"
#    splinefile: "nue_x_nutau"
#    samplevecno: 9
#    nutype: 12
#    oscnutype: 16
#    signal: true
#  - name: "FHC_numubar_x_nutaubar"
#    mtuplefile: "numubar_x_nutaubar"
#    splinefile: "numubar_x_nutaubar"
#    samplevecno: 10
#    nutype: -14
#    oscnutype: -16
#    signal: true
#  - name: "FHC_nuebar_x_nutaubar"
#    mtuplefile: "nuebar_x_nutaubar"
#    splinefile: "nuebar_x_nutaubar"
#    samplevecno: 11
#    nutype: -12
#    oscnutype: -16
#    signal: true
                 
#SubSamples:
#  - name: "FHC_numu_x_numu_0"
#    mtuplefile: "numu_x_numu_0"
#    splinefile: "numu_x_numu_0"
#    samplevecno: 0
#    nutype: 14
#    oscnutype: 14
#    signal: false
#  - name: "FHC_numu_x_numu_1"
#    mtuplefile: "numu_x_numu_1"
#    splinefile: "numu_x_numu_1"
#    samplevecno: 1
#    nutype: 14
#    oscnutype: 14
#    signal: false
#  - name: "FHC_numu_x_numu_2"
#    mtuplefile: "numu_x_numu_2"
#    splinefile: "numu_x_numu_2"
#    samplevecno: 2
#    nutype: 14
#    oscnutype: 14
#    signal: false
#  - name: "FHC_numu_x_numu_3"
#    mtuplefile: "numu_x_numu_3"
#    splinefile: "numu_x_numu_3"
#    samplevecno: 3
#    nutype: 14
#    oscnutype: 14
#    signal: false
#  - name: "FHC_numu_x_numu_4"
#    mtuplefile: "numu_x_numu_4"
#    splinefile: "numu_x_numu_4"
#    samplevecno: 4
#    nutype: 14
#    oscnutype: 14
#    signal: false
#  - name: "FHC_numu_x_numu_5"
#    mtuplefile: "numu_x_numu_5"
#    splinefile: "numu_x_numu_5"
#    samplevecno: 5
#    nutype: 14
#    oscnutype: 14
#    signal: false
#  - name: "FHC_numu_x_numu_6"
#    mtuplefile: "numu_x_numu_6"
#    splinefile: "numu_x_numu_6"
#    samplevecno: 6
#    nutype: 14
#    oscnutype: 14
#    signal: false
#  - name: "FHC_numu_x_numu_7"
#    mtuplefile: "numu_x_numu_7"
#    splinefile: "numu_x_numu_7"
#    samplevecno: 7
#    nutype: 14
#    oscnutype: 14
#    signal: false
#  - name: "FHC_numu_x_numu_8"
#    mtuplefile: "numu_x_numu_8"
#    splinefile: "numu_x_numu_8"
#    samplevecno: 8
#    nutype: 14
#    oscnutype: 14
#    signal: false
#  - name: "FHC_numu_x_numu_9"
#    mtuplefile: "numu_x_numu_9"
#    splinefile: "numu_x_numu_9"
#    samplevecno: 9
#    nutype: 14
#    oscnutype: 14
#    signal: false
#  - name: "FHC_numu_x_numu_10"
#    mtuplefile: "numu_x_numu_10"
#    splinefile: "numu_x_numu_10"
#    samplevecno: 10
#    nutype: 14
#    oscnutype: 14
#    signal: false
 # - name: "FHC_numu_x_numu_11"
 #   mtuplefile: "numu_x_numu_11"
 #   splinefile: "numu_x_numu_11"
 #   samplevecno: 11
 #   nutype: 14
 #   oscnutype: 14
 #   signal: false
 # - name: "FHC_numu_x_numu_12"
 #   mtuplefile: "numu_x_numu_12"
 #   splinefile: "numu_x_numu_12"
 #   samplevecno: 12
 #   nutype: 14
 #   oscnutype: 14
 #   signal: false
 # - name: "FHC_nue_x_nue"
 #   mtuplefile: "nue_x_nue"
 #   splinefile: "nue_x_nue"
 #   samplevecno: 13
 #   nutype: 12
 #   oscnutype: 12
 #   signal: false
 # - name: "FHC_numubar_x_numubar"
 #   mtuplefile: "numubar_x_numubar"
 #   splinefile: "numubar_x_numubar"
#    samplevecno: 14
#    nutype: -14
#    oscnutype: -14
#    signal: false
#  - name: "FHC_nuebar_x_nuebar"
#    mtuplefile: "nuebar_x_nuebar"
#    splinefile: "nuebar_x_nuebar"
#    samplevecno: 15
#    nutype: -12
#    oscnutype: -12
#    signal: false
