# for each list specify:
# isrhc = "true for rhc or false for fhc"; #default to false
# mtupleprefix = "common part at beginning of path to mtuple files"
# mtuplesuffix = "common part at end of path to mtuple files"
# splineprefix = "common part at beginning of path to spline files"
# splinesuffix = "common part at endof path to spline files"
# up_bnd = "upper boundary on erec" #deault to 30.
# isfitqun = true for fitqun variable samples false otherwise #default to true
#Add samples to the sample list as shown below
# {
# 	name = "descriptive name for sample";
# 	mtuplefile = "path to mtuple file";
# 	splinefile  = "path to splinefile"; #!!NB MUST BE COMPATIBLE WITH BINNING OPTION SPECIFIED IN EXECUTABLE
# 	samplevecno = which number in the skmcsamples array should this go in;
# 	nutype = "nutype before oscillation";
# 	oscnutype = "nutype after oscillation";
# 	signal = true for signal samples;,
# },
SampleName: "NDGAr_RHC_CCnumu"
SelectionCuts:
Binning:
  BinningOpt: 2
#  XVarBins: [0.,  0.5,  1.,  1.25, 1.5, 1.75, 2., 2.25, 2.5, 2.75, 3., 3.25, 3.5, 3.75, 4., 5., 6., 10.]
#  YVarBins: [0., 0.1, 0.2, 0.3, 0.4, 0.6, 1.1]
  XVarBins: [0., 2.5, 10.]
  YVarBins: [0., 1.1]

SampleBools:
  isrhc: yes
  isnd: yes
  iselike: no
InputFiles:
  mtupleprefix: "inputs/DUNE_NDGAr_CAF_files/NDGAr_RHC_ger_"
  mtuplesuffix: "_fv_ccinc.root"
  splineprefix: "inputs/DUNE_ND_spline_files/ND_RHC_ger_"
  splinesuffix: "_splines.root"
SampleCuts:
  up_bnd: 100.
NSubSamples: 1
DetID: 1
SubSamples:
  - name: "RHC_numu_x_numu_0"
    mtuplefile: "numu_x_numu_0"
    splinefile: "numu_x_numu_0"
    samplevecno: 0
    nutype: 14
    oscnutype: 14
    signal: false
#  - name: "RHC_numu_x_numu_1"
#    mtuplefile: "numu_x_numu_1"
#    splinefile: "numu_x_numu_1"
#    samplevecno: 1
#    nutype: 14
#    oscnutype: 14
#    signal: false
#  - name: "RHC_nue_x_nue"
#    mtuplefile: "nue_x_nue"
#    splinefile: "nue_x_nue"
#    samplevecno: 2
#    nutype: 12
#    oscnutype: 12
#    signal: false
#  - name: "RHC_numubar_x_numubar_0"
#    mtuplefile: "numubar_x_numubar_0"
#    splinefile: "numubar_x_numubar_0"
#    samplevecno: 3
#    nutype: -14
#    oscnutype: -14
#    signal: false
#  - name: "RHC_numubar_x_numubar_1"
 #   mtuplefile: "numubar_x_numubar_1"
 #   splinefile: "numubar_x_numubar_1"
 #   samplevecno: 4
 #   nutype: -14
 #   oscnutype: -14
 #   signal: false
 # - name: "RHC_numubar_x_numubar_2"
 #   mtuplefile: "numubar_x_numubar_2"
 #   splinefile: "numubar_x_numubar_2"
 #   samplevecno: 5
 #   nutype: -14
 #   oscnutype: -14
 #   signal: false
 # - name: "RHC_numubar_x_numubar_3"
 #   mtuplefile: "numubar_x_numubar_3"
 #   splinefile: "numubar_x_numubar_3"
 #   samplevecno: 6
 #   nutype: -14
 #   oscnutype: -14
 #   signal: false
 # - name: "RHC_nuebar_x_nuebar"
 #   mtuplefile: "nuebar_x_nuebar"
 #   splinefile: "nuebar_x_nuebar"
 #   samplevecno: 7
#    nutype: -12
#    oscnutype: -12
#    signal: false
