General:
  POT: 1.3628319e+23 
  Systematics:
    XsecCovFile: "inputs/xsec_covariance_DUNE_systs_060921_v3.root"
    XsecCovName: "xsec_cov"
    XsecAtGen: false
    OscCovFile: "inputs/oscillation_covariance_6par_nondouble_PDG2019.root"
    OscCovName: "osc_cov"
  Output:
    FileName: "Test_sigma_variations.root"
  ProcessMCMC: No
  Seed: 0
  Debug: No
SigmaVariations:
  EvalXsec: true
