---
Systematics:

##### Global energy scale uncertainties #####

- Systematic:
    Correlations:
    - TotalEScaleFD: 1.0
    - TotalEScaleNotCCNumuFD: 1.0
    SampleNames: ["FD_*"]
    Error: 0.02
    FlatPrior: false
    Names:
      FancyName: TotalEScaleFD
      ParameterName: TotalEScaleFD
    ParameterBounds:
    - -9999.0
    - 9999.0
    ParameterGroup: DetSysts
    ParameterValues:
      Generated: 0.0
      PreFitValue: 0.0
    StepScale:
      MCMC: 8.0
    Type: Functional

- Systematic:
  # Extra part, in accordance with CAFana, to account for
  # additional shifts based on Elep for events that are
  # (not true CCNumu) and (reconstructed as Nue)
  # https://github.com/DUNE/lblpwgtools/blob/3d475f50a998fbfa6266df9a0c4eb3056c0cdfe5/CAFAna/Systs/EnergySysts.h#L39
    Correlations:
    - TotalEScaleFD: 1.0
    - TotalEScaleNotCCNumuFD: 1.0
    SampleNames: ["FD_FHC_nue", "FD_RHC_nue"]
    Error: 0.02
    FlatPrior: false
    KinematicCuts:
    - IsTrueCCnumu: [-0.1, 0.1]
    Names:
      FancyName: TotalEScaleNotCCNumuFD
      ParameterName: TotalEScaleNotCCNumuFD
    ParameterBounds:
    - -9999.0
    - 9999.0
    ParameterGroup: DetSysts
    ParameterValues:
      Generated: 0.0
      PreFitValue: 0.0
    StepScale:
      MCMC: 8.0
    Type: Functional

- Systematic:
    Correlations:
    - TotalEScaleSqrtFD: 1.0
    - TotalEScaleSqrtNotCCNumuFD: 1.0
    SampleNames: ["FD_*"]
    Error: 0.01
    FlatPrior: false
    Names:
      FancyName: TotalEScaleSqrtFD
      ParameterName: TotalEScaleSqrtFD
    ParameterBounds:
    - -9999.0
    - 9999.0
    ParameterGroup: DetSysts
    ParameterValues:
      Generated: 0.0
      PreFitValue: 0.0
    StepScale:
      MCMC: 16.0
    Type: Functional

- Systematic:
    Correlations:
    - TotalEScaleSqrtFD: 1.0
    - TotalEScaleSqrtNotCCNumuFD: 1.0
    SampleNames: ["FD_FHC_nue", "FD_RHC_nue"]
    Error: 0.01
    FlatPrior: false
    KinematicCuts:
    - IsTrueCCnumu: [-0.1, 0.1]
    Names:
      FancyName: TotalEScaleSqrtNotCCNumuFD
      ParameterName: TotalEScaleSqrtNotCCNumuFD
    ParameterBounds:
    - -9999.0
    - 9999.0
    ParameterGroup: DetSysts
    ParameterValues:
      Generated: 0.0
      PreFitValue: 0.0
    StepScale:
      MCMC: 16.0
    Type: Functional

- Systematic:
    Correlations:
    - TotalEScaleInvSqrtFD: 1.0
    - TotalEScaleInvSqrtNotCCNumuFD: 1.0
    SampleNames: ["FD_*"]
    Error: 0.02
    FlatPrior: false
    Names:
      FancyName: TotalEScaleInvSqrtFD
      ParameterName: TotalEScaleInvSqrtFD
    ParameterBounds:
    - -9999.0
    - 9999.0
    ParameterGroup: DetSysts
    ParameterValues:
      Generated: 0.0
      PreFitValue: 0.0
    StepScale:
      MCMC: 18.0
    Type: Functional

- Systematic:
    Correlations:
    - TotalEScaleInvSqrtFD: 1.0
    - TotalEScaleInvSqrtNotCCNumuFD: 1.0
    SampleNames: ["FD_FHC_nue", "FD_RHC_nue"]
    Error: 0.02
    FlatPrior: false
    KinematicCuts:
    - IsTrueCCnumu: [-0.1, 0.1]
    Names:
      FancyName: TotalEScaleInvSqrtNotCCNumuFD
      ParameterName: TotalEScaleInvSqrtNotCCNumuFD
    ParameterBounds:
    - -9999.0
    - 9999.0
    ParameterGroup: DetSysts
    ParameterValues:
      Generated: 0.0
      PreFitValue: 0.0
    StepScale:
      MCMC: 18.0
    Type: Functional

##### Particle specific energy uncertainties #####

- Systematic:
    SampleNames: ["FD_*"]
    Error: 0.05
    FlatPrior: false
    Names:
      FancyName: HadEScaleFD
      ParameterName: HadEScaleFD
    ParameterBounds:
    - -9999.0
    - 9999.0
    ParameterGroup: DetSysts
    ParameterValues:
      Generated: 0.0
      PreFitValue: 0.0
    StepScale:
      MCMC: 18.0
    Type: Functional
- Systematic:
    SampleNames: ["FD_*"]
    Error: 0.05
    FlatPrior: false
    Names:
      FancyName: HadEScaleSqrtFD
      ParameterName: HadEScaleSqrtFD
    ParameterBounds:
    - -9999.0
    - 9999.0
    ParameterGroup: DetSysts
    ParameterValues:
      Generated: 0.0
      PreFitValue: 0.0
    StepScale:
      MCMC: 20.0
    Type: Functional
- Systematic:
    SampleNames: ["FD_*"]
    Error: 0.05
    FlatPrior: false
    Names:
      FancyName: HadEScaleInvSqrtFD
      ParameterName: HadEScaleInvSqrtFD
    ParameterBounds:
    - -9999.0
    - 9999.0
    ParameterGroup: DetSysts
    ParameterValues:
      Generated: 0.0
      PreFitValue: 0.0
    StepScale:
      MCMC: 7.0
    Type: Functional
- Systematic:
    SampleNames: ["FD_FHC_numu", "FD_RHC_numu"]
    Error: 0.02
    FlatPrior: false
    KinematicCuts:
    - IsTrueCCnumu: [0.9, 1.1]
    Names:
      FancyName: MuEScaleFD
      ParameterName: MuEScaleFD
    ParameterBounds:
    - -9999.0
    - 9999.0
    ParameterGroup: DetSysts
    ParameterValues:
      Generated: 0.0
      PreFitValue: 0.0
    StepScale:
      MCMC: 15.0
    Type: Functional
- Systematic:
    SampleNames: ["FD_FHC_numu", "FD_RHC_numu"]
    Error: 0.005
    FlatPrior: false
    KinematicCuts:
    - IsTrueCCnumu: [0.9, 1.1]
    Names:
      FancyName: MuEScaleSqrtFD
      ParameterName: MuEScaleSqrtFD
    ParameterBounds:
    - -9999.0
    - 9999.0
    ParameterGroup: DetSysts
    ParameterValues:
      Generated: 0.0
      PreFitValue: 0.0
    StepScale:
      MCMC: 20.0
    Type: Functional
- Systematic:
    SampleNames: ["FD_FHC_numu", "FD_RHC_numu"]
    Error: 0.02
    FlatPrior: false
    KinematicCuts:
    - IsTrueCCnumu: [0.9, 1.1]
    Names:
      FancyName: MuEScaleInvSqrtFD
      ParameterName: MuEScaleInvSqrtFD
    ParameterBounds:
    - -9999.0
    - 9999.0
    ParameterGroup: DetSysts
    ParameterValues:
      Generated: 0.0
      PreFitValue: 0.0
    StepScale:
      MCMC: 20.0
    Type: Functional
- Systematic:
    SampleNames: ["FD_*"]
    Error: 0.2
    FlatPrior: false
    Names:
      FancyName: NEScaleFD
      ParameterName: NEScaleFD
    ParameterBounds:
    - -9999.0
    - 9999.0
    ParameterGroup: DetSysts
    ParameterValues:
      Generated: 0.0
      PreFitValue: 0.0
    StepScale:
      MCMC: 6.0
    Type: Functional
- Systematic:
    SampleNames: ["FD_*"]
    Error: 0.3
    FlatPrior: false
    Names:
      FancyName: NEScaleSqrtFD
      ParameterName: NEScaleSqrtFD
    ParameterBounds:
    - -9999.0
    - 9999.0
    ParameterGroup: DetSysts
    ParameterValues:
      Generated: 0.0
      PreFitValue: 0.0
    StepScale:
      MCMC: 12.0
    Type: Functional
- Systematic:
    SampleNames: ["FD_*"]
    Error: 0.3
    FlatPrior: false
    Names:
      FancyName: NEScaleInvSqrtFD
      ParameterName: NEScaleInvSqrtFD
    ParameterBounds:
    - -9999.0
    - 9999.0
    ParameterGroup: DetSysts
    ParameterValues:
      Generated: 0.0
      PreFitValue: 0.0
    StepScale:
      MCMC: 10.0
    Type: Functional
- Systematic:
    Correlations:
    - EMEScaleFD: 1.0
    - EMEScaleCCNueFD: 1.0
    SampleNames: ["FD_*"]
    Error: 0.025
    FlatPrior: false
    Names:
      FancyName: EMEScaleFD
      ParameterName: EMEScaleFD
    ParameterBounds:
    - -9999.0
    - 9999.0
    ParameterGroup: DetSysts
    ParameterValues:
      Generated: 0.0
      PreFitValue: 0.0
    StepScale:
      MCMC: 30.0
    Type: Functional
- Systematic:
    Correlations:
    - EMEScaleFD: 1.0
    - EMEScaleCCNueFD: 1.0
    SampleNames: ["FD_FHC_nue", "FD_RHC_nue"]
    Error: 0.025
    FlatPrior: false
    KinematicCuts:
    - IsTrueCCnue: [0.9, 1.1]
    Names:
      FancyName: EMEScaleCCNueFD
      ParameterName: EMEScaleCCNueFD
    ParameterBounds:
    - -9999.0
    - 9999.0
    ParameterGroup: DetSysts
    ParameterValues:
      Generated: 0.0
      PreFitValue: 0.0
    StepScale:
      MCMC: 30.0
    Type: Functional
- Systematic:
    Correlations:
    - EMEScaleSqrtFD: 1.0
    - EMEScaleSqrtCCNueFD: 1.0
    SampleNames: ["FD_*"]
    Error: 0.025
    FlatPrior: false
    Names:
      FancyName: EMEScaleSqrtFD
      ParameterName: EMEScaleSqrtFD
    ParameterBounds:
    - -9999.0
    - 9999.0
    ParameterGroup: DetSysts
    ParameterValues:
      Generated: 0.0
      PreFitValue: 0.0
    StepScale:
      MCMC: 20.0
    Type: Functional
- Systematic:
    Correlations:
    - EMEScaleSqrtFD: 1.0
    - EMEScaleSqrtCCNueFD: 1.0
    SampleNames: ["FD_FHC_nue", "FD_RHC_nue"]
    Error: 0.025
    FlatPrior: false
    KinematicCuts:
    - IsTrueCCnue: [0.9, 1.1]
    Names:
      FancyName: EMEScaleSqrtCCNueFD
      ParameterName: EMEScaleSqrtCCNueFD
    ParameterBounds:
    - -9999.0
    - 9999.0
    ParameterGroup: DetSysts
    ParameterValues:
      Generated: 0.0
      PreFitValue: 0.0
    StepScale:
      MCMC: 20.0
    Type: Functional
- Systematic:
    Correlations:
    - EMEScaleInvSqrtFD: 1.0
    - EMEScaleInvSqrtCCNueFD: 1.0
    SampleNames: ["FD_*"]
    Error: 0.025
    FlatPrior: false
    Names:
      FancyName: EMEScaleInvSqrtFD
      ParameterName: EMEScaleInvSqrtFD
    ParameterBounds:
    - -9999.0
    - 9999.0
    ParameterGroup: DetSysts
    ParameterValues:
      Generated: 0.0
      PreFitValue: 0.0
    StepScale:
      MCMC: 20.0
    Type: Functional
- Systematic:
    Correlations:
    - EMEScaleInvSqrtFD: 1.0
    - EMEScaleInvSqrtCCNueFD: 1.0
    SampleNames: ["FD_FHC_nue", "FD_RHC_nue"]
    Error: 0.025
    FlatPrior: false
    KinematicCuts:
    - IsTrueCCnue: [0.9, 1.1]
    Names:
      FancyName: EMEScaleInvSqrtCCNueFD
      ParameterName: EMEScaleInvSqrtCCNueFD
    ParameterBounds:
    - -9999.0
    - 9999.0
    ParameterGroup: DetSysts
    ParameterValues:
      Generated: 0.0
      PreFitValue: 0.0
    StepScale:
      MCMC: 20.0
    Type: Functional
- Systematic:
    SampleNames: ["FD_*"]
    Error: 0.02
    FlatPrior: false
    Names:
      FancyName: HadResFD
      ParameterName: HadResFD
    ParameterBounds:
    - -9999.0
    - 9999.0
    ParameterGroup: DetSysts
    ParameterValues:
      Generated: 0.0
      PreFitValue: 0.0
    StepScale:
      MCMC: 20.0
    Type: Functional
- Systematic:
    SampleNames: ["FD_FHC_numu", "FD_RHC_numu"]
    Error: 0.02
    FlatPrior: false
    KinematicCuts:
    - IsTrueCCnumu: [0.9, 1.1]
    Names:
      FancyName: MuResFD
      ParameterName: MuResFD
    ParameterBounds:
    - -9999.0
    - 9999.0
    ParameterGroup: DetSysts
    ParameterValues:
      Generated: 0.0
      PreFitValue: 0.0
    StepScale:
      MCMC: 9.0
    Type: Functional
- Systematic:
    SampleNames: ["FD_*"]
    Error: 0.1
    FlatPrior: false
    Names:
      FancyName: NResFD
      ParameterName: NResFD
    ParameterBounds:
    - -9999.0
    - 9999.0
    ParameterGroup: DetSysts
    ParameterValues:
      Generated: 0.0
      PreFitValue: 0.0
    StepScale:
      MCMC: 17.0
    Type: Functional
- Systematic:
    Correlations:
    - EMResFD: 1.0
    - EMResCCNueFD: 1.0
    SampleNames: ["FD_*"]
    Error: 0.02
    FlatPrior: false
    Names:
      FancyName: EMResFD
      ParameterName: EMResFD
    ParameterBounds:
    - -9999.0
    - 9999.0
    ParameterGroup: DetSysts
    ParameterValues:
      Generated: 0.0
      PreFitValue: 0.0
    StepScale:
      MCMC: 22.0
    Type: Functional
- Systematic:
    Correlations:
    - EMResFD: 1.0
    - EMResCCNueFD: 1.0
    SampleNames: ["FD_FHC_nue", "FD_RHC_nue"]
    Error: 0.02
    FlatPrior: false
    KinematicCuts:
    - IsTrueCCnue: [0.9, 1.1]
    Names:
      FancyName: EMResCCNueFD
      ParameterName: EMResCCNueFD
    ParameterBounds:
    - -9999.0
    - 9999.0
    ParameterGroup: DetSysts
    ParameterValues:
      Generated: 0.0
      PreFitValue: 0.0
    StepScale:
      MCMC: 22.0
    Type: Functional
- Systematic:
    SampleNames: ["FD_FHC_numu", "FD_RHC_numu"]
    Error: 0.01
    FlatPrior: false
    Names:
      FancyName: RecoCVNNumuFD
      ParameterName: RecoCVNNumuFD
    ParameterBounds:
    - -9999.0
    - 9999.0
    ParameterGroup: DetSysts
    ParameterValues:
      Generated: 0.0
      PreFitValue: 0.0
    StepScale:
      MCMC: 8.0
    Type: Functional
- Systematic:
    SampleNames: ["FD_FHC_nue", "FD_RHC_nue"]
    Error: 0.01
    FlatPrior: false
    Names:
      FancyName: RecoCVNNueFD
      ParameterName: RecoCVNNueFD
    ParameterBounds:
    - -9999.0
    - 9999.0
    ParameterGroup: DetSysts
    ParameterValues:
      Generated: 0.0
      PreFitValue: 0.0
    StepScale:
      MCMC: 8.0
    Type: Functional

##### FD Fiducial Volume uncertainties #####

- Systematic:
    Correlations:
    - NumuFVFD: 0.5
    - NueFVFD: 0.5
    SampleNames: ["FD_FHC_numu", "FD_RHC_numu"]
    Error: 0.01
    FlatPrior: false
    Names:
      FancyName: NumuFVFD
      ParameterName: NumuFVFD
    ParameterBounds:
    - -9999.0
    - 9999.0
    ParameterGroup: DetSysts
    ParameterValues:
      Generated: 1.0
      PreFitValue: 1.0
    StepScale:
      MCMC: 0.1
    Type: Norm
- Systematic:
    Correlations:
    - NumuFVFD: 0.5
    - NueFVFD: 0.5
    SampleNames: ["FD_FHC_nue", "FHC_RHC_nue"]
    Error: 0.01
    FlatPrior: false
    Names:
      FancyName: NueFVFD
      ParameterName: NueFVFD
    ParameterBounds:
    - -9999.0
    - 9999.0
    ParameterGroup: DetSysts
    ParameterValues:
      Generated: 1.0
      PreFitValue: 1.0
    StepScale:
      MCMC: 0.1
    Type: Norm
