---
General:
  Verbosity: "NONE"
  CosineZIgnored: false
  CalculationType: "SubSampling"
#  CalculationType: "Binned"

SubSampling:
  FileName: "./Inputs/Atmospherics/ExampleSubSamplingBinning.root"
  CoarseEnergyAxisHistName: "CoarseEnergy"
  CoarseCosineZAxisHistName: "CoarseCosZ"
  FineEnergyAxisHistName: "FineEnergy"
  FineCosineZAxisHistName: "FineCosZ"

Binned:
  FileName: "./Inputs/Atmospherics/ExampleSubSamplingBinning.root"
  EnergyAxisHistName: "FineEnergy"
  CosineZAxisHistName: "FineCosZ"
#  FileName: "./Inputs/Atmospherics/ExampleAtmosphericBinning.root"
#  EnergyAxisHistName: "EnergyAxisBinning"
#  CosineZAxisHistName: "CosineZAxisBinning"

OscProbCalcerSetup:
  ImplementationName: "CUDAProb3"
  EarthModelFileName: "./Inputs/Atmospherics/PREM_4layer.dat"

  UseEarthModelSystematics: true
  Layers: 4

  UseProductionHeightsAveraging: false
  ProductionHeightsFileName: "./Inputs/Atmospherics/ProdHeightDist_E561_cZ520_N1_hbin2.5.root"
  ProductionHeightsHistFlavourSuffixes:
    Nue: "nue"
    Numu: "numu"
    Nutau: "numu"
    Nuebar: "nuebar"
    Numubar: "numubar"
    Nutaubar: "numubar"

  OscChannelMapping:
    - Entry: "Electron:Electron"
    - Entry: "Electron:Muon"
    - Entry: "Electron:Tau"
    - Entry: "Muon:Electron"
    - Entry: "Muon:Muon"
    - Entry: "Muon:Tau"
    - Entry: "Tau:Electron"
    - Entry: "Tau:Muon"
    - Entry: "Tau:Tau"
