---
General:
  Verbosity: "NONE"
  CosineZIgnored: true
  CalculationType: "Binned"

Binned:
  FileName: "./Configs/NuOsc/OscBinning.root"
  EnergyAxisHistName: "OscBinning"
  CosineZAxisHistName: "OscBinning"


OscProbCalcerSetup:
  ImplementationName: "NuFASTLinear"
  nNewtonIter: 15
  OscChannelMapping:
    - Entry: "Electron:Electron"
    - Entry: "Electron:Muon"
    - Entry: "Electron:Tau"
    - Entry: "Muon:Electron"
    - Entry: "Muon:Muon"
    - Entry: "Muon:Tau"
    - Entry: "Tau:Electron"
    - Entry: "Tau:Muon"
    - Entry: "Tau:Tau"
