---
# Check if MaCh3 compiles correctly

name: Build CI

# The events that trigger the workflow
on:
  pull_request:
    branches: [ develop, hwallace/feature/workflows ]
  push:
    branches: hwallace/feature/workflows

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false  # KS: Prevents cancellation of remaining jobs if one fails
      matrix:
        include:
          - os: Alma9
            file: doc/MaCh3DockerFiles/Alma9/Dockerfile
            tag: alma9latest
         # - os: Rocky9
         #   file: doc/MaCh3DockerFiles/Rocky9/Dockerfile
         #   tag: rocky9latest

    name: Build CI ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build the Docker image
      run: |
        docker build . \
          --file ${{ matrix.file }} \
          --tag ghcr.io/dune/mach3:${{ matrix.tag }} \
          --build-arg MACH3_DUNE_VERSION=${{ github.head_ref }} 
