---
name: Event Rates Beam

# To add additional run-time tests add (to matrix)
# - name: <your test>
#   test_exe: /test/<your exe>
#   test_config: path/to/tconfiguration
#   repo_linking_command: ln -sf /path/to/files/ (usually CAFs + splines)

on:
  pull_request:
    branches: [develop]
  push:
   branches: ["hwallace/patch/event_rate_ci"]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Beam Event Rate Validation
            test_exe: bin/EventRates
            test_config: CIValidations/CIInputs/CIFitConfig.yaml
            old_output: CIValidations/CIOutputs/BeamEventRates.txt
            new_output: CIValidations/CIOutputs/BeamEventRates_New.txt


    name: Run Test ${{matrix.name}}
    steps:
      # Checkout the repository code
      - uses: actions/checkout@v4
      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: start docker container with bind mount cvmfs
        env:
          MACH3_DUNE_VERSION: ${{ github.head_ref }}
        run: |
          docker build . \
          --file doc/MaCh3DockerFiles/Alma9/Dockerfile \
          --tag ghcr.io/dune/mach3:alma9_ci \
          --build-arg MACH3_DUNE_VERSION="${MACH3_DUNE_VERSION}" \
          --build-arg MACH3_DUNE_BUILD_ARGS="-DCUDAProb3Linear_ENABLED=ON -DMACH3_BUILD_TESTS=ON"

      # Run event rates
      - name: Run Event Rates
        uses: addnab/docker-run-action@v3
        with:
          image: ghcr.io/dune/mach3:alma9_ci
          shell: bash
          run: |
            source ./install/bin/setup.MaCh3.sh
            source ./install/bin/setup.NuOscillator.sh
            source ./install/bin/setup.MaCh3DUNE.sh
            ./${{matrix.test_exe}} ${{matrix.test_config}} 2>&1 |  grep -v '\[Monitor.cpp\]' | grep -v '\[manager.cpp\]' | tee ${{matrix.new_output}}

      - name: Check Outputs
        uses: LouisBrunner/diff-action@v2.0.0
        with:
          old: ${{matrix.test_output}}
          new: test_output
          mode: strict
          tolerance: same