---
name: Event Rates Beam

on:
  pull_request:
    branches: [develop]
  push:
   branches: ["hwallace/patch/event_rate_bot"]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        include:
          - name: Beam Event Rate Validation
            test_exe: build/src/EventRates
            test_config: configs/EventRates_Beam.yaml
            test_output: beam_valid.txt
            correct_output: tests/test_results/EventRatesV2TDR.txt
            build_arg: -DCUDAProb3Linear_ENABLED=ON
            # Add a list of directories to link
            cvmfs_links:
              - source: /cvmfs/dune.osgstorage.org/pnfs/fnal.gov/usr/dune/persistent/stash/MaCh3/inputs/TDR/v2/DUNE_2021_FD_splines
                target: inputs/DUNE_spline_files
              - source: /cvmfs/dune.osgstorage.org/pnfs/fnal.gov/usr/dune/persistent/stash/MaCh3/inputs/TDR/v2/DUNE_2023_FD_CAFs
                target: inputs/DUNE_CAF_files

    name: Run Test ${{matrix.name}}
    steps:
      # Set up CVMFS
      - name: Set up CVMFS
        uses: cvmfs-contrib/github-action-cvmfs@v4

      # Checkout the repository code
      - uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Start docker container with bind mount CVMFS
        env:
          MACH3_DUNE_VERSION: ${{ github.head_ref }}
        run: |
          docker build . \
          --file doc/MaCh3DockerFiles/Alma9/Dockerfile \
          --tag ghcr.io/dune/mach3:alma9test \
          --build-arg MACH3_DUNE_VERSION="${MACH3_DUNE_VERSION}" \
          --build-arg MACH3_DUNE_BUILD_ARGS=${{matrix.build_arg}}

      # Link CVMFS directories dynamically
      - name: Link CVMFS repos
        run: |
          # Create target directories if they don't exist
          mkdir -p inputs
          # Create symlinks
          ${{ toJSON(matrix.cvmfs_links) }} | jq -r '.[] | "ln -s \(.source) \(.target)"' | bash

      - name: Check CVMFS link validity
        run: |
          # Check each target
          ${{ toJSON(matrix.cvmfs_links) }} | jq -r '.[].target' | xargs python tests/test_scripts/root_file_corrupt.py

      # Run event rates
      - name: Run Event Rates
        uses: addnab/docker-run-action@v3
        with:
          image: ghcr.io/dune/mach3:alma9test
          shell: bash
          options: -v /cvmfs:/cvmfs:shared
          run: |
            source ./install/bin/setup.MaCh3.sh
            source ./install/bin/setup.NuOscillator.sh
            source ./install/bin/setup.MaCh3DUNE.sh
            ./${{matrix.test_exe}} ${{matrix.test_config}} 2>&1 | tee ${{matrix.test_output}}

      - name: Check that the files are the exact same
        uses: LouisBrunner/diff-action@v2.0.0
        with:
          old: /tests/test_results/${{ matrix.correct_output }}
          new: ${{ matrix.test_output }}
          mode: strict
          tolerance: same
