---
name: Event Rates Beam

# To add additional run-time tests add (to matrix)
# - name: <your test>
#   test_exe: /test/<your exe>
#   test_config: path/to/tconfiguration
#   repo_linking_command: ln -sf /path/to/files/ (usually CAFs + splines)

on:
  pull_request:
    branches: [develop]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Beam Event Rate Validation
            test_exe: tests/TestEventRates
            test_config: Configs/EventRates_Beam.yaml
            repo_linking_command: |
              ln -s \
              /cvmfs/dune.osgstorage.org/pnfs/fnal.gov/usr/dune/persistent/stash/MaCh3/Inputs/TDR/v2/DUNE_2021_FD_splines Inputs/DUNE_spline_files
              ln -s \
              /cvmfs/dune.osgstorage.org/pnfs/fnal.gov/usr/dune/persistent/stash/MaCh3/Inputs/TDR/v2/DUNE_2023_FD_CAFs Inputs/DUNE_CAF_files

    name: Run Test ${{matrix.name}}
    steps:
      # Set up CVMFS
      - name: Set up CVMFS
        uses: cvmfs-contrib/github-action-cvmfs@v5

      # Checkout the repository code
      - uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: start docker container with bind mount cvmfs
        env:
          MACH3_DUNE_VERSION: ${{ github.head_ref }}
        run: |
          docker build . \
          --file Docs/MaCh3DockerFiles/Alma9/Dockerfile \
          --tag ghcr.io/dune/mach3:alma9test \
          --build-arg MACH3_DUNE_VERSION="${MACH3_DUNE_VERSION}" \
          --build-arg MACH3_DUNE_BUILD_ARGS="-DCUDAProb3Linear_ENABLED=ON -DMACH3_BUILD_TESTS=ON"

      # Run event rates
      - name: Run Event Rates
        uses: addnab/docker-run-action@v3
        with:
          image: ghcr.io/dune/mach3:alma9test
          shell: bash
          options: -v /cvmfs:/cvmfs:shared
          run: |
            ${{matrix.repo_linking_command}}
            ls
            source ./install/bin/setup.MaCh3.sh
            source ./install/bin/setup.NuOscillator.sh
            source ./install/bin/setup.MaCh3DUNE.sh
            ./install/${{matrix.test_exe}} ${{matrix.test_config}}
