name: Event Rates Beam

# The events that trigger the workflow
on:
  pull_request:
    branches: [ develop ]
  push:
    branches: [hwallace/feature/event_rate_bot]

permissions:
  contents: read
  packages: write

jobs:
  setup-cvmfs:
    runs-on: ubuntu-latest
    steps:
      - uses: cvmfs-contrib/github-action-cvmfs@v4

  build:
    needs: setup-cvmfs
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false  # Prevents cancellation of remaining jobs if one fails
      matrix:
        include:
          - os: Alma9
            file: doc/MaCh3DockerFiles/Alma9/Dockerfile
            tag: alma9latest

    name: Build CI ${{ matrix.os }}
    container:
       image: ghcr.io/dune/mach3:alma9latest
       options: -v /cvmfs:/cvmfs:shared

    steps:
      - uses: actions/checkout@v4

      - name: Build Code
        run: |
          mkdir build
          cd build
          cmake ../
          make -j4
          cd ..
          source build/bin/setup.MaCh3.sh
          source build/bin/setup.NuOscillator.sh
          source build/bin/setup.MaCh3DUNE.sh
          ln -sf \
           /cvmfs/dune.osgstorage.org/pnfs/fnal.gov/usr/dune/persistent/stash/MaCh3/inputs/TDR/v1/* inputs

      - name: Run Event rates
        run: |
          ./build/bin/EventRates configs/EventRates_Beam.yaml
