name: Event Rates Beam

on:
  pull_request:
    branches: [develop]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: alma9
            file: doc/MaCh3DockerFiles/Alma9/Dockerfile
            tag: alma9test

    name: Build CI ${{ matrix.os }}

    steps:
      # Set up CVMFS
      - name: Set up CVMFS
        uses: cvmfs-contrib/github-action-cvmfs@v4


      # Checkout the repository code
      - uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: start docker container with bind mount cvmfs
        run: |
          docker build . \
          --file ${{ matrix.file }} \
          --tag ghcr.io/dune/mach3:${{ matrix.tag }} \
          --build-arg MACH3_DUNE_VERSION=${{ github.ref_name }} \
          --build-arg MACH3_DUNE_BUILD_ARGS="-DCUDAProb3Linear_ENABLED=ON -DUSE_CPU=ON"
      


      # Run event rates
      - name: Run Event Rates
        uses: addnab/docker-run-action@v3
        with:
          image: ghcr.io/dune/mach3:${{ matrix.tag }}
          shell: bash
          options: -v /cvmfs:/cvmfs:shared
          run: |          
            ln -sf \
            /cvmfs/dune.osgstorage.org/pnfs/fnal.gov/usr/dune/persistent/stash/MaCh3/inputs/TDR/v1/* \
            inputs

            source ./bin/setup.MaCh3.sh
            source ./bin/setup.NuOscillator.sh
            source ./bin/setup.MaCh3DUNE.sh
            ./src/EventRates configs/EventRates_Beam.yaml
