name: Event Rates Beam

on:
  pull_request:
    branches: [develop]
  push:
    branches: [hwallace/feature/event_rate_bot]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: Ubuntu22.04
            file: doc/MaCh3DockerFiles/Ubuntu22.04/Dockerfile
            tag: ubuntulatest

    name: Build CI ${{ matrix.os }}

    steps:
      # Set up CVMFS
      - name: Set up CVMFS
        uses: cvmfs-contrib/github-action-cvmfs@v4

      # Verify CVMFS mount
      - name: Verify CVMFS Access
        run: |
          echo "Checking CVMFS..."
          ls /cvmfs/dune.osgstorage.org/pnfs/fnal.gov/usr/dune/persistent/stash/MaCh3/inputs/TDR/v1

      # Checkout the repository code
      - uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: start docker container with bind mount cvmfs
        run: |
          docker build . \
          --file ${{ matrix.file }} \
          --tag ghcr.io/dune/mach3:${{ matrix.tag }} \
          --build-arg MACH3_DUNE_VERSION=${{ github.head_ref }} 
        
          docker run -v /cvmfs:/cvmfs:shared ghcr.io/dune/mach3:${{ matrix.tag }}

      # Build the code
      - name: Build Code
        run: |
          mkdir build
          cd build
          cmake ../
          make install -j4
          cd ..
          ln -sf \
           /cvmfs/dune.osgstorage.org/pnfs/fnal.gov/usr/dune/persistent/stash/MaCh3/inputs/TDR/v1/* inputs

      # Run event rates
      - name: Run Event Rates
        run: |
          echo "Inputs: "
          ls inputs
          echo "CVMFS: "
          ls /cvmfs/dune.osgstorage.org/pnfs/fnal.gov/usr/dune/persistent/stash/MaCh3/inputs/TDR/v1
          source build/bin/setup.MaCh3.sh
          source build/bin/setup.NuOscillator.sh
          source build/bin/setup.MaCh3DUNE.sh
          ./build/src/EventRates configs/EventRates_Beam.yaml
