name: Event Rates Beam

on:
  pull_request:
    branches: [develop]
  push:
    branches: [hwallace/feature/event_rate_bot]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: Ubuntu22.04
            file: doc/MaCh3DockerFiles/Ubuntu22.04/Dockerfile
            tag: ubuntulatest

    name: Build CI ${{ matrix.os }}
    container:
      image: ghcr.io/dune/mach3:ubuntulatest
      options: --privileged -v /cvmfs:/cvmfs:shared

    steps:
      # Checkout the repository code
      - uses: actions/checkout@v4

      # Install and set up CVMFS manually inside the container
      - name: Set up CVMFS in Container
        run: |
          sudo apt-get update
          sudo apt-get install -y cvmfs
          sudo mkdir -p /etc/cvmfs
          sudo cvmfs_config setup
          sudo mount -t cvmfs dune.osgstorage.org /cvmfs/dune.osgstorage.org

      # Verify CVMFS mount
      - name: Verify CVMFS Access
        run: |
          echo "Checking CVMFS..."
          ls /cvmfs/dune.osgstorage.org/pnfs/fnal.gov/usr/dune/persistent/stash/MaCh3/inputs/TDR/v1

      # Build the code
      - name: Build Code
        run: |
          mkdir build
          cd build
          cmake ../
          make install -j4
          cd ..
          ln -sf \
           /cvmfs/dune.osgstorage.org/pnfs/fnal.gov/usr/dune/persistent/stash/MaCh3/inputs/TDR/v1/* inputs

      # Run event rates
      - name: Run Event Rates
        run: |
          echo "Inputs: "
          ls inputs
          echo "CVMFS: "
          ls /cvmfs/dune.osgstorage.org/pnfs/fnal.gov/usr/dune/persistent/stash/MaCh3/inputs/TDR/v1
          source build/bin/setup.MaCh3.sh
          source build/bin/setup.NuOscillator.sh
          source build/bin/setup.MaCh3DUNE.sh
          ./build/src/EventRates configs/EventRates_Beam.yaml
