name: Event Rates Beam

on:
  pull_request:
    branches: [develop]

  push:
    branches: [hwallace/feature/event_rate_bot]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Event Rate Validation
            test_exe: /test/TestEventRates
            test_config: test/test_configs/EventRates_Beam_TEST.yaml
          
        

    name: Run Test ${{matrix.name}}

    steps:
      # Set up CVMFS
      - name: Set up CVMFS
        uses: cvmfs-contrib/github-action-cvmfs@v4


      # Checkout the repository code
      - uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: start docker container with bind mount cvmfs
        run: |
          docker build . \
          --file doc/MaCh3DockerFiles/Alma9/Dockerfile \
          --tag ghcr.io/dune/mach3:alma9test \
          --build-arg MACH3_DUNE_VERSION=${{ github.ref_name }} \
          --build-arg MACH3_DUNE_BUILD_ARGS="-DCUDAProb3Linear_ENABLED=ON -DMACH3_BUILD_TESTS=ON"
      

      # Run event rates
      - name: Run Event Rates
        uses: addnab/docker-run-action@v3
        with:
          image: ghcr.io/dune/mach3:alma9test
          shell: bash
          options: -v /cvmfs:/cvmfs:shared
          run: |    
          
            mkdir inputs/DUNE_spline_files inputs/DUNE_CAF_files
            ln -sf \
            /cvmfs/dune.osgstorage.org/pnfs/fnal.gov/usr/dune/persistent/stash/MaCh3/inputs/TDR/v2/DUNE_2021_FD_splines/* inputs/DUNE_spline_files
            
            ln -sf \
            /cvmfs/dune.osgstorage.org/pnfs/fnal.gov/usr/dune/persistent/stash/MaCh3/inputs/TDR/v2/DUNE_2023_FD_CAFs/* inputs/DUNE_CAF_files

            source ./bin/setup.MaCh3.sh
            source ./bin/setup.NuOscillator.sh
            source ./bin/setup.MaCh3DUNE.sh
            .${{matrix.test_exe}} ${{matrix.test_config}}
