name: PR Validation

on:
  pull_request:
    branches: [develop]

permissions:
  contents: read
  packages: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [Ubuntu22.04, Ubuntu25.10, Alma9]
          
    steps:
      - uses: actions/checkout@v4
      - name: Build ${{ matrix.os }} image
        run: |
          docker build \
            --file Docs/MaCh3DockerFiles/${{matrix.os}}/Dockerfile \
            --tag mach3-ci-${{ matrix.os }} \
            --build-arg MACH3_DUNE_VERSION="${{ github.head_ref }}" \
            .

      - name: Save image
        run: docker save mach3-ci-${{ matrix.os }} | gzip > ${{ matrix.os }}-image.tar.gz

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-image
          path: ${{ matrix.os }}-image.tar.gz

  ci-validations:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: Alma9-image

      - name: Load image
        run: gunzip -c Alma9-image.tar.gz | docker load

      - name: Mount CVMFS
        uses: cvmfs-contrib/github-action-cvmfs@v4
        with:
          cvmfs_repositories: dune.osgstorage.org

      - name: Run validations
        run: |
          docker run --rm \
            -v /cvmfs:/cvmfs:ro \
            mach3-ci-Alma9 \
            ./Docs/test_EventRates.sh