name: PR Validation

on:
  pull_request:
    branches: [develop]

permissions:
  contents: read
  packages: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu22.04, ubuntu25.10, alma9]
          
    steps:
      - uses: actions/checkout@v4

      - name: Build ${{ matrix.os }} image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Docs/MaCh3DockerFiles/${{matrix.os}}/Dockerfile
          push: false
          tags: mach3-ci-${{ matrix.os }}
          build-args: |
            MACH3_DUNE_VERSION=${{ github.head_ref }}
          load: true
          cache-from: type=gha,scope=${{ matrix.os }}
          cache-to: type=gha,mode=max,scope=${{ matrix.os }}
        
      - name: Save image
        run: docker save mach3-ci-${{ matrix.os }} | gzip > ${{ matrix.os }}-image.tar.gz

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-image
          path: ${{ matrix.os }}-image.tar.gz

  ci-validations:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: alma9-image

      - name: Load image
        run: gunzip -c alma9-image.tar.gz | docker load

      - name: Mount CVMFS
        uses: cvmfs-contrib/github-action-cvmfs@v4
        with:
          cvmfs_repositories: dune.osgstorage.org

      - name: Run validations
        run: |
          docker run --rm \
            -v /cvmfs:/cvmfs:ro \
            mach3-ci-alma9 \
            ./Docs/test_EventRates.sh